adc/graph_traversal/1260_DFS와BFS.py, adc/graph_traversal/2606_바이러스.py
- [바이러스](https://www.acmicpc.net/problem/2606)
- [DFS와 BFS](https://www.acmicpc.net/problem/1260)
---
- 1을 시작 노드로 설정하고 DFS 수행 (DFS는 동빈북 참고..ㅠㅠ)
- `visited` 변수에는 방문 했는지 안했는지 True/False로 표시
- DFS 수행 후 리턴되는 값을 sum해서 True인 개수 셈
- DFS, BFS 동빈북 참고했습니다ㅠ
- ~~**Q. 인접 리스트 생성한 후 sort()를 해줘야 제대로 된 답이 나오는데 왜그럴까요..?**~~
- DFS, BFS 돌면서 방문하는 노드 출력
---
=> [원딜] 2021.05.10

sally/README.md, sally/graph_traversal/11725_트리의 부모 찾기.cpp, sally/graph_traversal/1325_효율적인 해킹(BFS).cpp
- [11725_트리의 부모 찾기](https://www.acmicpc.net/problem/11725)
- [1325_효율적인 해킹](https://www.acmicpc.net/problem/1325)
---
- 인접리스트를 벡터로 구현하여 BFS 진행
- 간선의 수가 노드의 수에 비해 아주 작고, 입력 크기가 크기 때문에 이차원 배열을 사용해서 구현하면 메모리 초과 발생
- 단순 BFS를 노드 수 만큼 반복하여 가장 많은 노드를 감염시킨 인덱스를 출력
- 개선사항: leaf 노드에서부터 root 노드를 찾게되면, 사이클 문제에 대한 대처 방안이 필요한데, 조금 더 고민해보면... 사이클이 생기는 경우를 따로 처리하여 더 효율적인 코드를 만들 수 있을 것 같음
- 문제를 잘 읽어야겠다는 깨달음을 얻었습니다. ^.^
- 최대 전파 노드 수를 구해야하는데 노드의 최대 깊이를 카운팅해서... 1%에서 `틀렸습니다` 계속 떴음
---
=> [샐리] 2021.05.11

changwoomon/graph_traversal/2178_미로탐색.py, changwoomon/graph_traversal/2667_단지번호붙이기.py
- [2178_미로 탐색](https://www.acmicpc.net/problem/2178)
- [2667_단지번호붙이기](https://www.acmicpc.net/problem/2667)
---
- 어떻게 풀어야할지 잘 모르겠어서 [통통시절 수빈님의 강의](https://www.youtube.com/watch?v=DVAainlafRk)와 동빈북 참고했습니다 ㅠㅠ
- 맵(`_map`)을 받아올 때 `input().rstrip()`으로 하지않고 `input()`으로만 해주면 런타임에러 발생 ㅠㅠ
- `dx`, `dy` 변수를 이용해서 x, y를 바꿔주며 BFS로 탐색
- 각 점에서 상하좌우로 움직일 때 `도착지의 값 = 출발지의 값+1`로 해줌
- 각 지점의 좌표: [0, 0]부터 각 지점까지의 거리를 표시해줌
- [N-1, M-1] 지점의 거리 return
- 동빈북 p.152~154 참고
- `dx`, `dy` 변수를 이용해서 x, y를 바꿔주며 DFS로 탐색
- dfs: `_map[x][y]==1` (방문하지 않았던 지점)일 때 `cluster` 리스트에 append, `_map[x][y]=0`으로 방문 표시
- N x N for문 돌면서 값이 1인 [i, j] 지점이 있을 때
- dfs로 [i, j] 지점과 연결된 값이 1인 지점들 모두 방문 처리
- 총 단지수 +1
- num_cluster에 각 단지 내 집의 수 append
- 동빈북 p.149~151 참고
---
=> [원딜] 2021.05.12

opijae/graph_traversal/11725_트리의부모찾기.py, opijae/graph_traversal/1325_효율적인해킹.py, opijae/graph_traversal/2178_미로탐색.py, opijae/graph_traversal/2667_단지번호붙이기.py
- [미로 탐색](https://www.acmicpc.net/problem/2178)
- [단지번호붙이기](https://www.acmicpc.net/problem/2667)
---
- 4방향 탐색을 통해 주위 1값들을 찾기
- 탐색할때 out of index error가 발생 할 수 있으니 0으로 padding
- 새로운 길을 찾으면 현재 지점까지의 가중치 +1를 새로 저장
- 위의 문제와 큰틀은 동일
- 이 문제 같은 경우 모든 점들을 탐색한 다음 모든 1에 대한 점을 bfs 돌려야됨
- 1인 지점을 찾으면 해당 점을 0으로 만들면서 중복계산 방지
---
=> [후미] 2021.05.12

opijae/graph_traversal/7569_토마토.py, opijae/graph_traversal/7576_토마토.py
- [토마토](https://www.acmicpc.net/problem/7576)
- [토마토](https://www.acmicpc.net/problem/7569)
---
- 전형적인 4방향 bfs 문제이다.
- bfs내에서 while안에 for문을 돌릴때 1에 대한 좌표를 기준으로 돌린다는 것이 포인트다.
- 초기에 익은 토마토 위치 찾을 때 토마토가 다 익을것인지 어느 정도 미리 예측을 하면 꼭 bfs를 안돌 수 있지 않을까 했다.
- 결과적으로 시간이 더 걸렸다
- 마지막에 전체 칸수랑 익은 토마토개수 + 안익은 토마토 개수가 다르면 안익은 토마토가 있다는거니 print(-1)을 해준다.
- 위에 문제랑 동일 근데 3차원이여가지고 조금 헷갈린다.
---
=> [후미] 2021.05.13

changwoomon/graph_traversal/7569_토마토.py, changwoomon/graph_traversal/7576_토마토.py
- [토마토](https://www.acmicpc.net/problem/7576)
- [토마토](https://www.acmicpc.net/problem/7569)
---
- 펭귄님 풀이 참고...
- `_map` 정보를 받아온 후 `_map`의 모든 점을 돌며 익은 토마토의 좌표를 `pos`에 append
- `pos`에 저장되어있는 좌표들을 bfs로 탐색
- 여러 좌표의 익은 토마토들의 주변을 한 번에 탐색해야하기 때문에 while문 안에서 len(queue)만큼 for문을 돌려줘야한다
- bfs 이후에는 익지 않은 토마토가 있는지 `_map`을 검사
- 7576번과 동일
- 높이 H가 추가되어 queue에 z,x,y 좌표 추가해줌
---
=> [원딜] 2021.05.13

changwoomon/graph_traversal/14502_연구소.py, changwoomon/graph_traversal/16918_봄버맨.py
- [16918_봄버맨](https://www.acmicpc.net/problem/16918)
- [14502_연구소](https://www.acmicpc.net/problem/14502)
---
- `bomb 함수`: for문을 돌며 폭탄의 위치를 반환함
- `boom 함수`: `bomb 함수`에서 반환한 폭탄의 위치 + 상하좌우 4방향의 폭탄을 터뜨림
- for문을 1~N 까지 돌며 `i % 2 == 0` 일 때(조건을 왜 이렇게 줬었지..???) `bomb 함수` 실행, `i % 2 != 0` 일 때 `bomb 함수` 실행 후 모든 맵을 폭탄으로 채움
- 마지막 출력 전 `N % 2 == 0`이라면 폭탄으로 모두 채워진 맵이 출력되어야 하므로 모든 맵을 폭탄으로 채움
- 모두 폭탄으로 채워진 맵을 `deepcopy 함수`로 넣어주는 것보다 `[["O" for _ in range(C)] for _ in range(R)]`로 새로 만들어 주는게 시간이 더 빨랐다
- `virus 함수`: 맵에서 바이러스의 위치를 찾아 반환함
- `empty 함수`: 맵에서 빈 칸의 위치를 찾아 반환함
- `empty_C_3 변수`: `empty 함수`를 통해 나온 빈 칸의 위치를 3개씩 묶는 조합
- `empty_C_3` 변수를 for 문을 돎
- `tmp_map 변수`에 초기 map을 deepcopy
- `virus_bfs 함수`를 실행 후 `not_virus 함수`를 실행하여 안전 영역의 개수(`cnt 변수`)를 찾아냄
- `cnt 변수`의 최대값을 출력
---
- …
=> [원딜] 2021.05.14, 2021.05.15 (봄버맨, 연구소)

changwoomon/graph_traversal/13549_숨바꼭질3.py, changwoomon/graph_traversal/2636_치즈.py
- [2636_치즈](https://www.acmicpc.net/problem/2636)
- [13549_숨바꼭질 3](https://www.acmicpc.net/problem/13549)
---
- `cheese_count 함수`: for문을 돌며 치즈(1) 개수를 세고 반환
- `dfs 함수`: (0, 0) 부터 dfs로 탐색하며 치즈(1) 바깥부분 공기(0)의 위치를 찾는다
- `to_melt 함수`: `dfs 함수`에서 찾은 겉부분 공기 각 위치의 상하좌우가 치즈(1)이면 공기(0)으로 녹인다
- while문을 `바깥부분 공기(0)의 개수 == R*C`인 경우는 모두 공기(0)인 경우일때까지 돈다
- `Python3`는 시간초과나서 `PyPy3`로 제출했습니다ㅠㅠ
- `check 함수`: 입력받은 x에서 `x-1`, `x+1`, `2*x`를 수행
- 동생을 찾는 경우
- `2*x`를 수행한 경우에는 `True`, `cnt`를 반환
- `x-1`, `x+1`을 수행한 경우 `True`, `cnt + 1`을 반환
- 동생을 못찾는 경우
- `2*x`를 수행한 경우에는 queue에 [2*x, cnt]를 추가
- `x-1`, `x+1`을 수행한 경우에는 queue에 [각함수수행한값, cnt+1]을 추가
- `bfs 함수`: queue를 돌며 입력된 x가 동생의 위치이면 cnt를 반환, 아닌 경우 `check 함수` 수행
- `check 함수`에서 받은 condition이 True인 경우 같이 받은 tmp(시간)을 반환
---
=> [원딜] 2021.05.16

opijae/graph_traversal/14940_쉬운최단거리.py, opijae/graph_traversal/16973_직사각형탈출.py
- [직사각형탈출](https://www.acmicpc.net/problem/16973)
- [쉬운최단거리](https://www.acmicpc.net/problem/14940)
---
- 앞선 bfs랑 동일한 틀이다.
- 이 문제에서 중요한 점은 시작점과 끝점안에 벽이 있는가 판단하는 부분이다.
- 판단하는 방법
- 입력 받을때 벽인 부분 좌표를 저장
- 새로운 지점으로 이동하기 전에 시작점과 끝점 사이에 벽이 있는지 확인하고 움직인다.
- 쉬운최단거리
- dp 처럼 풀었다. 
- 조건에 맞으면 이전 거리에 +1한 값을 현재 지점에 저장한다 `_map[ni][nj] = _map[i][j]+1`
---
=> [후미] 2021.05.21

opijae/graph_traversal/14940_쉬운최단거리.py, opijae/graph_traversal/16973_직사각형탈출.py, opijae/graph_traversal/18513_샘터.py, opijae/graph_traversal/2668_숫자고르기.py
- [샘터](https://www.acmicpc.net/problem/18513)
- [숫자고르기](https://www.acmicpc.net/problem/2668)
---
- bfs로 풀었다.
- 큐에 현재 위치와 가까운 샘의 위치를 저장한다.
- 왼쪽 오른쪽 두 방향으로 이동 하면서 앞으로 가는 방향을 큐에 거리+1과 넣는다.
- `주의 : ` 집 범위가 따로 정해져 있지 않다.  방문을 set으로 해줘야 잘 된다. list 쓰면 시간초과 났다.
- 위에 배열은 1~N 까지 딱 정해져 있으니 무작위로 들어가는 아래 배열을 기준으로 잡는다.
- 위 배열에는 중복 되는게 없기 때문에 set을 사용해 중복 되는걸 지움 
- 밑 배열을 기준으로 위 배열이랑 같은 값들을 뽑아 새로 dictionary를 만든다.              
- 새로운 dictionary 위랑 밑에 값이 같으면 반복문을 종료한다.                                          
---
=> [후미] 2021.05.23

changwoomon/graph_traversal/14940_쉬운최단거리.py, changwoomon/graph_traversal/16973_직사각형탈출.py
- [직사각형 탈출](https://www.acmicpc.net/problem/16973)
- [쉬운 최단거리](https://www.acmicpc.net/problem/14940)
---
- 문제 풀이 방법은 다른 BFS 문제와 동일함
- 다른 점은 BFS를 돌기 위해 상하좌우로 움직일 때 직사각형의 변들이 벽을 만나는지 찾아야 한다는 점이다.
- 1. `where_is_2` 함수로 2(목표지점)의 위치를 찾는다.
- 2. 목표지점에서부터의 거리를 계산하고 방문한 지점은 `visited` set에 add해주며 BFS를 돈다.
- 3. BFS를 다 돌은 후에는 0이 아닌 위치 set에서 `visited` set을 빼주어 갈 수 없는 위치를 찾아 -1로 바꿔준다.
---
- 직사각형 탈출 문제 - BFS 함수
1. 방문하는 점들을 `_map`에서 -1로 표시하여 방문을 확인하는 방식
2. 방문하는 점들을 `visited` list에 추가해주어 방문을 확인하는 방식
2번 방법으로 제출할 경우 시간초과가 나옵니다.
31번째줄 if문에서 방문여부를 확인할 때 시간 차이가 있을것으로 예상되는데
`_map[xx][yy] == -1` 로 확인하는 것과  `[xx, yy] in visited`로 확인하는 것중에 두 번째 방법이 더 느린 이유가 무엇일까요..?
---
=> [원딜] 2021.05.21

changwoomon/graph_traversal/13023_ABCDE.py, changwoomon/graph_traversal/18513_샘터.py, changwoomon/graph_traversal/2668_숫자고르기.py
- [샘터](https://www.acmicpc.net/problem/18513)
- [숫자고르기](https://www.acmicpc.net/problem/2668)
---
- 아니이이이~~~ 이 문제 좀 이상하다.
- 후미님 풀리퀘에서 방문을 set으로 해줘야한다는 말 덕분에 통과할 수 있었다.
- 내 코드 34번째줄에서 `xx` 변수의 범위를 왜 저렇게 썼는지는 모르겠는데 고치기 귀찮아서 그냥 올렸다.
- 샘터를 기준으로 가장 가까운 양 옆부터 점점 옆으로 집을 짓는다. (BFS로)
- DFS로 풀려고 하다가 생각이 엄청 꼬였는데 풀긴 풀었다.
- `row` 변수에 두 번째 줄의 값을 입력받아준다.
- 1~N 범위에서 `visited` list를 계속 초기화해주며 DFS를 돈다.
- `dfs(v, i)` 함수
- v를 방문처리
- `row`변수의 v번째 값(`x`)을 받아와서 `visited`의 x번째가 방문이 아직 안되었다면 dfs를 돌고, 이미 방문됨+찾고있는 값일경우 `result`에 append 해준다
---
=> [원딜] 2021.05.22

changwoomon/graph_traversal/13023_ABCDE.py, changwoomon/graph_traversal/16954_움직이는미로탈출.py, changwoomon/graph_traversal/18513_샘터.py, changwoomon/graph_traversal/2668_숫자고르기.py
- [ABCDE](https://www.acmicpc.net/problem/13023)
- [움직이는 미로 탈출](https://www.acmicpc.net/problem/16954)
---
- 문제 해석이 어려워서 블로그 참고
- 이전의 DFS 문제들과 다른점은 재귀로 DFS를 다시 들어갔다 나온 후에는 그 지점 방문 표시를 `False`로 해줘야한다는 것이다.
- 0~N-1 에서 반복문으로 DFS를 돌리면서 depth가 4 이상이 되는 지점이 있을 때 DFS 및 반복문을 종료
- 내가 이겼다 하하
- `욱제의 캐릭터는 1초에 인접한 한 칸 또는 대각선 방향으로 인접한 한 칸으로 이동하거나, 현재 위치에 서 있을 수 있다.`
-> 가만히 있는 경우도 있으므로 `direction = ((0, 0), (1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (1, -1), (-1, 1), (-1, -1))`으로 해줘야함
- `wall_pos` 함수: `_map`에서 벽의 위치를 찾아 반환
- `wall_move` 함수: 벽의 위치를 받아와서 `_map`에서 벽을 한 칸씩 내려줌
- 이 함수를 제일 처음 만들었는데 이 함수 문제인줄 모르고 계속 BFS함수만 고치고있었다ㅠㅠ
- BFS 함수: 이전의 문제들과 비슷하나 캐릭터가 먼저 움직이고 그 후에 `wall_move` 함수를 실행해줘야하므로 `queue`의 길이만큼 for문을 다 돈 후에 `wall_move` 함수로 벽을 내려줘야함
- 벽이 0개이면 목표 지점까지 무조건 갈 수 있으므로 1 리턴
- 움직일 수 있는 지점이 0개이면 무조건 벽에 …
=> [원딜] 2021.05.23

changwoomon/string/11720_숫자의합.py, changwoomon/string/3029_경고.py
- [경고](https://www.acmicpc.net/problem/3029)
- [숫자의 합](https://www.acmicpc.net/problem/11720)
---
- 현재 시간, 나트륨을 던질 시간을 input으로 받아온다.(.split(":"))
- 현재 시간, 나트륨을 던질 시간을 초 단위로 바꾼다.
- 나트륨을 던질 시간이 현재 시간보다 크다면 그대로 빼주고, 아니라면 24\*60\*60(하루)에서 현재 시간을 뺀 후에 나트륨을 던질 시간을 더한다.
- 계산된 시간, 분, 초를 출력한다.
- input으로 숫자를 받아온다.
- for 문을 돌며 `_sum`에 더해준 후에 `_sum`을 출력한다.
---
=> [원딜] 2021.05.31

opijae/string/11720_숫자의합.py, opijae/string/3029_경고.py
- [경고](https://www.acmicpc.net/problem/3059)
- [숫자의합](https://www.acmicpc.net/problem/11720)
---
- 입력 시간을 전부 초로 바꿔서 계산
- 끝 시간이 시작 시간 보다 작다면 끝나는 시간에 `24h`을 더해 더 크게해줌
- `끝시간 - 입력시간` 을 시,분,초로 바꿔줌
- input이 들어오면 list로 바꾸고 int로 바꾼다음 다 더한다.
---
=> [후미] 2021.05.31

sally/README.md, sally/string/11365_!밀비 급일.cpp, sally/string/11720_숫자의 합.cpp, sally/string/3029_경고.py, sally/string/9046_복호화.cpp
- [11365_!밀비 급일](https://www.acmicpc.net/problem/11365)
- [9046_복호화](https://www.acmicpc.net/problem/9046)
---
- 문자열을 받고 END라면 종료, 아니라면 계속 반복문 수행
- 입력을 받아서 반대로 출력
- 입력을 받아서 공백을 제외한 문자에 `a`를 빼서, 그 값을 인덱스로 삼아, +1을 시킴(알파벳 당 개수를 count)
- count한 값과 인덱스(알파벳)을 vector로 묶어서 (count 한 값을 기준으로) 내림차순 sort
---
- 문자열에 공백이 들어갔을 때 처리 방법(getline과 입력버퍼에 관한 내용)
- cin은 '\n'를 변수에 담지 않는다. (입력버퍼에 남겨둔다.)
- getline은 '\n'를 변수에 담는다.
- 따라서, `cin.clear()` 혹은 `cin.ignore()` 필요
---
=> [샐리] 2021.06.01

changwoomon/string/1316_그룹단어체커.py, changwoomon/string/6550_부분문자열.py
- [부분 문자열](https://www.acmicpc.net/problem/6550)
- [그룹 단어 체커](https://www.acmicpc.net/problem/1316)
---
- 2개의 문자열(s, t)을 입력받아 deque에 넣어준다. (입력받은 문자열의 길이가 0이라면 break로 while 문 종료)
- t를 popleft로 한 글자씩 빼면서 s[0]과 동일할 때 s도 popleft로 한 글자 빼준다.
- s의 모든 글자가 다 빠지면 "Yes"를 출력하고, s에 글자가 남아있다면 "No"를 출력한다.
- `_input`에 입력받은 단어를 deque로 넣어주고 `_input`의 길이를 `str_len`에 넣어준다.
- 입력받은 단어 `_input`에서 popleft로 한 글자씩 빼주면서
- ck(set)에 들어있지 않다면 ck에 add, tmp에 저장, `str_len`을 1 감소시켜준다.
- ck에 들어있을 때 이전 글자와 동일하면(x==tmp가 True) `str_len`을 1 감소, 아니라면 break로 while 문을 종료
- while 문을 다 돌았을 때 `str_len`이 0이라면 그룹 단어이므로 cnt +1 해준다.
---
=> [원딜] 2021.06.03

changwoomon/string/1181_단어정렬.py, changwoomon/string/1316_그룹단어체커.py, changwoomon/string/4659_비밀번호발음하기.py, changwoomon/string/6550_부분문자열.py
- [단어 정렬](https://www.acmicpc.net/problem/1181)
- [비밀번호 발음하기](https://www.acmicpc.net/problem/4659)
---
- input을 N 번 받아오되 동일한 단어는 한 번만 출력해야 하므로 중복을 제거하기 위해 set에 담아준다.
- 받아온 중복제거 단어들을 각각의 단어 길이와 함께 `word_list`에 list로 넣어준다.
- `word_list`를 단어 길이, 단어(알파벳) 순으로 정렬한다.
- `word_list`를 for 문을 돌며 각 단어를 출력한다.
- while 문으로 비밀번호를 받아온다. 이때 받은 비밀번호가 "end"라면 break로 while 문을 종료하고, "end"가 아니라면 deque에 넣어준다.
- 비밀번호를 한 글자씩 돌면서 만족해야 할 세 가지 조건을 체크해준다.
- 세 조건 모두 True라면 acceptable, 아니라면 not acceptable을 출력한다.
---
=> [원딜] 2021.06.04

opijae/string/1181_단어정렬.py, opijae/string/4659_비밀번호발음하기.py
- [단어정렬](https://www.acmicpc.net/problem/1181)
- [비밀번호발음하기](https://www.acmicpc.net/problem/4659)
---
- 중복되면 빼니 set을 사용
- sorted를 이용해 문제 조건에 맞는 함수를 따로 만들어 비교
- 아니 print 할때 뒤에 `.`이 있는지 몰랐다......
- 문제 조건에 맞게 차근차근 조건문을 걸면 된다.
---
=> [후미] 2021.06.04

opijae/string/1764_듣보잡.py, opijae/string/20291_파일정리.py
- [듣보잡](https://www.acmicpc.net/problem/1764)
- [파일정리](https://www.acmicpc.net/problem/20291)
---
- 듣지 못한 dict를 만들고 보지 못한 사람들이 dict의 key에 있는지 판단
- 확장자 dict을 만들고 있으면 ++ 없으면 새로 만들어 준다.
---
=> [후미] 2021.06.08 

changwoomon/string/17413_단어뒤집기2.py, changwoomon/string/17609_회문.py, changwoomon/string/20437_문자열게임2.py
- [문자열 게임 2](https://www.acmicpc.net/problem/20437)
---
- 처음에는 문자열을 옮겨가면서 개수 세는 방식으로 풀었는데 시간 초과가 났다.
- 문자열 입력을 받고 `Counter`로 최대 문자의 개수가 K 개보다 작다면 조건을 만족하는 문자열을 찾을 수 없는 경우이므로 -1 출력
- 입력받은 문자열을 for 문을 돌면서 defaultdict에 각 문자의 index를 넣어준다.
- 각 문자에 저장된 index가 K 개 이상일 때만 그 사이의 길이를 `length`에 넣어준다.
- length에 -1만 담겨있다면 -1 출력하고, 아니라면 -1을 pop 해준 뒤 min 값과 max 값을 출력한다.
---
=> [원딜] 2021.06.10

peacecheejecake/README.md, peacecheejecake/string/20437_문자열게임2.py
- [20437_문자열게임2](https://www.acmicpc.net/problem/20437)
---
- 풀이과정
- 게임별로 defaultdict을 생성합니다. key는 문자열에 등장하는 문자이고, value는 index를 담은 리스트입니다.
- k개 이상 모인 문자의 index list만 모아 후보 리스트를 만듭니다.
- 만약 이 후보 리스트가 비었다면, -1을 출력합니다.
- 그렇지 않은 경우, 후보 리스트 내에서 가능한 모든 경우를 탐색합니다. 
- k - 1만큼 떨어진 index의 차를 계산해서 최솟값과 최댓값을 갱신하고, 각각에 1을 더한 값을 출력합니다.
---
=> [튜브] 2021.06.10

opijae/string/17413_단어뒤집기2.py, opijae/string/20437_문자열게임2.py
- [문자열게임2](https://www.acmicpc.net/problem/20437)
---
- 문장에 있는 unique char들을 뽑는다.
- 매 char 마다 문장의 위치를 찾은 후 끝점과 시작점의 차를 구한다.
- 정규식만 써서 풀고 싶은데 안된다 ㅠㅠㅠㅠ
---
=> [후미] 2021.06.10

sally/README.md, sally/string/20437_문자열 게임 2.py
- [20437_문자열 게임 2](https://www.acmicpc.net/problem/20437)
---
- 알파벳이 K개 미만이라면, 다음 알파벳을 체크
- 알파벳이 K개 이상이라면, 알파벳의 위치를 모두 저장
- 알파벳 간 거리가 가장 짧은 것과 가장 긴 것을 각각 구해서 출력
---
=> [샐리] 2021.06.10

opijae/tree/11725_트리의부모찾기.py, opijae/tree/9934_완전이진트리.py
- [완전이진트리](https://www.acmicpc.net/problem/9934)
- [트리의부모찾기](https://www.acmicpc.net/problem/11725)
---
- 이진 탐색 할때 순서를 그대로 출력한다.
- 완전이진 트리라 가능하다.
- defalutdict을 사용해 노드 정보들을 저장한다.
- 부모들을 돌면서 자식들을 검색한다.
- 검색된 자식들의 자식을 찾기위해 부모 배열에 저장한다.
- dfs로 순회한다.
---
=> [후미] 2021.06.11 

osmosm7/Tree/11725_트리의부모찾기.py, osmosm7/Tree/9934_완전이진트리.py
- [완전이진트리](https://www.acmicpc.net/problem/9934)
- [트리의부모찾기](https://www.acmicpc.net/problem/11725)
---
- 트리의 가운데 위치한 노드를 기준으로 잘라줌
- 양방향으로 dict에 넣어줌
- 1부터 시작해 [부모, 자식] 순으로 done에 추가
- done을 자식 순으로 정렬하고 2부터 n까지 부모 노드 출력
- 처음에 완전 bfs로 풀려다가 시간초과, 틀림의 연속이라 멘붕이었음
- string, tree 문제를 풀면서 dict의 아름다움에 대해 배우는중
---
=> [구너] 2021.06.11

peacecheejecake/README.md, peacecheejecake/tree/11725_트리의부모찾기.py, peacecheejecake/tree/9934_OBILAZAK.py
- [9934_완전이진트리](https://www.acmicpc.net/problem/9934)
- [11725_트리의부모찾기](https://www.acmicpc.net/problem/11725)
---
- 풀이과정
- k층에는 2 ** (K - k)에 홀수를 곱한 index가 포함된다는 규칙으로 2차원 리스트 indices를 만듭니다.
- 이 index를 따라 paper의 각 원소를 출력합니다.
- 풀이과정
- 모든 간선을 기록해 그래프를 만들고, BFS로 탐색합니다.
- 루트인 1에서 시작하므로, 연결된 두 노드 중 먼저 발견된 노드가 부모가 됩니다.
---
=> [튜브] 2020.06.11

changwoomon/tree/1991_트리순회.py, changwoomon/tree/5639_이진검색트리.py
- [트리 순회](https://www.acmicpc.net/problem/1991)
- [이진 검색 트리](https://www.acmicpc.net/problem/5639)
---
- tree를 dict로 받아온다. (key: node, value: [left, right])
- 전위 순회, 중위 순회, 후위 순회 함수를 돌고 각 순회 결과를 출력한다.
- 전위 순회 결과를 받아온다.
- 루트보다 큰 노드가 나타나는 index를 찾아 왼쪽, 오른쪽 서브트리로 나눈다.
- 후위 순회이므로 왼쪽, 오른쪽 서브트리를 순회 후 root를 출력한다.
---
=> [원딜] 2021.06.14

osmosm7/Tree/1068_트리.py
- [트리](https://www.acmicpc.net/problem/1068)
---
- 풀이과정
- 1. 인접 리스트 생성 (부모 > 자식 노드 방향)
- 2. 루트 노드 부터 시작
- 3. DFS로 노드 돌면서 자식노드 수 0개면 cnt +=1, return
- 4. 핵심 : 지우는 노드 방문했을때 지우는 노드의 부모노드의 자식 노드가 지우는 노드 1개면 cnt +=1 아니면 return
=> [구너] 2021.06.15

sally/README.md, sally/tree/1068_트리.cpp
- [1068_트리](https://www.acmicpc.net/problem/1068)
---
- for문을 돌면서 N회동안 입력을 받음(-1 입력한 인덱스가 root 노드)
- 입력을 받은 값은 해당 인덱스의 벡터에 push_back(부모에 매달려 있는 형식)
- root 노드로 부터 DFS를 수행(지워야하는 타겟 노드는 방문하지 않음)
- target 노드를 방문하지 않으면, 그 아래 매달려있는 노드를 모두 방문하지 않게 됨
- 자신에게 달린 노드들 중 하나에라도 방문하게 된다면 result에 값을 추가하지 않음
- 자신에게 달린 노드 모두를 방문하지 못하거나, 자신에게 달려있는 노드가 없다면, 그 노드가 leaf node이므로 `result++`
---
=> [샐리] 2021.06.15

peacecheejecake/README.md, peacecheejecake/tree/1068_트리.py
- [1068_트리](https://www.acmicpc.net/problem/1068)
---
- 풀이과정
- 각 노드의 자식 노드를 이차원 list에 저장하여 그래프를 생성합니다.
- 루트 노드에서 출발하여 재귀적으로 그래프를 탐색합니다.
- 각각의 자식 노드에서 비롯된 리프 노드 개수를 더해주되, 자식 노드가 지워야 하는 노드라면 세지 않도록 합니다.
- 단, 지워야 하는 노드가 현재 탐색하는 노드의 유일한 자식 노드인 경우, 현재 노드가 리프 노드가 되므로 1을 더해줍니다.
- 또한 루트 노드는 어떠한 노드의 자식 노드도 아니므로, 루트 노드를 지우는 경우에는 무조건 0을 출력하도록 예외 처리를 합니다.
---
=> [튜브] 2021.06.15

sally/README.md, sally/tree/14675_단절점과 단절선.cpp
- [14675_단절점과 단절선](https://www.acmicpc.net/problem/14675)
---
- 단절선 질의가 들어오면 무조건 yes 출력
- 단절점 질의가 들어오는 경우, 해당 노드에 연결된 간선의 수가 2 이상인 경우에 yes 출력, 아니라면 no 출력
- 간선 정보를 입력받을 때, 간선에 매달린 노드 정보를 통해서 `노드에 연결된 간선의 수`를 업데이트 할 수 있음
---
=> [샐리] 2021.06.17

changwoomon/tree/14675_단절점과단절선.py
- [단절점과 단절선](https://www.acmicpc.net/problem/14675)
---
- 단절선인지에 대한 질의에 대한 답은 무조건 yes이다.
- 아무 생각 없이 문제 푸느라 tree를 저장할 때 node를 다 저장해 줬는데, 그냥 개수만 세어주는 것이 훨씬 빠를 거 같지만 이력서 써야 해서 이만~
---
=> [원딜] 2021.06.17

opijae/tree/14675_단절점과단절선.py, opijae/tree/6416_트리인가.py
- [단절점과단절선](https://www.acmicpc.net/problem/14675)
---
- 사이클이 없는 트리느 모든 간선은 단절선이다.
- 정점이 다른 정점이랑 연결된 점이 2개 이상이면 그 점은 단절점이다.
=> [후미] 2021.06.17

osmosm7/Tree/14675_단절점과단절선.py
- [단절점과단절선](https://www.acmicpc.net/problem/14675)
---
- 풀이과정
- 1. 단절선에 대한 질문은 무조건 yes였다.
- 2. 각 노드들의 연결 edge 수를 나타내는 모두 0인 list 생성
- 3. 엣지에 대한 정보를 받으면 엣지에 포함된 node의 위치의 list를 1씩 더해줌
- 4. 단절점에 대한 질문을 받으면 노드에 연결된 엣지 수가 2개 이상이면 yes 아니면 no 출력
---
- 그래프내의 단절점을 모두 찾는 '단절점'(11266) 문제는 플래티넘5 난이도 추후에 도전하자!
- sys.stdin.readline() 을 이용해 input을 받지 않으면 시간초과가 뜬다. - 지금까지 몰랐음
---
=> [구너] 2021.06.17

peacecheejecake/README.md, peacecheejecake/tree/6416_트리인가.py
- [6416_트리인가?](https://www.acmicpc.net/problem/6416)
- [6416_단절점과단절선](https://www.acmicpc.net/problem/14675)
---
- 풀이과정
- 입력받은 한 줄이 빈 문자열인 경우, 다음 줄을 입력받습니다.
- `0 0`이 나올 때까지 노드는 set, 간선은 list에 저장합니다.
- 음수가 입력되는 경우, `end_of_game`을 True로 하고 이 값이 False일 경우만 트리 여부를 판단합니다.
- `is_tree`의 초기값을 True로 하고, 빈 그래프인 경우 이 값을 그대로 가져갑니다.
- 빈 그래프가 아닌 경우, 조건 1, 2, 3에 대한 판단을 순차적으로 합니다.
- 조건 3에 대해서는 dfs를 재귀적으로 수행하되, node가 다시 발견되는 경우 사이클이 발생한 것으로 판단합니다.
- `is_tree` flag에 따라 알맞은 문장을 출력합니다.
--- 
- 주어진 대로 해서 통과하긴 했는데, 조건 1, 2를 만족하고 3에 위배되는 경우가 무엇이 있을까요? 잘 떠오르지가 않네요.
- 재귀 함수가 아닌 방법으로 구현할 수 있을까요?
=> [튜브] 2021.06.16

peacecheejecake/README.md, peacecheejecake/tree/14675_단절점과단절선.py, peacecheejecake/tree/6416_트리인가.py
- [14675_단절섬과단절선](https://www.acmicpc.net/problem/14675)
---
- 풀이과정
- (아니 이게 맞다고..?)
- 모든 간선은 bridge
- 가장 끝에 있는 노드, 즉 1번 등장하는 노드만 cut vertex
---
=> [튜브] 2021.06.17

changwoomon/README.md, changwoomon/string/20437_문자열게임2.py, changwoomon/tree/14675_단절점과단절선.py, changwoomon/tree/17073_나무위의빗물.py
- [나무 위의 빗물](https://www.acmicpc.net/problem/17073)
---
- i번 정점에 쌓인 물의 양의 기댓값이 어쩌구~ 하면서 어려워 보이게 설명하지만 결국엔 leaf node의 개수를 묻는 문제이다.
- leaf node의 개수를 구한 후 1번 노드에 고인 물의 양을 leaf node의 개수로 나눈 것을 출력한다.
- 끝!
---
=> [원딜] 2021.06.18

osmosm7/Tree/17073_나무위의빗물.py
- [나무위의빗물](https://www.acmicpc.net/problem/17073)
---
- 풀이과정
- 트리를 방향에 맞춰 재배치 해야하나 했는데 아니었음
- 물의 이동이 끝난다 == 가장 밑의 자식노드에게 물이갔다
- 가장 밑의 자식 노드의 갯수만 파악하면 된다. > 루트 노드 제외 연결 노드가 1이면 cnt +=1
- 전체 물의 양 / 자식 노드의 수
---
=> [구너] 2021.06.18

opijae/tree/14675_단절점과단절선.py, opijae/tree/17073_나무위의빗물.py, opijae/tree/6416_트리인가.py
- [나무위의빗물](https://www.acmicpc.net/problem/17073)
---
- 자식 노드의 개수를 찾는 문제이다.
- 자식 노드 판별은 노드 리스트를 만들어 인접 노드의 개수가 하나인 개수를 센다
---
=> [후미] 2021.06.18

peacecheejecake/README.md, peacecheejecake/tree/14675_단절점과단절선.py, peacecheejecake/tree/17073_나무위의빗물.py, peacecheejecake/tree/6416_트리인가.py
- [17073_나무위의빗물](https://www.acmicpc.net/problem/17073)
---
- 풀이과정
- 물이 더 이상 움직이지 않을 때는 물은 전부 리프 노드에 있을 것입니다.
- 자식 노드가 여러 개 있을 때 각각에 물을 줄 확률이 동일하므로, 전체 물의 양을 리프 노드 개수로 나누면 됩니다.
- 입력에서 한 번 등장하는 노드를 리프 노드로 봅니다. 다만, 루트 노드의 자식 노드가 하나만 있을 경우도 있으므로, 루트 노드인 1번 노드는 제외합니다.
---
=> [튜브] 2021.06.18

changwoomon/tree/1068_트리.py
- [트리](https://www.acmicpc.net/problem/1068)
---
- 입력받은 부모 노드들을 돌면서 각 노드의 자식들을 set으로 되어있는 트리를 만들어준다.
- 제거할 노드부터 BFS를 돈다.
- `tree, visited`를 for 문을 돌면서 자식 노드가 하나도 없을 때 visited에 방문하지 않은 노드(삭제되지 않는 노드)를 세어준다.
- 트리가 일자 형태 일 때는 제거한 노드의 부모 노드가 leaf node가 되므로 그 경우도 세어준다.
---
=> [원딜] 2021.06.15

changwoomon/README.md, changwoomon/dynamic_programming_1/10870_피보나치수5.py, changwoomon/dynamic_programming_1/2839_설탕배달.py
- [피보나치 수 5](https://www.acmicpc.net/problem/10870)
- [설탕 배달](https://www.acmicpc.net/problem/2839)
---
- n <= 1일 때는 n을 그대로 return 하고 2 이상일 때는 F_n = F_{n-1} + F_{n-2}이므로 F_{n-1} + F_{n-2}을 return 한다.
- N >= 0인 동안 while 문을 돌면서 N이 5의 배수라면 N을 5로 나눈 몫을 봉지 개수에 더해 return 하고, 배수가 아니라면 5의 배수가 될 때까지 N에서 3씩 빼주며 봉지 개수 +1 해준다.
---
=> [원딜] 2021.06.21

opijae/dynamic_programming_1/10870_피보나치수5.py, opijae/dynamic_programming_1/2839_설탕배달.py
- [피보나치수5](https://www.acmicpc.net/problem/10870)
- [설탕배달](https://www.acmicpc.net/problem/2839)
---
- `fib=[0,1]` 로 피보나치 배열이 시작하면서 
- `fib[n]=fib[n-1]+fib[n]` 이런 식으로 배열이 채워진다.
- 옯겨야되는 설탕양 만큼 배열을 만듬
- 작은 봉지만큼 `arr`을 채움
- 큰 봉지로 채워 질 수록 더 적은 봉지의 개수를 쓴다는 점을 이용
---
=> [후미] 2021.06.21

peacecheejecake/README.md, peacecheejecake/dynamic_programming_1/10870_피보나치수5.py, peacecheejecake/dynamic_programming_1/2839_설탕배달.py
- [10870_피보나치수5](https://www.acmicpc.net/problem/10870)
- [2839_설탕배달](https://www.acmicpc.net/problem/2839)
---
- 풀이과정
- -2, -1번째 수를 -1, 1로 설정하여 0, 1번째 수가 0, 1이 되게 한다.
- N + 1번만큼 루프를 돌며 점화식에 따라 계산한다.
- 풀이과정
- 일단 5kg짜리 봉지를 최대한 많이 챙긴다.
- 나머지 무게에 따라 어떻게 조정할지 정책을 세우고 `bag_adj`에 저장한다. (5kg, 3kg 순)
- 정책에 의해 빼야 하는 5kg 봉지 수가 최대로 챙길 수 있는 5kg 봉지 수보다 많으면, 불가능한 것으로 판단한다.
- 그렇지 않은 경우 조정된 봉지 수를 출력한다.
---
- 제 설탕 배달 풀이도 DP라고 할 수 있을까요?
=> [튜브] 2021.06.21

dkswndms4782/dynamic_programming_1/10870_피보나치수5.cpp, dkswndms4782/dynamic_programming_1/2839_설탕배달.cpp
- [피보나치 수 5](https://www.acmicpc.net/problem/10870)
- [설탕 배달](https://www.acmicpc.net/problem/2839)
---
+ arr 배열을 전역변수로 둔 후 dp(n)함수에서 return한 값을 출력하는 방식
+ n이 0일때는 0, 1과2일때는 1을 return
+ arr[n]이 0보다 클때는 arr[n] return 
+ arr[n]에 dp(n-1) + dp(n-2)를 할당해준 후 arr[n]을 Return
+ n이 2이하, 4일때는 -1 출력
+ n이 3이나 5일때는 1 출력
+ arr[5001]  = { 0, }; 전역변수 선언. dp함수에서 arr[3]과 arr[5]에 1을 넣어준 후, for문으로 6부터 Bottom-up방식으로 arr를 채움(사용 변수 : i)
+ arr[i-1]값이 있을때 arr = arr[i-3] + 1
+ arr[i-5]의 값이 있고, arr[i]값이 0이 아니면 더 작은 값 arr[i]에 할당(arr[i-3]의 값이 없을때는 arr[i]가 0)
+ arr[i-5]의 값이 있고, arr[i]가 0이면 arr[i-5]+1값을 arr[i]에 할당
+ return arr[n]
-----
=> [감자] 2021.06.21

peacecheejecake/README.md, peacecheejecake/dynamic_programming_1/1010_다리놓기.py, peacecheejecake/dynamic_programming_1/10870_피보나치수5.py, peacecheejecake/dynamic_programming_1/2748_피보나치수2.py, peacecheejecake/dynamic_programming_1/2839_설탕배달.py
- [2748_피보나치수2](https://www.acmicpc.net/problem/2748)
- [1010_다리놓기](https://www.acmicpc.net/problem/1010)
---
- -2번째, -1번째 (가상의) 수를 각각 -1, 1로 정한다.
- 주어진 식에 따라 구한다.
- 어제와 다른 풀이가 생각나지 않는다.
- 다리는 교차할 수 없으므로, 동쪽 m개 중에 n개 지점이 확정되면, 이를 서쪽의 n개 지점과 순서대로 연결해야 한다.
- 따라서 다리를 지을 수 있는 경우의 수는 m개 중에 n개를 고르는 조합의 수와 같다.
- T의 범위가 주어지지 않았으므로 입력은 `sys.stdin.readline`으로 받는다.
- DP로는 어떻게 풀지 모르겠다.
=> [튜브] 2021.06.22

dkswndms4782/dynamic_programming_1/1010_다리놓기.cpp, dkswndms4782/dynamic_programming_1/2748_피보나치수2.cpp
- [2748_피보나치수2](https://www.acmicpc.net/problem/2748)
- [1010_다리놓기](https://www.acmicpc.net/problem/1010)
---
- 피보나치5와 같지만, n의 값이 최대 90이었기때문에 c++에서는 int 배열에 값들을 다 담을 수 없었음
- 그래서 long long int로 배열 자료형 선언
- factorial을 30까지 다 해준 후 arr에 넣으려니 문제 발생(unsigned long long으로 풀어도 안됨)
- 그래서 double로 바꿔서 계산한 후 ceil함수로 소수점 반올림, 후 int로 바꿔 출력했으나 틀림
- 조합문제라고 생각했기때문에 m*(m-1)* ... * (m - n + 1)/n!을 사용
- num함수로 m*(m-1)* ... * (m - n + 1)이부분 구해줌
- factorial은 계속 구해주면 0.5초안에 풀지못할거같아 15!까지는 arr에 넣어줌
- n이 m과 같으면 1 출력, 아니면 n과 m-n중 더 작은 값을 n으로 할당하고 num(m,n)/factorial[n]출력
—
=> [감자] 2021.06.22

changwoomon/README.md, changwoomon/dynamic_programming_1/1010_다리놓기.py, changwoomon/dynamic_programming_1/10870_피보나치수5.py, changwoomon/dynamic_programming_1/2748_피보나치수2.py, changwoomon/dynamic_programming_1/2839_설탕배달.py
- [피보나치 수 2](https://www.acmicpc.net/problem/2748)
- [다리 놓기](https://www.acmicpc.net/problem/1010)
---
- 21일 문제 `피보나치 수 5` 코드 그대로 쓰려고 했는데 재귀로 제출하니까 시간 초과가 났다.
- for 문을 돌면서 n 번째 피보나치 수를 구한 후 출력한다.
- 경우의 수 문제이다. M Combination N을 구하면 된다.
- 팩토리얼을 구현한 뒤 M C N을 계산하여 출력한다.
---
=> [원딜] 2021.06.22

osmosm7/dynamic_programming_1/17626_FourSquares.py, osmosm7/dynamic_programming_1/9655_돌게임.py
- [돌게임](https://www.acmicpc.net/problem/9655)
- [Four Squares](https://www.acmicpc.net/problem/17626)
---
- 풀이과정
- 입력 : [1,2,3,4,5,6,7,8,9,10]
- 정답 : 상근/창영/상근/창영/상근/창영
- 위와 같은 패턴찾아서 홀수면 상근 짝수면 창영
- 4이하인 경우 패턴이 고정되서 n%4 의 답과 같음을 이용하는게 원래풀이 인거 같다.
- 풀이과정
- dp는 시간초과 엄청 났음...
- 
- 현재 수 a 에 대해 for 문 돌면서 각 i 에 대해
-  a번째 = a-i**2 번째+ i**2 번째 
- dp로 내려다 시간 초과 때문에 3시간 걸렸습니다...
- pypy3를 몰랐는데 찾아서 쓸 수 밖에 없었습니다...
- pypy3 인정인가요??
---
=> [구너] 2021.06.23

osmosm7/dynamic_programming_1/1463_1로만들기.py, osmosm7/dynamic_programming_1/17626_FourSquares.py, osmosm7/dynamic_programming_1/9095_123더하기.py, osmosm7/dynamic_programming_1/9655_돌게임.py
- [1로 만들기](https://www.acmicpc.net/problem/1463)
- [1,2,3 더하기](https://www.acmicpc.net/problem/9095)
---
- 풀이과정
- 0위치에 큰 값을 넣어둠
- 1인 경우는 0
-  2,3 인경우는 1
- a,b를 0으로 고정
- i가 2,3으로 나눠지는 경우에는 각 몫을 a,b으로 갱신
- dp[i] = min(dp[i-1],dp[a],dp[b])+1
- 풀이과정
- dp 리스트 생성
- 1,2,3 에 해 1,2,4 넣어줌
- 4부터는 dp[i] = dp[i-1] + dp[i-2] + dp[i-3] 
---
- 4 squares가 생각하기 훨씬 어려운거 같은데 구현으로 풀면 쉬워서 난이도가 그런가??
- 이거 풀고 4 squares 풀었으면 좀 빨리 떠올랐을듯!
---
=> [구너] 2021.06.24

dkswndms4782/dynamic_programming_1/1463_1로만들기.cpp, dkswndms4782/dynamic_programming_1/17626_FourSquares.cpp, dkswndms4782/dynamic_programming_1/9095_1,2,3더하기.cpp, dkswndms4782/dynamic_programming_1/9655_돌게임.cpp
- [1로 만들기](https://www.acmicpc.net/problem/1463)
- [1,2,3 더하기](https://www.acmicpc.net/problem/9095)
---
- dp 함수에서 몇번에 걸쳐 1로 만들 수 있는지 return
- n이 1일경우 0을 return 해줘야함. 안하면 메모리오류ㅠㅠㅠ
- n이 3으로 나눠떨어질경우 arr[n] = arr[n/3] + 1
- n이 2로 나눠떨어질경우 arr[n] = arr[n/2] + 1
- arr[n] = arr[n-1] + 1
- 위 세가지중 가장 작은 값을 arr에 할당
- n이 11까지이므로 bottom-up방식으로 11까지 arr를 채움
- 마지막 더하는 숫자의 경우에 따라 몇가지 경우의 수가 나올 수 있는지 arr에 할당
- arr[i-1]은 arr[i]에서 마지막으로 더해진 숫자가 1인 경우의 수
- arr[i] = arr[i-1] + arr[i-2] + arr[i-3]
=> [감자] 2021.06.24

peacecheejecake/README.md, peacecheejecake/dynamic_programming_1/1463_1로만들기.py, peacecheejecake/dynamic_programming_1/17626_FourSquares_1.py, peacecheejecake/dynamic_programming_1/17626_FourSquares_2.py, peacecheejecake/dynamic_programming_1/9095_123더하기.py, peacecheejecake/dynamic_programming_1/9655_돌게임.py
- [1463_1로 만들기](https://www.acmicpc.net/problem/1463)
- [9095_1, 2, 3 더하기](https://www.acmicpc.net/problem/9095)
---
- 크기가 N+1인 `table`을 0으로 초기화한다.
- 2 이상 N 이하인 자연수 k에 대해, 다음과 같은 규칙으로 `table[k]`를 갱신한다.
1. 가능한 연산을 했을 때의 수를 모두 `cands`에 담는다.
2. `cands`에 담긴 수 중 필요한 연산 횟수가 최소인 경우에 1을 더한 값이 k의 연산 횟수이다.
- T의 범위가 주어져 있지 않으므로, `sys.stdin.readline`으로 입력을 받는다.
- `create_table` 함수로 table을 만든다. 문제의 경우 `max_n=10`이고, table을 만드는 규칙은 다음과 같다.
1. 3 이하의 n에 대해서는 각각 1, 2, 4로 지정한다.
2. n이 4 이상인 경우, (가장 첫번째 수가 1, 2, 3인 경우를 나타내는) 직전 3개 원소를 더한다.
- 각 케이스에서, `table[n]`을 출력한다.
=> [튜브] 2021.06.24

peacecheejecake/README.md, peacecheejecake/dynamic_programming_1/17626_FourSquares_1.py, peacecheejecake/dynamic_programming_1/17626_FourSquares_2.py, peacecheejecake/dynamic_programming_1/9655_돌게임.py
- [9655_돌게임](https://www.acmicpc.net/problem/9655)
- [17626_FourSquares](https://www.acmicpc.net/problem/17626)
---
- 가져갈 수 있는 돌 개수가 모두 홀수이므로, 홀/짝 여부로 게임의 승자가 결정된다.
- 풀이 1
- 0부터 n까지의 정보를 담은 `table`의 원소를 모두 0으로 초기화한다.
- 1부터 n까지 자연수(k)에 대해 차례로 제곱수 개수의 최솟값을 구하고, table에 저장한다.
- k 이하의 완전제곱수를 r이라고 하면, k에서의 최솟값은 `table[k - r * r]` 중 최솟값이 될 것이다.
- 시간의 단축을 위해 r의 범위는 k / 2의 제곱근 이상으로 제한한다.
- 작은 수부터 차례로 풀어가기 때문에, 모든 경우에 table을 이용할 수 있다.
- 대신 시간이 오래 걸려서 PyPy에서밖에 통과하지 못했다.
- 풀이 2
- 라그랑주의 증명을 바탕으로 한 풀이이다. (문제를 잘 읽자)
- `find_min`함수가 모든 일을 하며, 이 함수는 다음과 같이 동작한다.
1. `squares`에 n 이하의 모든 제곱수를 저장한다.
2. `n`이 `squares`에 있으면 1을 반환한다.
3. n/2의 제곱근 이상 n의 제곱근 이하의 범위의 수 `r`에 대해, `n - r ** 2`이 `squares`의 원소라면 2를 반환한다.
4. 3과 마찬가지 방법으로 세 개의 제곱수를 합해 n이 되는지 검사하고, 그러한 경우 3을 반환한다.
5. 나머지 경우에는 4를 반환한다.
=> [튜브] 2021.06.23

opijae/dynamic_programming_1/17626_FourSquares.py, opijae/dynamic_programming_1/9655_돌게임.py
- [돌게임](https://www.acmicpc.net/problem/9655)
- [FourSquares](https://www.acmicpc.net/problem/17626)
---
- SK는 1,3만 고를 수 있으니 1,3,5,7,9.... 식으로 홀수인 경우 이기게 된다.
- 제곱수인 경우
- 2개로 나뉘는 경우
- 3개로 나뉘는 경우를 각각 고려해 푼다.
---
=> [후미] 2021.06.23

osmosm7/Basic/Untitled.ipynb, osmosm7/dynamic_programming_1/11726_2xn타일링.py, osmosm7/dynamic_programming_1/1463_1로만들기.py, osmosm7/dynamic_programming_1/2579_계단오르기.py, osmosm7/dynamic_programming_1/9095_123더하기.py
- [2xn 타일링](https://www.acmicpc.net/problem/11726)
- [계단오르기](https://www.acmicpc.net/problem/2579)
---
- 풀이과정
- dp[i]  = dp[i-1] + dp[i-2]
- 
- dp는 정말 아이디어 짜는게 어렵다.....
- 풀이과정
- dfs로 했다가 시간초과.....
- dp로 푸는도중 11이면 무조건 2인 조건때문에 어려웠음
- 블로그에서 두가지 경우에 대해 나눠서 하는 아이디어 얻음
- 1,2에 대해서는 예외 처리
-  dp[0] = 0, dp[1] = 1의 점수, dp[2] = 1,2의점수 합
- dp[i]에 대해 1,2 전으로 부터 온 2가지 경우 생각
- 1. i-1 에서 왔음 > i,i-1 연속했으니 i-1 이전에는 i-3이어야함
> i-1의 점수 + dp[i-3]
- 2. i-2에서 왔음 
- > dp[i-2]
- 그러므로 dp[i] = max(dp[i-2], dp[i-3] + i-1의 점수) + i 점수
---
- 계단오르기 문제 input =1,2에 대해 따로 예외로 두지 않고 풀 수도 있나요??
---
* 참고 블로그 : https://sungmin-joo.tistory.com/18
=> [구너] 2021.06.25

.mergify.yml
This change has been made by @CoodingPenguin from https://mergify.io config editor.
=> [Mergify] Add Auto Review-requested

.mergify.yml
This change has been made by @CoodingPenguin from https://mergify.io config editor.
=> [Mergify] Change review-requested from teams to users

.mergify.yml
This change has been made by @CoodingPenguin from https://mergify.io config editor.
=> [Mergify] Add automatic assign-yourself

osmosm7/dynamic_programming_1/11053_가장긴증가하는부분수열.py, osmosm7/dynamic_programming_1/11727_2xn타일링2.py
- [2 x n 타일링 2](https://www.acmicpc.net/problem/11727)
- [가장 긴 증가하는 부분 수열](https://www.acmicpc.net/problem/11053)
---
- 풀이과정
- 2x1 두개 == 2x2 이다.
- dp[0] = 0, dp[1] = 1, dp[2] =3 설정
- 이후 dp[i] = dp[i-1] + 2*dp[i-2]
- 풀이과정
-dp[i]에  lst[i] 숫자가 마지막 일때 가장 긴 증가 수열 수를 저장
- lst 내 i 보다 이전 위치에 대해 for문을 돌며 크기를 비교해 max_len을 갱신
---
=> [구너] 2021.06.28

opijae/dynamic_programming_1/11053_가장긴증가하는부분수열.py, opijae/dynamic_programming_1/11727_2xn타일링2.py
- [2xn타일링2](https://www.acmicpc.net/problem/11726)
- [가장긴증가하는부분수열](https://www.acmicpc.net/problem/11053)
---
- [이 문제](https://github.com/boostcamp-ai-tech-4/coding-test-study/pull/131) 랑 똑같다
- 현재 타일은 이전 타일(세로로 했을때) + 전전 타일(가로로 했을때 + 2*2 타일)의 값을 더해준다.
- 매 값 마다 이전 값들이랑 비교해서 수열을 계산한다.
---
=> [후미] 2021.06.28

osmosm7/dynamic_programming_1/11053_가장긴증가하는부분수열.py, osmosm7/dynamic_programming_1/11727_2xn타일링2.py, osmosm7/dynamic_programming_1/1912_연속합.py, osmosm7/dynamic_programming_1/9465_스티커.py
- [연속합](https://www.acmicpc.net/problem/1912)
- [스티커](https://www.acmicpc.net/problem/9465)
---
- 풀이과정
- 이전 값까지 최대 연속합에 현재 위치를 마지막으로 더해줬을때 값을 넣어준다.
- 이전 값까지 최대 연속합이 음수라면 현재값을 더해도 현재값보다 작으므로 현재값을 넣어준다.
- 가장 큰 값 출력
- 풀이과정
- dp도 입력과 같은 사이즈로 생성
-  i번째 값은 i-1번째 대각선 위치와 i-2번째 대각선 위치에서 최댓값을 비교
- 아래와 같이 풀었는데 현재 위치와 i-2번째 같은 위치는 i-1번째의 대각선 위치를 거쳐 현재 위치 값을 더해줄 수 있어서 생략해도 될거 같다. (dp[0][i-2] > dp[1-b][i-1] 여기에 포함됨) 
- dp[b][i] = max(post[b][i]+max(dp[0][i-2],dp[1][i-2]),dp[1-b][i-1]+post[b][i])
---
=> [구너] 2021.06.29

opijae/dynamic_programming_1/1912_연속합.py, opijae/dynamic_programming_1/9465_스티커.py
- [연속합](https://www.acmicpc.net/problem/1912)
- [스티커](https://www.acmicpc.net/problem/9465)
---
- 이전 값 + 현재값 더한게 현재값보다 큰지 고르기
- 현재 위치를 뗀다고 가정하면 이전 값 중 선택 할 수 있는 값들 중 최대 값이랑 더함 
---
```python
for i in range(2):
print('zz')
```
```python
print('zz')
print('zz')    
```
- 위 두 코드 실행 시간 차이가 1200ms vs 900ms 로 차이가 많이 나는데
- for 문이 오버헤드가 커서 그럴까요?
---
=> [후미] 2021.06.29

osmosm7/dynamic_programming_1/11055_가장큰증가부분수열.py, osmosm7/dynamic_programming_1/1890_점프.py, osmosm7/dynamic_programming_1/1912_연속합.py, osmosm7/dynamic_programming_1/9465_스티커.py
- [점프](https://www.acmicpc.net/problem/1890)
- [가장 긴 증가하는 부분 수열](https://www.acmicpc.net/problem/11053)
---
- dfs로하면 시간에러!!!!!!! >>> # 창우님께선 dfs로 푸심... 제 잘못 
- input matrix와 같은 크기 dp 생성 0 으로 채워줌 (0,0은 1로 변경)
-  dp[i][j] !=0이면, matrix[i][j]  값만큼 떨어진 오른쪽, 아래 부분에 dp[i][j] 값을 더해줌
- 풀이과정
- 최초 dp에 input값을 넣어 둠
- 현재 i 번째 숫자에 대해 루프를 돌며 i번째 숫자보다 작으면 dp[i] 갱신 시도 
- max(dp) 출력
---
- 점프 문제를 dfs로 먼저 풀어봤는데 시간 에러가 떴습니다.
- dp문제 에 있긴해서 dp를 떠올리긴했는데... 다른분들은 바로 dp로 풀 생각을 하셨는지 궁금합니다!
---
=> [구너] 2021.06.30

peacecheejecake/README.md, peacecheejecake/dynamic_programming_1/11055_가장큰증가부분수열.py, peacecheejecake/dynamic_programming_1/1890_점프.py
- [가장 큰 증가하는 부분 수열](https://www.acmicpc.net/problem/11055)
- [점프](https://www.acmicpc.net/problem/1890)
---
- `arr[i]`를 포함하는 증가 수열 중 최대합을 `table`에 저장한다.
- `table`의 최댓값을 출력한다.
- 위/왼쪽 칸부터 다음 칸으로 가능한 모든 곳에 자신까지 경우의 수를 더해준다.
- 1행 -> 1열 -> 2행 -> 2열 -> ... 순으로 진행하고 `table`에 저장한다.
=> [튜브] 2021.06.30

opijae/dynamic_programming_1/11055_가장큰증가부분수열.py, opijae/dynamic_programming_1/1890_점프.py
- [가장큰증가부분수열](https://www.acmicpc.net/problem/11055)
- [점프](https://www.acmicpc.net/problem/1890)
---
- 이전 값 중 증가하는 숫자에 한에 최대값 구하고 저장
- 오른쪽, 왼쪽으로 점프가능한지 확인하고 
- 가능하다면 dp 배열에 값 저장
---
=> [후미] 2021.06.30

peacecheejecake/README.md, peacecheejecake/dynamic_programming_1/1106_호텔.py, peacecheejecake/dynamic_programming_1/2407_조합.py
- [2407_조합](https://www.acmicpc.net/problem/2407)
- [1106_호텔](https://www.acmicpc.net/problem/1106)
---
- k!(k=0~n)을 순서대로 저장한다.
- `n! / (m! * (n - m)!)`를 계산해서 출력한다.
- 모집해야 하는 고객이 0~C명일 때, 각각의 최소 금액을 `table`에 저장한다.
- 0명일 때는 0, 1명일 때는 최소 단위 금액과 같다.
- 2명 이상일 때, 각각의 도시를 한 번 선택하는 경우를 각각 고려한다. 이 중 최솟값을 최소 금액으로 한다.
- 모든 경우는 아래 둘 중 하나이다.
- 홍보 한 번으로 충분한 경우 : 해당 도시에서 홍보 한 번에 필요한 금액과 같다.
- 추가 홍보가 필요한 경우 : `table`에서  (필요한 인원 - 홍보 한 번으로 줄어든 인원)에 해당하는 값을 꺼내 더해준다.
- `table[C]`를 출력한다.
=> [튜브] 2021.07.01

osmosm7/dynamic_programming_1/1106_호텔.py, osmosm7/dynamic_programming_1/2407_조합.py
- [호텔](https://www.acmicpc.net/problem/1106)
- [조합](https://www.acmicpc.net/problem/2407)
---
- 풀이과정
- dp를 큰 수로 채우고 dp[0] = 0으로 설정
- 최소 c명이므로 c명 이상일때도 생각해줘야함
- 1100까지 루프를 돌며 dp 갱신 
- dp[j] = min(dp[j-cust] + cost,dp[j])
- dp[c : ]에 대해 가장 작은 수 출력
- 풀이과정
- dp 생성
- dp[i] = dp[i-1] * i 로 채워넣음
- _nCm_ = _dp[n] // dp[m] // dp[n-m]_
- * 위 식에서 // 대신 /를 쓰면 나누는 과정에서 다른 수가 나온다!!!! 
---
- 호텔 문제에서 저는 c가 최대 1000명, 한번에 홍보하는 인원이 최대 100명이라 1100까지 살펴보는게 최적이라 생각했는데 최적의 수가 1100이 맞을지 다른 분들의 풀이를 참고해보겠습니다!
---
=> [구너] 2021.07.01

dkswndms4782/dynamic_programming_1/1106_호텔.cpp, dkswndms4782/dynamic_programming_1/2407_조합.cpp
- [조합](https://www.acmicpc.net/problem/2407)
- [호텔](https://www.acmicpc.net/problem/1106)
---
- 블로그 참고ㅠ
- nCr=(n-1)C(r-1)+(n-1)Cr 사용
- c++은 큰 수를 저장할 수 없어 더해줄 때 string으로 더해줌
- customer배열은 값을 담는 배열
- bottom-up방식으로 customer[i]가 0이 아니면 N만큼 포문으로 다음 customer[i + city[j].first]값을 채움
- 12 2 같은 경우는 최소값이 2. 이런경우를 위해 C부터 C+100까지 최소값을 고른 후 출력
1 11
3 5
---
=> [감자]2021.07.01

opijae/dynamic_programming_1/1106_호텔.py, opijae/dynamic_programming_1/2407_조합.py
- [조합](https://www.acmicpc.net/problem/2407)
- [호텔](https://www.acmicpc.net/problem/1106)
---
- dp로 어캐 푸는지 모르겠습니다,..ㅠㅠ 
- 여러 분 풀이 보고 알겠네요
- for문을 돌려 n 부터 n-m까지 곱하고 1 부터 m까지 나눕니다.
- dp를 최소 비용당 받을 수 있는 최대 손님 으로 설정한다.
- dp[i]가 목표 손님수를 넘으면 break 한다.
---
=> [후미] 2021.07.01

.mergify.yml
This change has been made by @CoodingPenguin from https://mergify.io config editor.
=> [Mergify] Add closed and merged condition

peacecheejecake/README.md, peacecheejecake/dynamic_programming_1/15486_퇴사2.py, peacecheejecake/dynamic_programming_1/2156_포도주시식.py
- [퇴사 2](https://www.acmicpc.net/problem/15486)
- [포도주 시식](https://www.acmicpc.net/problem/2156)
---
- (T, P) 튜플을 `info`에 담고, 뒤에서부터 순회한다.
- i번째 날 상담을 할 때, 다음의 세 개의 경우로 최대 금액을 구할 수 있다.
1. 상담을 마치는 날이 N-1일 이전일 때 : P + `마감하는 날까지 받는 최대 금액`
2. 상담을 마치는 날이 마지막 날일 때 : P
3. N일 이전에 상담을 못 마칠 때 : 상담 불가
- i<N이라면, i번째 날에 상담하지 않을 때 최대 금액이 될 수도 있다. 따라서 i번째 날에 상담을 할 때와 상담을 하지 않을 때 각각의 최댓값 중 더 큰 것을 i번째 최댓값으로 한다.
- 이전 포도주를 마셨을 때와 마시지 않았을 때로 나누어 `table`에 저장한다.
- 이전 포도주를 마셨을 때 : 이이전 포도주를 마시지 않는 하나의 경우만 존재한다.
- 이전 포도주를 마시지 않을 때 : 이이전 포도주를 마실 때의 두 경우와, 이이이전 포도주를 마시고 이이전 포도주는 안마시는 경우가 가능하다. 총 3가지 경우 중 최댓값을 택한다.
- 3번째부터 n번째까지 차례대로 `table`을 채우고, 마지막 두 개의 포도주를 포함하는 경우 중 최댓값을 출력한다.
- n=1일 때는 첫 번째 입력을 바로 출력하도록 예외처리를 한다.
=> [튜브] 2021.07.02

osmosm7/dynamic_programming_1/15486_퇴사2.py, osmosm7/dynamic_programming_1/2156_포도주시식.py
- [포도주 시식](https://www.acmicpc.net/problem/2156)
- [퇴사2](https://www.acmicpc.net/problem/15486)
---
- 풀이과정
- 계단오르기랑 비슷해서 오히려 틀렸다
- 1칸, 2칸 뛰어넘는것 보다 더 많이 뛰어 넘는 걸 고려해야함
- dp[i] = max(max(dp[:i-1]) ,max(dp[:i-2])+ lst[i-1])+ lst[i]
- 풀이과정
- 처음에 dfs로 풀다가 재귀 에러, 메모리에러....
- 이후, 시간초과 때문에 엄청 헤맸다....
- dp[i+1] = max(dp[i],dp[i+1]) 이렇게 추가한게 키
* 참고 : https://won-percent.tistory.com/10
---
---
=> [구너] 2021.07.02

dkswndms4782/dynamic_programming_1/15486_퇴사2.cpp, dkswndms4782/dynamic_programming_1/2156_포도주시식.cpp
- [15486_퇴사2](https://www.acmicpc.net/problem/15486)
- [2156_포도주시식](https://www.acmicpc.net/problem/2156)
---
- 선택지는 현재 상담을 할것인지 말것인지, 2개
- 상담 한다 -> dp[i + T[i]] = max(dp[i] + P[i], dp[i + T[i]]);
- 상담 안한다(다음 날로 넘어감) -> max(dp[i+1], dp[i]);
- 0번 연속해서 마신 포도주 : 현재 포도주 마시지 않음(dp[i-1])
- 1번 연속해서 마신 포도주 : 이전 포도주 마시지 않음(dp[i-2] + 현재 음료)
- 2번 연속해서 마신 포도주 :  i-2번째 포도주는 마시지 말았어야함. (dp[i-3] + 현재음료 + 전음료)
---
=> [감자] 2021.07.02

osmosm7/dynamic_programming_1/108444_쉬운계단수.py, osmosm7/dynamic_programming_1/2293_동전1.py
- [쉬운 계단 수](https://www.acmicpc.net/problem/10844)
- [동전1](https://www.acmicpc.net/problem/2293)
---
- 풀이과정
- 사실상 어려운 계단 수
- 2중 dp 는 떠올리기 항상 어려운거 같음
- 1~9의 숫자가 이전 계단수에 어떻게 영향 받는지 생각해야함
- 0으로 시작할 수 없음을 체크해 0,9와 다른 수의 경우를 다르게 생각
- 0,9는 각각 이전 1,8에만 영향을 받고 다르 수는 i-1,i+1의 영향을 받음
- 위 아이디어로 dp를 생성하고 마지막 위치의 합을 더해줘 출력
(코드에서는 확인을 위해 다 더했지만 마지막 위치만 더해주면 됨)
- 풀이과정
- 동전의 가치를 c 라 할때, 값 i에 대해 i를 나타내는 가지수는
- dp[i] = dp[i-c] + dp[i] 로 갱신할 수 있음
- dp[0] 을 1로 설정해두면 dp[c] = dp[c-c] + dp[c]를 추가작업 없이 풀이 가능
---
- 과연 실전에서 2중 dp를 만들 수 있을까?ㅋㅋ
---
=> [구너] 2021.07.05

peacecheejecake/README.md, peacecheejecake/dynamic_programming_1/10844_쉬운계단수.py, peacecheejecake/dynamic_programming_1/2293_동전1.py
- [쉬운 계단 수](https://www.acmicpc.net/problem/10844)
- [동전 1](https://www.acmicpc.net/problem/2293)
---
- `table`에 길이가 i일 때, 마지막 자릿수에 따른 경우의 수를 저장한다.
- 첫 번째 수는 0이 될 수 없으므로, `table[0]`은 `[0, 1, 1, 1, 1, 1, 1, 1, 1, 1]`이다.
- 0은 1로부터, 9는 8로부터, 나머지 수는 위아래 두개의 수를 더한 것으로부터 구한다.
- 마지막 원소의 합을 `1e9`로 나눈 나머지를 출력한다.
- `table`는 길이가 k + 1이고, `table[i]`는 구하는 수가 i일 때를 나타낸다.
- 각각의 동전(`coin`)에 대하여, 그 동전을 포함하여 만들 수 있는 경우의 수를 각각 더해준다(`coin`부터 k까지).
- 모든 동전은 서로 다르고, 각각의 동전은 한 번씩만 고려되며, 현재 동전을 포함하는 경우라도 아직 차례가 오지 않은 동전을 포함하는 경우라면 0이 더해진다. 따라서 중복되는 경우는 없다.
- `table[k]`를 출력한다.
---
저는 동전 1에서 `모든 경우가 중복되지 않는 것`을 증명하는 데 너무(x100) 오래걸렸습니다. 이번뿐만 아니라 비슷한 문제에서 헤매는 경향이 있네요 ㅠㅠ 혹시 규칙 찾는 데 정해진 방법이 있을까요?
=> [튜브] 2021.07.05

osmosm7/dynamic_programming_1/108444_쉬운계단수.py, osmosm7/dynamic_programming_1/11660_구간합구하기5.py, osmosm7/dynamic_programming_1/2293_동전1.py, osmosm7/dynamic_programming_1/2294_동전2.py
- [동전2](https://www.acmicpc.net/problem/2294)
- [구간 합 구하기 5](https://www.acmicpc.net/problem/11660)
---
- 풀이과정
- 동전 c 마다 현재 값 i 에 대해
- dp[i] = min(dp[i], dp[i-c] +1) 로 갱신
- 풀이과정
- 역시나 2중 포문으로 되지 않을까 했다가 빠르게 포기
- (1,1) ~ (n,n) 구간안에 x,y 까지 합을 보여주는 dp 생성
- dp[x][y] = dp[x-1]+dp[y-1] -dp[x-1][y-1]
- x1, y1, x2, y2 구간합은 dp[x2][y2] - dp[x1-1][y2] - dp[x2][y1-1] + dp[x1-1][y1-1]
- x1, y1 값에 따라 조건 추가!
=> [구너] 2021.07.06

dkswndms4782/dynamic_programming_1/11660_구간합구하기5.cpp, dkswndms4782/dynamic_programming_1/2294_동전2.cpp
- [동전2](https://www.acmicpc.net/problem/2294)
- [구간 합 구하기 5](https://www.acmicpc.net/problem/11660)
---
- vector를 이용해 unique한 값 구하기
- 동전 1과 유사하지만 코인의 수이므로, dp[j-v[i]]+1, dp[j]중 작은 값 선택
- 처음에 dp배열 초기화 101로 했다가 엄청 틀렸다ㅠ 10001로 초기화 해줌
- 처음 배열을 받을 때, table[i][j]값을 넣어줌. 그 후 바로 table[i][j] += table[i][j-1]을 해주었다
ex) 1 2 3 4 => 1 3 6 10
- result는 table[i][y2] - table[i][y1-1]을 해서 각 행에서 필요한 숫자만큼 더한 값을 뽑아 더해줌
---
=> [감자] 2021.07.06

sally/README.md, sally/dynamic_programming_1/11660_구간 합 구하기 5.cpp, sally/dynamic_programming_1/2294_동전 2.cpp
- [2294_동전 2](https://www.acmicpc.net/problem/2294)
- [11660_구간 합 구하기 5](https://www.acmicpc.net/problem/11660)
---
- INF로 배열을 초기화
- 하나의 동전으로 만들 수 있는 값을 인덱스로 삼고, 배열의 해당 위치에 1을 넣어줌
- 앞에서부터 배열을 갱신
- `현재 보고있는 인덱스 값 + 동전의 값어치`를 인덱스로 삼는 위치의 value와 `현재 보고 있는 인덱스 값 + 1`을 비교해서 더 작은 값을 `현재 보고있는 인덱스 값 + 동전의 값어치`를 인덱스로 삼는 위치의 value에 저장
- index가 값, value가 최소 사용 동전의 수를 나타냄
- 이차원 배열을 입력받음
- 1번 열 부터 자신 까지의 값을 더함 (`가로 더하기`)
- 1행부터 계산하기 - 자신과 자신의 위의 값을 더함 (`가로 더하기` 한 것에 `세로 더하기` 추가)
- (x1, y1) (x2, y2) 사이의 값 더하기
- `큰 사각형` - `작은 사각형` + `공통으로 빠진 부분`
- `dp[x2][y2]` - (`dp[x1-1][y2] + dp[x2][y1-1]`) + `dp[x1-1][y1-1]`
---
=> [샐리] 2021.07.06

opijae/dynamic_programming_1/10844_쉬운계단수.py, opijae/dynamic_programming_1/11660_구간합.py, opijae/dynamic_programming_1/2293_동전1.py, opijae/dynamic_programming_1/2294_동전2.py
- [쉬운계단수](https://www.acmicpc.net/problem/10844)
- [동전1](https://www.acmicpc.net/problem/2293)
---
- 2~8은 `n-1, n+1` 두가지 경우 고려가 가능하지만
- 1,9는 한가지 경우가 되니 따로 빼서 계산한다.
- 동전의 값 간격마다 더해줘 계산한ㄷ.
---
=> [후미] 2021.07.05

opijae/dynamic_programming_1/10844_쉬운계단수.py, opijae/dynamic_programming_1/11660_구간합.py, opijae/dynamic_programming_1/2293_동전1.py, opijae/dynamic_programming_1/2294_동전2.py
- [동전2](https://www.acmicpc.net/problem/2294)
- [구간합](https://www.acmicpc.net/problem/11660)
---
- 모든 동전에 대해 계산을 해주고 
- 동전의 값마다 간격을 세워 계산을 한다.
- 아래 그림에서 보라색 네모를 친 부분이 원하는 값이다.
- 빨간색은 `x2,y2` , 파란색은 `x1,y1` 부분이다.
- 보라색을 구하기 위해서는 빨강 - 연두 + 연두 겹친부분이다.
---
=> [후미] 2021.07.06

peacecheejecake/README.md, peacecheejecake/dynamic_programming_1/11660_구간합구하기5.py, peacecheejecake/dynamic_programming_1/2294_동전2.py
- [동전 2](https://www.acmicpc.net/problem/2294)
- [구간 합 구하기 5](https://www.acmicpc.net/problem/11660)
---
- 동전에 중복이 있을 수 있으므로, 중복되지 않는 동전만 리스트에 담아준다.
- 구해야 하는 값이 1부터 k일 때까지 필요한 동전 수 최솟값을 `table`에 저장한다.
- `table`은 `INF`로 초기화한다.
- 각 동전을 한 번 포함하는 경우를 모두 계산하며, 그 값이 이미 있는 값보다 작은 경우 갱신한다.
- 동전 시리즈 있으면 몇 개 더 풀어봐야겠다.
- `table`에 숫자를 저장한다.
- `table[x][y]`을 [1, 1]부터 [x, y]까지 구간합으로 갱신한다.
- `table[x2][y2]`에서 구하는 영역에 포함되지 않는 것을 빼 주는 방법으로 계산한다.
- x1 > 0이고 y1 > 0인 경우, 두 번 빠지는 `table[x1 - 1][y1 - 1]`을 다시 더해준다.
- 문제를 잘 읽자. (`x행 y열`인데 `x열 y행`으로 해서 한참 헤맸다.)
=> [튜브] 2021.07.06.

dkswndms4782/dynamic_programming_1/11660_구간합구하기5.cpp, dkswndms4782/dynamic_programming_1/21317_징검다리건너기.cpp, dkswndms4782/dynamic_programming_1/2294_동전2.cpp
- [징검다리건너기](https://www.acmicpc.net/problem/21317)
---
- 짱큰점프를 한 경우랑 하지않은 경우를 구분해주기 위해 dp[21][2]로 배열 선언 후, 두번째 idx가 0인경우(짱큰점프 하지 않은 경우)와 idx가 1인경우(짱큰점프 한 경우)로 나눠주었다.
- dp의 첫번째 idx는 현재 징검다리 돌의 번호를 나타낸다. 
- dp[i][0]에서 k를 더해준 값은 dp[i+3][1]에 할당
- [dp[i + 1][0] = dp[i][0] + jump[i][0]] 이렇게 칸을 이동한 만큼의 에너지를 더한 후 할당
---
=> [감자] 2021.07.07

sally/README.md, sally/dynamic_programming_1/21317_징검다리 건너기.cpp
- [21317_징검다리 건너기](https://www.acmicpc.net/problem/21317)
---
- dp 배열을 2차원으로 만든다.
- 0행에는 슈퍼점프를 쓰지 않은 경우
- 1행에는 슈퍼점프를 쓴 경우를 기록할 것임
- `dp[0][0] = 0`을 제외한 모든 값을 INF로 초기화
- 슈퍼점프를 쓰지 않은 경우
- 자신보다 1전의 값을 참고
- 자신보다 2전의 값을 참고(dp 배열의 0번째 행 사용)
- 슈퍼점프를 쓴 경우
- 자신보다 3전의 0번째 행의 값을 참고(슈퍼점프를 안쓴 지점에서 슈퍼점프 에너지를 더함(?))
- 자신보다 2전의 1번째 행의 값을 참고(슈퍼점프를 이미 쓴 경우에서 1 돌다리 움직임)
- 자신보다 1전의 1번째 행의 값을 참고(슈퍼점프를 이미 쓴 경우에서 2 돌다리 움직임)
---
=> [샐리] 2021.07.07

osmosm7/dynamic_programming_1/21317_징검다리건너기.py
- [징검다리건너기](https://www.acmicpc.net/problem/21317)
---
- 우선적으로 1,2 점프만 이용해 dp[0]를 생성했습니다.
- 슈퍼점프(3)가 가능한 위치 (0\~n-3) 별로 시행해줬습니다. (dp[1\~n-2])
- 이때 슈퍼점프 이전은 dp[0]을 가져오고, 슈퍼점프 이후는 1,2 점프로 갱신했습니다.
- 결과적으로 제출시 틀렸다고 나오는데 이유가 뭘까 궁금합니다.......
---
=> [구너] 2021.07.07

opijae/dynamic_programming_1/21317_징검다리건너기.py, opijae/shortest_path/11403_경로찾기.py, opijae/shortest_path/18352_특정거리의도시찾기.py
- [징검다리건너기](https://www.acmicpc.net/problem/21317)
---
- dp를 이차원 배열로 만들어 0번째는 슈퍼 점프를 사용하지않았을때
- 1번째는 슈퍼점프를 사용했을때다.
---
=> [후미] 2021.07.07

dkswndms4782/shortest_path/11403_경로찾기.cpp, dkswndms4782/shortest_path/18352_특정거리의도시찾기.cpp
- [특정 거리의 도시 찾기](https://www.acmicpc.net/problem/18352)
- [경로 찾기](https://www.acmicpc.net/problem/11403)
---
- queue에 city번호과 거리를 넣어준다
- queue에서 뽑은 city에서 갈 수 있는 city중 방문하지 않은 곳은 queue에 넣어준다.(거리 + 1)
- sort한 후 정렬
- dfs로 풀었다
- 각 노드마다 갈 수 있는 곳을 dfs로 체크한 후 result[original][next]를 1로 만들어주었다. 
- 각 노드가 dfs를 돌때마다 bool check배열을 매번 초기화 해주었다. 
---
=> [감자] 2021.07.09

osmosm7/dynamic_programming_1/21317_징검다리건너기.py, osmosm7/shortest_path/11403_경로 찾기.py, osmosm7/shortest_path/18352_특정거리의도시 찾기.py
- [경로 찾기](https://www.acmicpc.net/problem/11403)
- [특정 거리 찾기](https://www.acmicpc.net/problem/18352)
---
- 플로이드 워샬로 갈 수 있는 도시 모두 1로 변경
- 인접 리스트 생성
- BFS로 k step까지 거리 측정
- k step에 도시가 있으면 출력, 없으면 -1 출력
---
=> [구너] 2021.07.09

sally/README.md, sally/shortest_path/11403_경로 찾기.cpp, sally/shortest_path/18352_특정 거리의 도시 찾기.cpp
- [18352_특정 거리의 도시 찾기](https://www.acmicpc.net/problem/18352)
- [11403_경로 찾기](https://www.acmicpc.net/problem/11403)
---
- BFS를 사용해서 K번째 depth에 있는 노드를 정렬하여 출력
- 플로이드 알고리즘을 활용
- 간선이 다른 간선을 이용해서 연결해줄 수 있다면 true로 업데이트하여 반환하기만 하면 된다.
---
=> [샐리] 2021.07.09

coodingpenguin/README.md, coodingpenguin/shortest_path/11403_경로찾기.py, coodingpenguin/shortest_path/18352_특정거리의도시찾기.py
- [특정거리의 도시찾기](https://www.acmicpc.net/problem/18352)
- [경로 찾기](https://www.acmicpc.net/problem/11403)
---
- 처음에 다잌스트라 알고리즘으로 풀었으나, 간선에 비용이 없으니 그래프 탐색으로도 풀 수 있다는 것을 알게 되었다.
- 너비우선탐색으로 탐색하면서, 해당 노드의 distance 테이블이 갱신되지 않았다면 갱신해주면 된다.
- distance 테이블에서 값이 k인 노드의 번호만 추출하여 만약 아무것도 없다면 -1을 있다면 노드들을 다 출력한다.
- 입력이 인접행렬로 주어졌다. 그래서 최대한 인접행렬 그대로 사용하려 했다.
- k, i, j를 n까지 삼중 루프문을 돌면서, `i~k`, `k~j`에서의 간선이 존재한다면, `i~j`의 값을 1로 갱신해준다.
- 삼중이라서 시간복잡도가 크지만, n이 1000으로 작기 때문에, n^3 = 10^9으로 약간 아슬아슬하지만 백준 내에서는 통과했다.
- 앞의 문제와 동일하게 비용이 없기 때문에, 단순 그래프탐색으로 풀 수 있으며, 이렇게 푸는 경우 내 경우보다 시간이 덜 걸린다.
---
=> [펭귄] 2021.07.09

changwoomon/README.md, changwoomon/dynamic_programming_1/21317_징검다리건너기.py, changwoomon/shortest_path/11403_경로찾기.py, changwoomon/shortest_path/18352_특정거리의도시찾기.py
- [특정 거리의 도시 찾기](https://www.acmicpc.net/problem/18352)
- [경로 찾기](https://www.acmicpc.net/problem/11403)
---
- 그래프를 받아와서 BFS를 돈다.
- queue에 넣어줄 때 `(도시 번호, 거리)`로 넣어준다.
- 거리가 K라면 answer에 append 하고, K보다 작다면 거리+1 해주면서 queue에 append 한다.
- answer의 길이가 1보다 클 때 answer를 정렬하여 출력하고, 아니라면 -1을 출력한다.
- for i in range(N)
- visited를 시작할 때마다 초기화한다.
- 정점 i로부터 DFS를 돈다.
- visited를 출력한다.
---
=> [원딜] 2021.07.09

opijae/shortest_path/11403_경로찾기.py, opijae/shortest_path/18352_특정거리의도시찾기.py
- [특정거리의도시찾기](https://www.acmicpc.net/problem/18352)
- [경로찾기](https://www.acmicpc.net/problem/11403)
---
- 큐는 (시작 노드, 남은 거리) 가 저장된다.
- bfs로 푼다
- 오름차순으로 도시 출력해야되는데 sort 하기 싫어서 heap으로 접근 하려했다...
- 간선이 존재하는 경우 생각해 bfs로 푼다.
---
=> [후미] 2021.07.09

changwoomon/README.md, changwoomon/shortest_path/11265_끝나지않는파티.py, changwoomon/shortest_path/2224_명제증명.py
- [명제 증명](https://www.acmicpc.net/problem/2224)
- [끝나지 않는 파티](https://www.acmicpc.net/problem/11265)
---
> `시간복잡도`: O(V(V+E)) ......??
- 명제 `P => Q` 를 입력받아 ` => `으로 split 한 후 P를 key로, Q를 value로 하는 dict를 만든다.
- dict의 key들을 for 문을 돌면서 BFS로 각 key에서 갈 수 있는 Q를 찾아 출력한다.
> `시간복잡도`: O(N^3) ..?
- 입력받은 graph를 플로이드-워셜 알고리즘으로 최단 거리를 구해준다.
- A, B, C를 입력받아 graph[A-1][B-1] 값이 C보다 작거나 같다면 `"Enjoy other party"` 크다면 `"Stay here"`를 출력한다.
---
=> [원딜] 2021.07.12

dkswndms4782/shortest_path/11265_끝나지않는파티.cpp, dkswndms4782/shortest_path/2224_명제증명.cpp
- [명제 증명](https://www.acmicpc.net/problem/2224)
- [끝나지 않는 파티](https://www.acmicpc.net/problem/11265)
---
> `시간복잡도`:  O(N + E) + O(NlogN) -> O(NlogN)
-> DFS를 사용하여 풀었기때문에  O(N + E)(N : 알파벳의 개수 , E : 정점에 연결된 간선의 개수)
-> sort를 해줬기때문에 O(NlogN)
- 각 알파벳마다 dfs를 통해 명제가 성립 될 수 있는경우를 다 찾아줌
- 후 sort하고 출력
> `시간복잡도`: O(V^3)
-> 플로이드 와샬 알고리즘을 사용했기때문에 O(V^3)
- 모든 정점간의 최단거리를 구했어야하므로 플로이드 와샬 알고리즘 사용
- for문 3개를 사용하여 dp기반 알고리즘을 통해 배열을 최단거리로 채워넣음
- 후 입력받은 C와 비교하여 time이 더 작으면 "enjoy~~"출력
---
=> [감자] 2021.07.12

opijae/shortest_path/11625_끝나지않는파티.py, opijae/shortest_path/2224_명제증명.py
- [명제증명](https://www.acmicpc.net/problem/2224)
- [끝나지않는파티](https://www.acmicpc.net/problem/11625)
---
> `시간복잡도`:  O(n^3) (n은 고유한 알파벳 수)
- 인접 행렬로 만들어 주고 플로이드 마셜 방법을 사용한다.
- 인접행렬을 만들 때 A - z순서로 index에 넣어줘야된다. 
- 넣어줄때 index dictionary를 만들어 사용한다.
> `시간복잡도`: O(n^3) (n은 파티장의 크기)
- 플로이드 마셜 문제이다.
- 모든 경우를 고려한다.
- 전역으로 풀면 시간초과나서 함수로 바꿔 풀었더니 통과 되었다. 
-  파이썬은 로컬 -> 전역 -> bulit in 변수 순으로 찾는다 해서 로컬로 문제를 풀면 메모리에 더 빨리 접근할 수 있어 빨리 풀 수 있는거 같다. 
- 참고 링크 : https://stackoverflow.com/questions/12590058/performance-with-global-variables-vs-local
---
=> [후미] 2021.07.12

sally/README.md, sally/shortest_path/11265_끝나지 않는 파티.cpp, sally/shortest_path/2224_명제 증명.cpp
- [2224_명제 증명](https://www.acmicpc.net/problem/2224)
- [11265_끝나지 않는 파티](https://www.acmicpc.net/problem/11265)
---
> `시간복잡도`: O(V^3)
- 플로이드 와셜 알고리즘을 사용하여 갈 수 있는 모든 경로를 파악
- 모든 경우 중, 갈 수 있는 경우들만 출력
> `시간복잡도`: O(V^3)
- 플로이드 와셜 알고리즘을 사용하여 갈 수 있는 모든 경로를 파악
- 원하는 지점에, 지정한 시간 이내에 도달할 수 있는지 출력
---
=> [샐리] 2021.07.12

osmosm7/shortest_path/11265_끝나지않는파티.py, osmosm7/shortest_path/2224_명제증명.py
- [명제 증명](https://www.acmicpc.net/problem/2224)
- [끝나지 않는 파티](https://www.acmicpc.net/problem/11265)
---
> `시간복잡도`: 
플로이드 와샬을 썼으니 N^3이 아닐까요??
- chr과 ord를 새로 배웠다.
- ord를 이용해 입력 알파벳을 인코딩
- 플로이드 와샬로 명제 증명 가능한지 갱신
- 증명 가능하면 chr을 이용해 디코딩 후 출력
> `시간복잡도`: 
플로이드 와샬을 썼으니 N^3이 아닐까요??
- 풀이과정
- 플로이드 와샬로 최단 시간 갱신
- 최단시간 안에 도착할 수 없으면 stay here 있으면 Enjoy other party 출력
---
=> [구너] 2021.07.12

osmosm7/shortest_path/13549_숨바꼭질3.py, osmosm7/shortest_path/1753_최단경로.py
- [숨바꼭질 3](https://www.acmicpc.net/problem/13549)
- [최단 경로](https://www.acmicpc.net/problem/1753)
---
> `시간복잡도`:  다익스트라의 시간복잡도는 O(|E||log|V|) 라 하는데 확인 필요!
- dp로 풀었습니다!
- -1로 구성된 리스트를 만들어 visit과 갱신 동시에 수행
- x2, +1, -1 각각 범위 내에 있고 리스트 원소가 -1이면 갱신
- 도착지가 갱신되었으면 출력!
> `시간복잡도`: 잘 모르겠습니다... for 문이 없고 매스텝 한번씩 갱신되니 최대 O( l end - start l )..??
- 다익스트라로 거리 갱신
- 갈 수 있으면 최단 거리 출력 없으면 INF 출력
---
=> [구너] 2021.07.13

changwoomon/README.md, changwoomon/shortest_path/13549_숨바꼭질3.py, changwoomon/shortest_path/1753_최단경로.py
- [최단경로](https://www.acmicpc.net/problem/1753)
- [숨바꼭질 3](https://www.acmicpc.net/problem/13549)
---
> `시간복잡도`: O(E⋅logV)
- 다익스트라 알고리즘을 사용해서 시작 정점(K)부터 각 정점까지의 최단 거리를 구한다.
- 최단 거리를 구할 수 없으면(시작 정점부터 갈 수 없는 정점이면) `INF` 출력
> `시간복잡도`: O(E⋅logV)
- 다익스트라 알고리즘을 사용해서 수빈이의 위치부터 각 번호 위치까지 가는데에 걸리는 최소 시간을 구한다.
---
=> [원딜] 2021.07.13

.mergify.yml
- conflict 발생 시 `conflict` 라벨을 다는 것과 해결 시 제거하는 Action 추가
=> [Mergify] Automate adding and removing conflict label 

changwoomon/README.md, changwoomon/implementation/14467_소가길을건너간이유1.py, changwoomon/implementation/1913_달팽이.py
- [달팽이](https://www.acmicpc.net/problem/1913)
- [소가 길을 건너간 이유 1](https://www.acmicpc.net/problem/14467)
---
- [0][0]부터 아래 방향으로 좌표에 대한 조건을 만족하면 계속 직진하면서, 조건을 만족하지 못하면 좌표를 좌회전 시키면서 값을 채워나간다.
- 입력받은 소의 번호가 `cows.keys()`에 존재하지 않는다면 `cows[소의 번호] = 위치`
- 입력받은 소의 번호가 `cows.keys()`에 존재할 때 `cows[소의 번호]`에 저장되어 있는 위치와 입력받은 위치가 다르다면 cnt를 +1
- cnt를 출력
---
=> [원딜] 2021.07.14

sally/README.md, sally/implementation/14467_소가 길을 건너간 이유 1.cpp, sally/implementation/1913_달팽이.cpp
- [1913_달팽이](https://www.acmicpc.net/problem/1913)
- [14467_소가 길을 건너간 이유 1](https://www.acmicpc.net/problem/14467)
---
> - N: 입력(한 행의 크기)
- 방향 정보를 담는 배열을 만든다.
- 순서는 `하 → 우 → 상 → 좌`
- 범위를 벗어날 때와 이미 방문한 곳을 다시 방문하여고 할 때, 방향 정보를 업데이트한다.
- 1이 배열에 쓰여지면 탈출/종료한다.
> - N: 입력(소의 이동 경우의 수)
- `-1`로 배열을 초기화
- 반복문을 돌면서, -1 이 쓰여진 자리에는 입력값으로 초기화를 시켜준다. → 바로 continue 시켜줘서 아래의 조건과 만나지 않게 한다.
- 현재 입력과 다른 값이 쓰여있다면 출력값을 1 더해준다.
---
=> [샐리] 2021.07.14

osmosm7/implementation/14467_소가길을건너간이유1.py, osmosm7/implementation/1913_달팽이.py
- [달팽이](https://www.acmicpc.net/problem/1913)
- [소가 길을 건너간 이유 1](https://www.acmicpc.net/problem/14467)
---
> `시간복잡도`: n^2
- 0,0 부터 시작해 범위에 포함 안되거나 이미 채워진 곳을 만나면 방향 바꾸며 채워넣음
> `시간복잡도`:  글쎄요... 각 소의 숫자 길이 + 소 별로 확인된 수 > 최대 n^2 ??
- 관측된 소별로 list를 만들고, 길을 건넌 숫자를 체크
---
- 실력이 상승한건지 실버라 그런지 EASY 하군요 ㅎㅎ 
---
=> [구너] 2021.07.14

opijae/implementation/14467_소가길을건너간이유1.py, opijae/implementation/1913_달팽이.py
- [달팽이](https://www.acmicpc.net/problem/1913)
- [소가길을건넌이유](https://www.acmicpc.net/problem/14467)
---
> `시간복잡도`: (n/2-1) * m (n= 입력값, m= n~ n-1....2, 1)
-  아래 그림 대로 숫자가 1씩 줄어드는 성질을 이용해 품
> `시간복잡도`:  n
- 소의 이전 위치를 저장 했다 새로운 값이 들어오면 비교
---
=> [후미] 2021.07.14

changwoomon/README.md, changwoomon/implementation/12933_오리.py, changwoomon/implementation/14467_소가길을건너간이유1.py, changwoomon/implementation/1913_달팽이.py, changwoomon/implementation/2578_빙고.py
- [오리](https://www.acmicpc.net/problem/12933)
- [빙고](https://www.acmicpc.net/problem/2578)
---
> `시간복잡도`: O(입력문자수*정답오리수)
- defaultdict를 이용해서 입력되는 문자를 한 글자씩 넣어줄 수 있는 key에 넣어준다.
- 넣어줄 수 있는 key가 없다면 -1 리턴
> `시간복잡도`: O(25\*5\*5)
- 생각하기 귀찮아서 시작할 때 빙고가 되는 경우의 수를 전부 구해줬습니다.
- 진행자가 불러주는 숫자를 for 문을 돌면서 철수의 빙고판에서 그 숫자의 좌표를 set에 add
- `빙고 경우의 수 좌표 ∩ 철수의 숫자 좌표 == 빙고 경우의 수 좌표`라면 빙고이므로 cnt+1
- cnt가 3이면 몇 번째 숫자인지 리턴
---
=> [원딜] 2021.07.15

sally/README.md, sally/implementation/12933_오리.cpp, sally/implementation/2578_빙고.cpp
- [12933_오리](https://www.acmicpc.net/problem/12933)
- [2578_빙고](https://www.acmicpc.net/problem/2578)
---
> - N : 문자열의 길이
- 문자열을 앞에서부터 보되, 내부 반복문에서 찾을 수 있는 겹치지 않는 "quack" 들을 찾아서 visit true로 변경
- 외부 반복문에서는, 가지않았던 곳 중에 'q' 문자열을 발견하면, 
- 그때 내부 반복문을 실행하는 구조 + 내부 반복문을 실행하기 시작할 때, 오리의 수를 증가시킴
- 만약 visit false인 문자열이 있으면 -1, 아니라면 지금까지 세어온 오리의 수를 출력
> - N: 초기 배열의 크기(배열 초기화를 위한 입력의 수)
- 자리에 따른 입력과 입력에 따른 자리를 각각 저장
- → 접근속도를 O(1)로 만들 수 있음
- checker 함수를 통해 3빙고가 만들어졌는지 확인
---
=> [샐리] 2021.07.15

peacecheejecake/README.md, peacecheejecake/implementation/1244_스위치켜고끄기.py, peacecheejecake/implementation/4396_지뢰찾기.py
- [지뢰 찾기](https://www.acmicpc.net/problem/4396)
- [스위치 켜고 끄기](https://www.acmicpc.net/problem/1244)
---
> `시간복잡도`: O(n^2) 
- 모든 칸을 돌며, 클릭한 경우(`x`)에만 적절한 값을 구한다.
- 클릭한 칸이 지뢰(`*`)인 경우, `lost=True`로 해서 모든 지뢰를 출력할 수 있도록 한다. 이 때를 위해 입력을 받을 때 지뢰의 위치도 별도의 리스트(`mines`)에 담아 둔다.
- 문제의 설명이 애매한 부분이 있다. 지뢰를 밟는 경우 다른 칸은 전부다 `.`으로 출력하라고 이해할 수도 있을 것 같다. (이번에도 그렇고 생각해보니 저번에도 가장 먼저 이렇게 풀어서 틀렸다.)
> `시간복잡도`: O(sn) - s는 학생 수, n은 스위치 개수
- 학생별로 입력을 받아 `switch`함수에 인자로 넘겨준다.
- 남학생인 경우, 받은 숫자의 배수 번째 수의 스위치 상태를 바로 바꾼다.
- 여학생인 경우, 받은 숫자부터 한 칸씩 대칭으로 진행한다. 대칭 위치의 두 숫자가 같은 경우 스위치 상태를 변경하고, 그렇지 않으면 종료한다.
- 20개씩 시작 인덱스를 건너뛰며 출력한다.
---
어느덧 자연스럽게 1위 탈환.. 다시 열심히 풀겠습니다 ㅎ
=> [튜브] 2021.07.16

dkswndms4782/implementation/10994_별찍기19.cpp, dkswndms4782/implementation/20291_파일정리.cpp
- [별찍기19](https://www.acmicpc.net/problem/10994)
- [파일정리](https://www.acmicpc.net/problem/20291)
---
> `시간복잡도`: C++은 string의 곱하기 연산이 안돼서 for문으로 더해줬다. 또 idx/2만큼 배열에 값 넣어줘서 O(N^2)..?
- 홀수줄이면 양옆에 "* "" *"를 넣은 후 가운데 채우기
- 짝수줄이면 양옆에 "* "" *"를 넣은 후 가운데 비우기
> `시간복잡도`: N만큼 입력받고 sort해서 출력하기때문에 O(NlogN)
- map을 이용해 고유 key값에 1 더해줌.
- 값이 1일때 벡터에 넣어줘서 중복으로 벡터에 들어가는거 방지
- sort한 후에 map value값 같이 출력
=> [감자] 2021.07.19

peacecheejecake/README.md, peacecheejecake/implementation/10994_별찍기.py, peacecheejecake/implementation/2029_파일정리.py
- [별 찍기 - 19](https://www.acmicpc.net/problem/10994)
- [파일 정리](https://www.acmicpc.net/problem/2029)
---
- 주어진 모양은 정사각형이고, 상하좌우대각선 모두 대칭이다. 가장 바깥쪽 한 변의 길이를 `l = 4 * (n - 1) + 1`로 하자.
- `l x l` 크기의 리스트를 빈칸으로 채운다.
- 행과 열의 가운데 인덱스를 m(=l // 2)이라 하자.
- 행 번호가 짝수일 때, `|m - col| <= |m - row|`를 만족하면 리스트의 (i, j)는 `*`이 된다.
- 열 번호가 짝수일 때, `|m - row| <= |m - col|`를 만족하면 리스트의 (i, j)는 `*`이 된다.
- 각 열의 연산이 끝날 때마다 한 줄씩 바로 출력한다.
> `시간복잡도`: O(LN)
>   - L: 파일 이름의 최대 길이
>   - N: 파일의 개수
- `input()` 대신 `readline()`으로 입력을 받는다. 다만 `\n`이 포함되어 있으므로 `strip()`도 붙여준다.
- 파일명의 확장자만 리스트에 저장한다.
- `collections.Counter()`를 이용해 확장자의 개수를 센다. -> `counter`
- `counter`의 키 값들을 정렬하고, 한 줄씩 출력한다.
---
- 길이 L인 문자열에서 split()의 시간복잡도가 O(L)이 맞을까요?
---
=> [튜브] 2021.07.19

changwoomon/README.md, changwoomon/implementation/10994_별찍기-19.py, changwoomon/implementation/20291_파일정리.py
- [10994_별 찍기 - 19](https://www.acmicpc.net/problem/10994)
- [20291_파일 정리](https://www.acmicpc.net/problem/20291)
---
- 규칙에 맞게 윗부분 출력
- 가운데 부분 출력 후 아랫부분은 윗부분을 그대로 뒤집어서 출력
> `시간복잡도`:  O(NlogN)
- 파일 이름을 받아올 때 `.`으로 split 후 확장자만 가져와 Counter에 넣는다.
- 확장자 이름 기준으로 정렬하여 출력한다.
---
=> [원딜] 2021.07.19

dkswndms4782/implementation/16926_배열돌리기1.cpp, dkswndms4782/implementation/2615_오목.cpp
- [오목](https://www.acmicpc.net/problem/2615)
- [배열돌리기1](https://www.acmicpc.net/problem/16926)
---
> `시간복잡도`:  O(V^2)(V : 바둑판 원소 개수)
- 각 정점마다 dfs진행
- 깊이가 5일 경우 정답과 좌표 출력
- dfs진행 방향은 4갈래로 정해서 배열로 둠
- 깊이가 5인데 이전에 바둑알 하나가 놓여있을 경우 막기 위해 if문으로 검사 후 continue
> `시간복잡도`: O(R * min(N,M)/2 * N * M)..?
- 1번 회전할때마다 배열에 값 새로 갱신
- R번 회전
=> [감자] 2021.07.21

osmosm7/implementation/2615_오목.py
- [오목](https://www.acmicpc.net/problem/2615)
---
> `시간복잡도`: 잘 모르겠습니다 ㅠㅠ
- 해당 위치에서 1시방향, 3시방향 5시방향, 6시방향 총 4방향을 탐색하는 dfs 작성
- 바둑판을 돌며 0이 아닌 숫자를 만나면 dfs 실행 (만약 반대 방향이 같은 숫자면 실행하지 않음)
- 해당 방향이 같은 숫자면  cnt+1 해줌
- 리턴된 cnt가 5면 해당 숫자와 위치 출력!
---
=> [구너] 2021.07.21

osmosm7/implementation/15787_기차가어둠을헤치고은하수를.py, osmosm7/implementation/2615_오목.py
- [기차가 어둠을 헤치고 은하수를](https://www.acmicpc.net/problem/15787)
- 오늘까지 한문제씩만 풉니다 ㅠㅠ
---
- n x 20 deque 배열 생성
- 1,2, 3,4 조건에 따라 인풋을 다르게 설정
- 각각의 방법마다 다르게 처리하는 구조 필요 
- 1,2 일때  > 해당위치를 각각 1,0으로 변경 (기존에 1,0이어도 상관없음)
- 3,4 일때 > 각각 deque의 특성을 이용해 한칸씩 밀거나 한칸씩 당기고 0 추가
=> [구너]2021.07.22

peacecheejecake/README.md, peacecheejecake/implementation/15787_기차가어둠을헤치고은하수를.py, peacecheejecake/implementation/17276_배열돌리기.py
- [기차가 어둠을 헤치고 은하수를](https://www.acmicpc.net/problem/15787)
- [배열 돌리기](https://www.acmicpc.net/problem/17276)
---
> `시간복잡도`: O(M)
- N개의 기차를 리스트 `train`으로 나타내고, 모두 0으로 초기화한다.
- train[i]를 이진수로 나타냈을 때, 각각의 자리에 사람이 있을 때 1, 없을 때 0이다.
- 각각의 연산은 다음과 같은 규칙으로 처리한다. 낮은 자리수부터 앞 좌석을 나타낸다.
1. k번째 자리에 탑승: k번째 자리의 OR 연산한 값
2. k번째 자리에서 하차: 원래 수 - k번째 자리에서 AND 연산 한 값
3. 하나씩 뒤로 이동: 원래 수에 LEFT SHIFT 연산한 값. 단, 21번째에 사람이 있으면 하차시킨다.
4. 하나씩 앞으로 이동: 원래 수에 RIGHT SHIFT 연산한 값.
- 통과하는 기차의 개수만을 물어봤으므로, `set(train)`의 길이를 출력한다.
- 각도가 0이나 360이면 그대로 출력한다.
- 회전해야 하는 축의 원소를 `axes` 리스트에 담는다. 편의상 각 축의 원소를 하나씩 담은, 총 n개의 튜플을 담는다.
- 아래 그림과 같이 묶기 위해 축의 순서는 (부 대각선, 가운데 행, 주 대각선, 가운데 열) 순서로 한다. 이 때 '묶어주는' 것은 부 대각선을 넘어가야 하느냐를 파악하기 위함이다. 만약 부 대각선을 넘는 경우, 해당 축에 대해서는 `axes`에 저장된 원소들을 거꾸로 읽어서 갱신한다.
- 회전한 이후의 위치를 s, 45도를 …
=> [튜브] 2021.07.22

peacecheejecake/README.md, peacecheejecake/implementation/15787_기차가어둠을헤치고은하수를.py, peacecheejecake/implementation/17276_배열돌리기.py, peacecheejecake/implementation/17413_단어뒤집기2.py, peacecheejecake/implementation/20436_ZOAC3.py
- [ZOAC 3](https://www.acmicpc.net/problem/20436)
- [단어 뒤집기 2](https://www.acmicpc.net/problem/17413)
---
> N: 문자열 길이
- 키보드의 좌표를 저장할 때, 왼손과 오른손 정보도 함께 담는다.
- 알파벳 하나씩, 거리 + 1만큼 더해준다.
> N: 문자열 길이
- 출력할 문자열, 부분 문자열, 테그 안에 있는지 여부를 나타내는 변수를 각각 초기화한다.
- 문자열을 한 자리씩 순회하면서, 아래 규칙에 따른다.
- '<'를 만나면, 그 이전까지의 부분 문자열(단어)을 뒤집어서 출력할 문자열에 더한다.
- '>'를 만나면, 그 이전까지의 부분 문자열(태그)과 '>'를 더한다.
- ' '(공백)을 만나면, 태그 밖에 있을 때만 뒤집은 부분 문자열과 공백을 더해 출력할 문자열에 더한다.
- 나머지 경우는 해당 자리를 부분 문자열에 더하고 다음 순서로 넘어간다.
- 마지막 부분 문자열이 단어라면 더해지지 않았으므로, 이를 뒤집어서 더해준 후 출력한다.
---
=> [튜브] 2021.07.20

opijae/implementation/20207_달력.py, opijae/implementation/21608_상어초등학교.py
- [달력](https://www.acmicpc.net/problem/20207)
- [상어초등학교](https://www.acmicpc.net/problem/21608)
---
> `시간복잡도`: o(n) n=366
- 증감배열이란걸 활용해서 풀었다. 
- 시작일은 +1 끝나는 다음날 -1 이 기록되는 배열이다.
- 이 배열을 이용해 조금 더 빨리 캘린터 배열을 만들 수 있다.
> `시간복잡도`:  o(4n^4)
참고 : https://hillier.tistory.com/76
- 조건에 따라 구현 했다.
- 조건 3은 for문 j가 먼저 돌고  i가 돌기 때문에 고려하지 않아도 된다.
---
=> [후미] 2021.07.23

dkswndms4782/implementation/20207_달력.cpp, dkswndms4782/implementation/21608_상어초등학교.cpp
- [달력](https://www.acmicpc.net/problem/20207)
- [상어초등학교](https://www.acmicpc.net/problem/21608)
---
> `시간복잡도`: O(N * 365)
- 3-5의 일정이 들어오면 arr[3], arr[4], arr[5]에 +1을 해줌
- 366번만큼 for문을 돌며 arr[i] = 0일때는 가로 세로 곱한 값 result에 더해줌
- arr[i]가 0이 아닐때는 width +1, height는 최댓값으로 설정
> `시간복잡도`: O(N*N*4*4)
- 풀다가 잘 안풀려 블로그 참고했습니다!
- 현재 좌석 구조체 만듦 :x,y,empty, near(friend)
- 학생 구조체 만듦 :num, friend
- seat형을 가진 vector에 전체 맵 만큼 돌며 값 넣어준 후 sort. 맨 앞의 값이 현재 좌석 값이 됨
- 점수 계산할땐 주변 친구를 count하여 점수 계산
---
=> [감자] 2021.07.23

peacecheejecake/README.md, peacecheejecake/implementation/15787_기차가어둠을헤치고은하수를.py, peacecheejecake/implementation/17276_배열돌리기.py, peacecheejecake/implementation/20207_달력.py, peacecheejecake/implementation/21608_상어초등학교.py
- [달력](https://www.acmicpc.net/problem/20207)
- [상어 초등학교](https://www.acmicpc.net/problem/21608)
---
> `시간복잡도`: O(CN)
>  C: 달력 길이(=365)
- 날짜별로 일정 개수를 저장한다.
- 일정 개수가 0이 되기 전까지 너비를 1씩 늘리고, 높이는 
- 0을 만나면 직사각형 넓이를 계산해서 총 넓이에 더해준다.
> `시간복잡도`: O(N^4)
- NxN 리스트에 `좌표->학생`을, 딕셔러니에 `학생->좌표`를 기록한다.
- 좋아하는 학생이 자리에 앉아있으면, 그 자리의 인접한 곳에 1씩 더하는 식으로 1번 조건을 고려한다.
- 1번에서 해결되지 않으면, 빈 자리 주변의 빈 자리를 세어 2번 조건을 고려한다.
- 2번의 후보가 여러개면 정렬하여 3번 조건을 고려한다.
- 만족도 계산 규칙에 따라 전체 만족도를 계산하고 출력한다.
=> [튜브] 2021.07.23

osmosm7/implementation/20207_달력.py, osmosm7/implementation/21608_상어초등학교.py
- [달력](https://www.acmicpc.net/problem/20207)
- [상어초등학교](https://www.acmicpc.net/problem/21608)
---
> `시간복잡도`:  n
- input에 대해 가장 큰수와 작은 수 찾음
- 가장큰수 +1 길이의 list 생성
- 각 일정에 속하는 list 위치 +1 씩 해줌
- 가장 작은 숫자부터 탐색하며 한 블럭의 일정이 가장 많이 겹친 부분 체크 (now_max) & 일정 길이 +=1
- 일정이 없으면 (list[i] ==0) 현재까지 일정 길이와 가장 많은 일정 수 곱해서 answer에 더해줌
- answer 출력
> `시간복잡도`: n^3 ??
- (n x n) mat 생성
- 입력 학생 순서대로 mat의 각 위치에서  [y,x, 좋아하는 친구, 빈공간] list 더해줌
- mat의 모든 위치 순회하면 친구, 빈공간, y,x 순으로 정렬
- 모든 친구에 대해 했으면 mat를 순회하며 만족도 조사
- 만족도 출력
=> [구너] 2021.07.23

osmosm7/implementation/14719_빗물.py, osmosm7/implementation/20164_홀수홀릭호석.py
- [홀수홀릭호석](https://www.acmicpc.net/problem/20164)
- [빗물](https://www.acmicpc.net/problem/14719)
---
> `시간복잡도`:  모르겠습니다.....
- 풀이과정
- min,max 설정
- 숫자가 들어오면 숫자 내 홀수 개수 확인
- 숫자의 길이 1이면 min,max 값 갱신
- 숫자 길이 2면 두 수를 합한 수를 다음 숫자로 넘김
- 숫자 길이 3이상이면 자를 2곳의 후보들을 찾고 각후보들로 dfs 시행
- 반복
> `시간복잡도`:  O(N)
- 풀이과정
- 빗물이 고이는 곳은 높은곳 과 높은 곳 사이
- 두 높은곳 중 낮은곳 기준으로 빗물이 고임
- 그래서 양방향에서 한번씩 빗물의 양을 확인하고 더 작은값을 취함
=> [구너] 2021.07.26

peacecheejecake/README.md, peacecheejecake/implementation/14719_빗물.py, peacecheejecake/implementation/20164_홀수홀릭호석.py
- [홀수 홀릭 호석](https://www.acmicpc.net/problem/20164)
- [빗물](https://www.acmicpc.net/problem/14719)
---
> `시간복잡도`: O(L^3); L은 N의 길이
- `count_odd` 함수는 홀수의 개수를 센다.
- `simulate` 함수는 문제의 규칙에 따라 최소, 최대를 재귀적으로 계산한다.
- 숫자의 길이가 3 이상인 경우, 이중 for문으로 완전탐색한다.
> `시간복잡도`: O(HW)
- 가로 W, 세로 H인 이차원 리스트(=2차원 블록세상)를 만든다. 편의상 바닥을 첫 번째 행에 오게 한다.
- 블록이 있는 자리는 1, 없는 자리는 0으로 채운다.
- 각 행마다 1 사이에 있는 0의 개수를 구해서 더한다.
---
=> [튜브] 2021.07.26

dkswndms4782/implementation/14719_빗물.cpp, dkswndms4782/implementation/20164_홀수홀릭호석.cpp
- [홀수홀릭호석](https://www.acmicpc.net/problem/201624)
- [빗물](https://www.acmicpc.net/problem/14719)
---
> `시간복잡도`: O(N^3)..? (N : 숫자의 길이)
- 재귀함수 사용
- 수의 길이가 3이상일때는 for문 두개로 쪼개서 수를 만든 후 재귀
- 수의 길이가 2일때는 두 수 더하기
- 1일때 max와 min비교
> `시간복잡도`: O(W)
- 현재 간의 빗물의 양은 양쪽 최대값중 작은값에서 현재 칸의 높이 뺀 값
- 현재 index기준으로 left, right의 최대값 구함
- 더해줌
=> [감자] 2021.07.26

changwoomon/README.md, changwoomon/implementation/14719_빗물.py, changwoomon/implementation/20164_홀수홀릭호석.py
- [홀수 홀릭 호석](https://www.acmicpc.net/problem/20164)
- [빗물](https://www.acmicpc.net/problem/14719)
---
> `시간복잡도`: 음... 🤔
- `num_of_odd(num)`: num을 한 글자씩 for 문을 돌며 홀수의 개수 리턴
- `odd_holic_hoseok(num, cnt)`: 문제의 연산을 수행하는 함수
- `num_of_odd` 함수의 리턴값을 cnt에 더함
- 수가 한 자리이면 함수에서 받아온 cnt와 기존에 존재하던 최소, 최대를 비교하여 갱신
- 수가 두 자리이면 앞뒤를 더해 새로운 수를 만들어 재귀
- 수가 세 자리 이상이면 가능한 모든 분할을 고려하여 새로운 수를 만들어 재귀
> `시간복잡도`: O(W), W: 가로 길이
- 쌓여있는 블록 중 가장 높게 쌓인 블록의 개수(`max_H`)와 index(`max_H_idx`)를 구한다.
- 양 끝에서부터 `max_H_idx`까지 가면서 빗물이 고일 수 있는 최대 높이를 구한다.
---
=> [원딜] 2021.07.26

sally/README.md, sally/implementation/14719_빗물.cpp, sally/implementation/20164_홀수 홀릭 호석.cpp
- [20164_홀수 홀릭 호석](https://www.acmicpc.net/problem/20164)
- [1419_빗물](https://www.acmicpc.net/problem/1419)
---
> `시간복잡도`: O(M^4)
> - 자리수(M): log_10^N
> - 자세한 복잡도 계산은 아래 문제 풀이와 함께 기재
> - _재귀의 시간복잡도라니 끔찍하구만_ 
> - M의 값이 매우 작아서(<=9) 시간 내에 풀 수 있었던 것 같다.
- 문자열과 현재까지 나타난 홀수의 개수를 파라미터로 받는 재귀 함수 `func`
- `func`의 역할: 문자열의 자리수에 따라, 문자열의 경우의 수를 나누고, 다시 `func`을 호출
- 규칙에 따라, 가장 먼저, 인자로 받은 문자열에서 홀수의 수를 카운트
- 자리수가 1이라면 현재까지 센 홀수의 수를 전역값과 비교하여 최소/최대 값 업데이트
- 자리수가 2라면, 각 자리수를 정수화하여 더하고, 이를 다시 함수에 넣음(재귀)
- 자리수가 3이상이라면, 경우의 수를 만들어 함수에 다시 넣음(재귀)
- 2중 for문을 사용하여 아래와 같이 3개의 범위로 나눠줌 → `O(1/2 x N^2)`
- [0, i)
- [i, j)
- [j, N)
- 다음 문자열의 자리수는 최악의 경우 → `M-1` (ex. 99999 → 999 + 9 + 9 = 1017)
- 재귀의 최악 depth는 `M`
- 한번의 재귀마다 반복되는 횟수는 최악의 경우, `1/2 x (현재 문자열의 길이)^2`
- func 함수 호출 1회 마다, odd_count 함수 호출
- odd_count의 …
=> [샐리] 2021.07.26

dkswndms4782/implementation/16719_ZOAC.cpp
- [ZOAC](https://www.acmicpc.net/problem/16719)
---
> `시간복잡도`: O(N^2) (N : 문자열의 길이)
- stack에 탐색을 시작했던 왼쪽 idx를 넣음
- check배열은 그 idx에 해당하는 값을 출력할지 확인하기 위함
- check[stack의 top + 1]이 true라면 현재에서 오른쪽까지는 사전순서대로 출력한 것 -> 이때 pop
- 왼쪽부터 작은값을 찾아 그 값의 idx를 stack에 push
=> [감자] 2021.07.27

sally/README.md, sally/implementation/16719_ZOAC.cpp
- [16719_ZOAC](https://www.acmicpc.net/problem/16719)
---
> - N: 입력 문자열의 길이
- 분할 정복
- a, b로 확인할 범위를 계속 유지하거나, 이동시켜가며 문제 풀이
- 주어진 범위 내에서 가장 작은(아스키코드상) 문자를 앞에서부터 찾아서 출력에 추가
- 출력할 문자의 위치를 유지하는 bool 배열을 업데이트하며, bool 배열상 위치가 true인 값을 모두 출력
- 출력이 완료되면, `현재 위치 ~ 현재의 상한 인덱스`의 범위를 재귀로 호출
- 이후, `현재의 하한 인덱스 ~ 현재 위치`의 범위를 재귀로 호출
---
=> [샐리] 2021.07.27

changwoomon/README.md, changwoomon/implementation/16719_ZOAC.py
- [ZOAC](https://www.acmicpc.net/problem/16719)
---
> `시간복잡도`: O(N^2), N: 문자열의 길이
- 입력받은 문자열의 길이만큼 `""` 리스트를 만든다.
- `ZOAC(string, i)`
- string에서 최솟값과 그 인덱스를 찾아 `answer[i+인덱스] = 최솟값`으로 값을 넣어준다.
- answer 리스트 출력
- 최솟값 인덱스+1 ~ 문자열 끝까지 재귀
- 최솟값 인덱스 전까지 재귀
---
=> [원딜] 2021.07.27

opijae/implementation/14716_빗물.py, opijae/implementation/16719_zoac.py, opijae/implementation/20164_홀수홀릭호석.py, opijae/two_pointer/11659_구간합구하기4.py, opijae/two_pointer/11728_베열합치기.py
- [zoac](https://www.acmicpc.net/problem/16719)
---
> `시간복잡도`: 재귀를 n 번돌고 한 step마다 n번이니 O(n^2) ..?
- https://hillier.tistory.com/109 참고
- 제일 작은 값 기준으로 앞, 뒤를 나눠서 진행한다.
- 이진 탐색 푸는거 처럼 풀면 될거 같다.
---
=> [후미] 2021.07.27

opijae/implementation/14716_빗물.py, opijae/implementation/16719_zoac.py, opijae/implementation/20164_홀수홀릭호석.py, opijae/two_pointer/11659_구간합구하기4.py, opijae/two_pointer/11728_베열합치기.py
- [배열합치기](https://www.acmicpc.net/problem/11728)
- [구간합구하기4](https://www.acmicpc.net/problem/11659)
---
> `시간복잡도`:  nlogn
- 두 배열을 합치고 sort
> `시간복잡도`:  n
- 사전에 합을 구한후 입력이 들어오면 index에 맞춰어 빼준다.
---
---
=> [후미] 2021.07.28

sally/README.md, sally/two_pointer/11659_구간 합 구하기 4.cpp, sally/two_pointer/11728_배열 합치기.cpp
- [11728_배열 합치기](https://www.acmicpc.net/problem/11728)
- [11659_구간 합 구하기 4](https://www.acmicpc.net/problem/11659)
---
> `시간복잡도`: O(NlogN)
- 벡터에 모두 담은 후, sort
> `시간복잡도`:O(M+N)
> - N: 배열 입력 수
> - M: 테스트 수
- 배열에 입력을 받으면서, 누적합처럼 만들어놓는다.
- 구간합을 구할 때, 좌측인덱스를 a, 우측인덱스를 b라고 하면, `arr[b] - arr[a-1]` 계산해서 출력
---
=> [샐리] 2021.07.28

osmosm7/two_pointer/11659_구간합구하기4.py, osmosm7/two_pointer/11728_배열합치기.py
- [배열 합치기](https://www.acmicpc.net/problem/11728)
- [구간합 구하기 4](https://www.acmicpc.net/problem/11659)
---
> `시간복잡도`:  O((N+M)) ? : n+m 만큼 순회 + 매번 append 하니까?
- 풀이과정
- a,b 두 리스트 0번 위치 숫자를 가져옴
- 두 숫자의 크기를 비교해 작은 숫자를 정답 리스트에 넣어줌
- 작았던 리스트의 인덱스 +1, 만약 리스트 벗어났다면 큰 숫자로 갱신
- 반복 후 정답 출력
> `시간복잡도`: O(N) 
- 풀이과정
- dp를 생성해 n번째 자리에 n번째 까지 합을 저장
- a ,b가 입력으로 들어오면 dp[b] - dp[a-1]로 구간 합 출력
---
=> [구너] 2021.07.28

peacecheejecake/README.md, peacecheejecake/two_pointer/11659_구간합구하기4.py, peacecheejecake/two_pointer/11659_구간합구하기4_ver2.py, peacecheejecake/two_pointer/11728_배열합치기.py
- [배열 합치기](https://www.acmicpc.net/problem/11728)
- [구간 합 구하기 4](https://www.acmicpc.net/problem/11659)
---
> `시간복잡도`: O(M + N)
- 두 배열의 포인터가 가리키는 값이 더 작을 때, 그 값을 인쇄하고 해당 배열의 포인터를 +1 한다.
- 두 배열 중 하나가 모두 출력될 때까지 반복한다.
- 하나의 배열을 끝까지 보고 나서는, 나머지 배열의 출력되지 않은 부분을 출력한다.
> `시간복잡도`: O(MlogN)
- 세그먼트 트리를 만들고 이를 활용해 구간합을 계산한다.
- 이걸 왜 했을까
> `시간복잡도`: O(M + N)
- 각각의 원소까지 더했을 때의 합을 구해 리스트에 담는다.
- `j번째까지 합 - (i - 1)번째까지 합`을 출력한다.
---
=> [튜브] 2021.07.28

coodingpenguin/README.md, coodingpenguin/two_pointer/11659_구간합구하기4.py, coodingpenguin/two_pointer/11728_배열합치기.py
- [배열 합치기](https://www.acmicpc.net/problem/11728)
- [구간 합 구하기 4](https://www.acmicpc.net/problem/11659)
---
> `시간복잡도`:  배열 A의 크기 N, 배열 B의 크기 M에 대해 O(N+M)   
> 배열 A와 배열 B 모두 한 번씩 순회하므로 N+M이다.
- 각 배열 A, B에 대한 포인터를 두고 해당 포인터에 있는 요소를 비교해 작은 값을 정렬된 배열 `sorted_arr`에 추가한다.
- 둘 중 한 포인터가 해당 배열을 다 돌았을 경우 루프문을 종료하고 남은 요소를 `sorted_arr`에 추가한다.
> `시간복잡도`: 수 개수 N, 예시 수 M에 대해, O(N+M)    
> 접두사 합을 구하기 위해 배열을 한 번 순회하므로 N이고   
> 구간합을 구할 때의 시간복잡도는 O(1)이므로 예시 수를 고려했을 때 
> 이 둘을 합하면 최종 시간 복잡도는 O(N+M)이다.
- 입력 받은 N개의 수를 `arr`에 저장하고 접두사 합을 계산한다.
- 예를 들어, [1, 2, 3]이면 접두사 합은 [1, 1+2, 1+2+3] = [1, 3, 6]이다.
- 접두사합을 이용하여 구간합을 구한다. 
---
=> [펭귄] 2021.07.28

changwoomon/README.md, changwoomon/implementation/16719_ZOAC.py, changwoomon/two_pointer/11659_구간합구하기4.py, changwoomon/two_pointer/11728_배열합치기.py
- [11728_배열 합치기](https://www.acmicpc.net/problem/11728)
- [11659_구간 합 구하기 4](https://www.acmicpc.net/problem/11659)
---
> `시간복잡도`: O(NlogN), N: 두 배열의 원소 개수 합
- 두 배열을 합친 후 정렬하여 출력
> `시간복잡도`: O(N), N: 수의 개수
- `_sum`: 0 ~ 각 원소 인덱스 수의 합
- i번째 수부터 j번째 수까지 합을 `_sum[j-1]-_sum[i-2]`로 계산하여 출력
---
=> [원딜] 2021.07.28

dkswndms4782/two_pointer/11659_구간합구하기4.cpp, dkswndms4782/two_pointer/11728_배열합치기.cpp
- [배열합치기](https://www.acmicpc.net/problem/11728)
- [구간합구하기4](https://www.acmicpc.net/problem/11659)
---
> `시간복잡도`: O(N + M)
- 각 배열의 원소를 하나씩 비교, 더 작은 수 출력
- 예를 들어 A배열의 원소 값이 더 작았을 경우,  A배열의 표시index a는 1증가
- a == N, b == M일때 stop
> `시간복잡도`: O(N + M)
- 각 원소의 누적합을 나타내는 배열 만들기
- 시작 index(a)와 끝 index(b)를 받았을때, sum[b] - sum[a-1]을 출력
---
=> [감자] 2021.07.28

sally/README.md, sally/two_pointer/20922_겹치는 건 싫어.cpp, sally/two_pointer/21921_블로그.cpp
- [21921_블로그](https://www.acmicpc.net/problem/21921)
- [20922_겹치는 건 싫어](https://www.acmicpc.net/problem/20922)
---
- 입력받으면서, 누적합을 벡터에 push_back
- K부터 N까지 반복하며, 해당 인덱스를 target이라고 할 때, `벡터[target] - 벡터[target - K]` 값의 max를 출력
- start index, end index를 유지
- 입력을 받으면서 end index를 늘려감
- 입력받은 값의 개수를 유지하는 배열 nums를 유지
- 범위(start index ~ end index) 내에 `end index에 위치한 값`이 K개 이상이라면, start index를 늘려가며 범위를 줄여감
- 범위를 줄여가면서 nums 배열의 값을 업데이트
---
=> [샐리] 2021.07.29

osmosm7/two_pointer/20922_겹치는건싫어.py, osmosm7/two_pointer/21921_블로그.py
- [겹치는건 싫어](https://www.acmicpc.net/problem/20922)
- [블로그](https://www.acmicpc.net/problem/21921)
---
- 풀이과정
- 200001 길이 체크리스트 생성
- lt를 0으로 잡고 입력 중 0번째 값의 체크리스트 위치 +1
- 만약 체크리스트 위치 값이 k 보다 크면
- 체크리스트[입력값의 lt 위치 값] 을 1 빼주고 lt +1
- 체크리스트 위치 값이 k가 될때까지 반복
- 현재 길이 체크해서 기존 가장 긴 값과 비교해 갱신
- 가장 긴 길이 출력
- 풀이과정
- sum(lst[i:i+m]) 로 했다가 시간초과....
- 1일부터 m 일까지 를 초기 & 최대 방문수로 설정
- 하루씩 순회하며 가장 처음 날짜 방분수를 빼주고 다음 날짜 방문수 추가
- 기존 최대 방문수와 비교해 갱신
- 최대 방문수 출력 
---
두 방법이 시간차이가 많이 나나 봅니다 N 과 1차이?
- 1. now_num = sum(lst[i:i+m])
- 2. now_num = now_num - lst[i-1] + lst[i+m-1]
---
=> [구너] 2021.07.29

peacecheejecake/README.md, peacecheejecake/two_pointer/20922_겹치는건싫어.py, peacecheejecake/two_pointer/21921_블로그.py
- [블로그](https://www.acmicpc.net/problem/21921)
- [겹치는 건 싫어](https://www.acmicpc.net/problem/20922)
---
- 부분합을 가장 첫 X일 방문자 합으로 초기화한다.
- 가장 빠른 일자의 방문자 수를 빼고, 다음 하나를 더하며 문제의 답을 찾는다.
- 각각의 X일 집합마다, 최대 방문자 수와 중복된 횟수를 기록한다. 최대 방문자 수가 갱신되면 중복 횟수는 1로 초기화되고, 그렇지 않으면 +1 한다.
- 부분 수열 안의 숫자마다 중복 횟수를 딕셔너리로 기록한다. 만약 K번 넘게 등장하는 숫자가 있으면, `excess` 집합에 넣어둔다.
- 전체 수열을 모두 탐색할 때까지, 다음을 반복한다.
- 일단 부분 수열 바로 다음 수를 부분 수열에 추가한다. 문제의 조건에 맞으면 최대 길이가 1 늘어나고, 그렇지 않으면 제일 앞의 수를 제거한다.
- 제거로 인해 K+1개 있던 수가 K개가 된다면 `excess` 집합에서 빼준다. 반대로 새로 추가했더니 K+1번 중복된다면 집합에 추가한다.
- 최대 길이만 구하면 되기 때문에, K번 넘게 중복되어도 길이가 줄어들지 않게 해 보았다. 연산량 차이는 거의 없는 것 같다. (더 늘어난 것 같기도 하다)
---
=> [튜브] 2021.07.29

osmosm7/two_pointer/15961_회전초밥.py, osmosm7/two_pointer/20922_겹치는건싫어.py, osmosm7/two_pointer/21921_블로그.py, osmosm7/two_pointer/2470_두용액.py
- [회전 초밥](https://www.acmicpc.net/problem/15961)
- [두 용액](https://www.acmicpc.net/problem/2470)
---
- 풀이과정
- 회전 초밥이므로 마지막 n 번째 초밥이 시작 초밥이 될 수 있게 새 리스트 생성
- 초밥 별로 개수를 체크할 수 있는 리스트/딕트 생성
- 보너스 초밥은 무조건 들어가므로 체크 리스트에 1로 시작
- 정답(초밥의 최대개수)도 1로 시작
-체크리스트에 초밥 개수가 추가해주는데 0이면  answer +1
-k개 이상이면 맨 앞 초밥을 제거하는데, 기존 초밥 개수가 1개면 answer -1
- 정답 갱신
- 풀이과정
- 우선 입력을 sorting
- 왼쪽 끝, 오른쪽 끝을 시작점으로 잡고
- 두 용액의 합의 절대값을 초기 답으로 설정
- 두 값의 절대값을 비교해 절대값 큰 쪽의 위치를 중간 쪽으로 변경
- lt = rt가 될때까지 반복
---
- 회전 초밥에서 체크리스트를 리스트랑 defaultdict로 만들어 봤는데 비교해보면
- 리스트로 하는게 쪼끔 더 빠르더라구요
- 근데 또 메모리는 같은
---
=> [구너] 2021.07.30

dkswndms4782/two_pointer/11659_구간합구하기4.cpp, dkswndms4782/two_pointer/11728_배열합치기.cpp, dkswndms4782/two_pointer/20922_겹치는건싫어.cpp, dkswndms4782/two_pointer/21921_블로그.cpp
- [블로그](https://www.acmicpc.net/problem/21921)
- [겹치는 건 싫어](https://www.acmicpc.net/problem/20922)
---
- X의 길이만큼 0부터 더해준 후, start index의 값을 빼주고 end index의 값을 더해주며 sliding window방식으로 합을 구함
- 합이 max보다 클 경우 max 값 갱신, max값과 같을 경우 count++;
- 현재 부분수열에서 겹치는 값이 얼마나 나왔는지 확인하기 위한 count 배열이 있음
- count[num[end]]의 값이 K + 1과 같다면, start의 index를 +1해주고 count[num[start]]를 -1해줌
- ((num[end]와 num[start]가 같을때) + 1)까지 위 연산 반복 후  end index + 1
- 위 과정들 반복
---
=> [감자] 2021.07.29

opijae/two_pointer/11659_구간합구하기4.py, opijae/two_pointer/20922_겹치는건싫어.py, opijae/two_pointer/21921_블로그.py
- [블로그](https://www.acmicpc.net/problem/21921)
- [겹치는건싫어](https://www.acmicpc.net/problem/20922)
---
> `시간복잡도`: O(n)
- 같은 길이의 리스트를 한칸씩 밀면서 합을 check
- 밀때는 왼쪽꺼를 빼고 오른쪽거를 더한다.
> `시간복잡도`: O(n)
- 동일한 숫자가 k개 나올때 까지 리스트를 오른쪽으로 확장한다.
- 동일한 숫자가 k가 나오면 해당 숫자가 나올때 까지 리스트를 축소한다.
---
=> [후미] 2021.07.29

changwoomon/README.md, changwoomon/two_pointer/11659_구간합구하기4.py, changwoomon/two_pointer/11728_배열합치기.py, changwoomon/two_pointer/20922_겹치는건싫어.py, changwoomon/two_pointer/21921_블로그.py
- [21921_블로그](https://www.acmicpc.net/problem/21921)
- [20922_겹치는 건 싫어](https://www.acmicpc.net/problem/20922)
---
- X 칸의 합을 0 ~ N-X까지 한 칸씩 옮겨주며 구한다.
- 합이 최댓값보다 크다면 최댓값 갱신, 합이 최댓값과 같다면 cnt + 1
- `array[right]`에 해당하는 숫자가 K 개보다 적게 있다면 right + 1, 아니면 left + 1
- 이런 식으로 한 칸씩 옮겨가면서 최댓값 갱신
---
=> [원딜] 2021.07.29

dkswndms4782/two_pointer/15961_회전초밥.cpp, dkswndms4782/two_pointer/20922_겹치는건싫어.cpp, dkswndms4782/two_pointer/21921_블로그.cpp, dkswndms4782/two_pointer/2470_두용액.cpp
- [두 용액](https://www.acmicpc.net/problem/2470)
- [회전 초밥](https://www.acmicpc.net/problem/15961)
---
> `시간복잡도`: O(NlogN)
- 절댓값 기준으로 sort
- 연속된 index 두개를 합한 후 절댓값이 최소인 값을 저장, 출력
> `시간복잡도`: 
- 현재 나온 수가 몇개인지 확인하는 check배열과 중복된 값을 나타내는 count 변수 선언
- count가 최소일 때 종류 개수를 k-count로 갱신. 이때 쿠폰(c)의 개수가 check[c]에서 0이면 종류를 +1을 해줘도 되므로 종류 개수를 k-count + 1로 갱신
- start는 0, end는 k에서 시작하며 start = (start + 1)  % N, end = (end + 1) % N으로 갱신하므로 start가 다시 0이 되면 while문 종료
---
=> [감자] 2021.07.30

opijae/two_pointer/11659_구간합구하기4.py, opijae/two_pointer/15961_회전초밥.py, opijae/two_pointer/20922_겹치는건싫어.py, opijae/two_pointer/21921_블로그.py, opijae/two_pointer/2470_두용액.py
- [두용액](https://www.acmicpc.net/problem/2470)
- [회전초밥](https://www.acmicpc.net/problem/15961)
---
> `시간복잡도`:  nlogn 
- 1. 배열을 정렬
- 2. 왼쪽 끝, 오른쪽 끝 부터 더하기
- 3. 더한 값이 양 수면 오른쪽 값(큰값)을 줄이고 아님 반대로한다.
> `시간복잡도`: n
- 서비스 초밥은 먹었다 친다.
- check 배열을 만들어 다른 종류의 먹은 초밥 개수를 check 한다.
- '회전'초밥을 고려해 index를 설정해 줘야된다.
---
=> [후미] 2021.07.30

opijae/two_pointer/15961_회전초밥.py, opijae/two_pointer/1806_부분합.py, opijae/two_pointer/2470_두용액.py, opijae/two_pointer/3151_합이0.py
- [부분합](https://www.acmicpc.net/problem/1806)
- [합이0](https://www.acmicpc.net/problem/3151)
---
> `시간복잡도`:  O(n)
- left, right 두개의 포인터를 사용해서 품
- `arr[left:right]` 가 S보다 작으면 right++ 해 값을 키우고 아니면 left ++ 해 값을 줄이는 방식으로 간다.
- right가 끝에 다으면 더 이상 증가하면 안된다.
> `시간복잡도`: O(n^2)
- [블로그](https://blog.naver.com/PostView.naver?blogId=jinhan814&logNo=222446622366&categoryNo=52&parentCategoryNo=52&viewDate=&currentPage=1&postListTopCurrentPage=1&from=postView) 참고
- 투포인터로 어떻게 풀지 감이 잘 안잡힌다...
- 세 수 i,j,k가 있을 때 i+j = -k 가 되야된다는 점을 이용한다.
- i+j의 결과들을 index에 맞추어 cnt 베열에 ++를 해준다.
- dp 처럼 접근을 하는 거 같습니다.
---
=> [후미] 2021.08.02

opijae/two_pointer/15961_회전초밥.py, opijae/two_pointer/1806_부분합.py, opijae/two_pointer/20366_같이눈사람만들래.py, opijae/two_pointer/20442_ㅋㅋ뤀ㅋ.py, opijae/two_pointer/3151_합이0.py
- [ㅋㅋ루ㅋㅋ](https://www.acmicpc.net/problem/20442)
- [같이눈사람만들래?](https://www.acmicpc.net/problem/20366)
---
> `시간복잡도`:  O(n)
- R의 개수를 구하고 투포인터 를 이요해 양쪽을 탐색하며 K의 개수를 센다.
- 답은 왼쪽, 오른쪽 K의 개수중 최소값 *2 +R의 개수로 구한다.
> `시간복잡도`: O(n^3)
- 총 두개의 페어가 필요하다
- 한 개의 페어는 완탐으로 찾고 나머지 페어는 투포인터를 사용해 원하는 값을 구한다.
---
=> [후미] 2021.08.03

changwoomon/README.md, changwoomon/brute_force/1969_DNA.py, changwoomon/brute_force/2503_숫자야구.py, changwoomon/two_pointer/20366_같이눈사람만들래.py, changwoomon/two_pointer/20442_ㅋㅋ루ㅋㅋ.py
- [1969_DNA](https://www.acmicpc.net/problem/1969)
- [2503_숫자 야구](https://www.acmicpc.net/problem/2503)
---
> `시간복잡도`: O(MNlogN)
- 입력받은 DNA들을 한 글자씩 옮겨가며 가장 많이 등장하는 문자를 answer에 추가한다.
- 이때, 등장 횟수가 동일한 여러 글자가 있을 수 있으므로 `등장횟수, 알파벳`으로 정렬
- answer와 입력받은 DNA들을 비교하며 Hamming Distance를 구해 출력
- 전체 후보군을 cand set에 저장
- cand를 for 문을 돌며 cand[인덱스]와 입력받은 숫자[인덱스]가 같으면 strike_cnt+1, cand[인덱스]가 `입력받은 숫자[:인덱스], 입력받은 숫자[인덱스+1]`(해당 인덱스를 제외한 나머지 숫자) 안에 있으면 ball_cnt+1
- strike_cnt, ball_cnt가 입력받은 정보와 다르면 set에서 제거
- cand의 len을 출력
---
=> [원딜] 2021.08.04

dkswndms4782/brute_force/1969_DNA.cpp, dkswndms4782/brute_force/2503_숫자야구.cpp
- [DNA](https://www.acmicpc.net/problem/1969)
- [숫자야구](https://www.acmicpc.net/problem/2503)
---
> `시간복잡도`: O(MN)(M : 염기서열 길이)(N : 염기서열 개수)
- 각 자리마다 A,T,C,G와 차이나는 값을 구함
- {A,3}이렇게 넣은 후 사전순, 값이 큰 순으로 sort
- 맨 앞 값의 char는 result에 더하고, 그 뒷 값의 int는 count에 더한 후 출력
> `시간복잡도`: O(9*N*M)(M : 1에서 9까지의 서로 다른 숫자 세 개로 구성된 세 자리 수 개수)(N : 질문개수)
- 123부터 999까지 0이 들어가지 않고 수가 겹치지 않는 수를 v에 넣음
- 이를 N개의 질문의 값과 비교하여 strike,ball값이 완전히 겹치면 count++, 아니면 break
=> [감자] 2021.08.04

opijae/brute_force/1969_DNA.py, opijae/brute_force/2503_숫자야구.py, opijae/two_pointer/20366_같이눈사람만들래.py, opijae/two_pointer/20442_ㅋㅋ뤀ㅋ.py
- [DNA](https://www.acmicpc.net/problem/1969)
- [숫자야구](https://www.acmicpc.net/problem/2503)
---
> `시간복잡도`:  O(n*m) n = DNA 수 m = DNA 길이
- 각 DNA 마다 제일 많이 나타나는 문자열을 고르는 문제이다.
- 해밍거리는 N - 최대 빈도수의 값으로 구한다.
> `시간복잡도`: O(n) 
- 111 ~999 까지 후보군이 될수 있는 수들을 모두 구한다.
- 매 입력마다 입력으로 주어진 strike, ball이 조건에 맞는 지 확인하고 틀리면 후보군에서 지운다.
---
=> [후미] 2021.08.04

peacecheejecake/README.md, peacecheejecake/brute_force/1969_DNA.py, peacecheejecake/brute_force/2503_숫자야구.py
- [DNA](https://www.acmicpc.net/problem/1969)
- [숫자 야구](https://www.acmicpc.net/problem/2503)
---
> `시간복잡도`: O(NM)
- 모든 DNA를 배열에 저장하고, 1열부터 M열까지 가장 많이 등장한 뉴클레오티드를 고른다. 가장 많이 등장한 뉴클레오티드는 Counter를 이용해 구하고, 여러 개가 가능한 경우를 고려해 정렬의 key에 알파벳 사전 순서를 포함한다.
> `시간복잡도`: O(ND^3)
>
>   D는 가능한 숫자 개수(=9)
- 순열로 가능한 모든 숫자를 딕셔너리의 key로 하고, value는 True로 초기화한다.
- 입력을 한 줄씩 읽을 때마다 가능한 모든 숫자를 검사한다. 만약 스트라이크나 볼 개수가 입력과 다르면, 딕셔너리의 값을 False로 바꾼다.
- 하나의 입력에 대한 처리가 끝나고, 값이 False인 숫자를 딕셔너리에서 지우면 실행 속도가 빨라질 것 같다.
---
=> [튜브] 2021.08.04

changwoomon/README.md, changwoomon/brute_force/17626_FourSquares.py, changwoomon/brute_force/1969_DNA.py, changwoomon/brute_force/2422_한윤정이이탈리아에가서아이스크림을사먹는데.py, changwoomon/brute_force/2503_숫자야구.py
- [2422_한윤정이 이탈리아에 가서 아이스크림을 사먹는데](https://www.acmicpc.net/problem/2422)
- [17626_Four Squares](https://www.acmicpc.net/problem/17626)
---
> `시간복잡도`: O(N^3)
- 섞어먹으면 안되는 조합의 입력을 a, b라 했을 때, `do_not[a][b] = True`, `do_not[b][a] = True`로 표시해줌
- i (1\~N), j (i+1\~N) 2중 for 문을 돌며 `do_not[i][j]`가 True이면 continue로 넘겨줌, False라면 k (j+1~N)까지 3중 for 문을 돌며 `do_not[i][k]`, `do_not[j][k]` 중 하나라도 True이면 continue로 넘겨주고 False라면 cnt+1
> `시간복잡도`: O(N^{3/2})
- 1부터 입력받은 n의 0.5승까지의 제곱 값들을 table에 저장해놓는다.
- n이 table에 있는 값 하나와 같으면 1 출력
- n이 table에 있는 값 두 개의 합과 같으면 2 출력
- n이 table에 있는 값 세 개의 합과 같으면 3 출력
- 나머지의 경우 4 출력
---
=> [원딜] 2021.08.05

opijae/brute_force/17626_FourSquares.py, opijae/brute_force/2422_한윤정이이탈리아에가서아이스크림을사먹는데.py
- [한윤정이이탈리아에가서아이스크림을사먹는데](https://www.acmicpc.net/problem/2422)
- [FourSquares](https://www.acmicpc.net/problem/17626)
---
> `시간복잡도`:  O(n) + combination(이거 시간 복잡도를 모르겠네요 ㅠ)
- 가능한 아이스크림 조합을 찾은 후 조합이 되는지 하나씩 확인한다.
> `시간복잡도`: O(n) 
- 차례대로 하나로 나누어 떨어지는지 두개가 필요한지... 확인해본다.
---
=> [후미] 2021.08.05

osmosm7/brute_force/17626_Foursquares.py, osmosm7/brute_force/2422_한윤정이이탈리아에가서아이스크림을사먹는데.py
- [한윤정이 이탈리아에 가서 아이스크림을 사먹는데](https://www.acmicpc.net/problem/2422)
- [Four Squares](https://www.acmicpc.net/problem/17626)
---
> `시간복잡도`: O('N^3')
- 풀이
- 각각 i,j,k가 (1,n-2), (i+1,n-1), (j+1,n) 까지 도는 3중 포문을 돈다.
- 만약 (i,j),(i,k),(j,k)가 먹으면 안되는 조합에 있으면 continue
- cnt+=1
> `시간복잡도`: O('N^2')
- 풀이과정
- dp 로 풀이
- n까지 0으로 채운 리스트 생성
- 우선 모든 제곱수의 답을 1로 갱신
- n보다 작은 j에 대해
- min(lst[i],lst[i-j*j]+lst[j*j]) 을 이용해 lst[i] 갱신
---
=> [구너] 2021.08.05

peacecheejecake/README.md, peacecheejecake/brute_force/17626_FourSquares.py, peacecheejecake/brute_force/1969_DNA.py, peacecheejecake/brute_force/2422_한윤정이이탈리아에가서아이스크림을사먹는데.py, peacecheejecake/brute_force/2503_숫자야구.py
- [한윤정이 이탈리아에 가서 아이스크림을 사먹는데](https://www.acmicpc.net/problem/2422)
- [Four Squares](https://www.acmicpc.net/problem/17626)
---
> `시간복잡도`: O(N^3)
- 1부터 N까지 수를 key로, key + 1부터 N까지 수를 담은 집합을 value로 하는 딕셔너리(`checker`)를 생성한다. 이는 어떠한 아이스크림이 앞에 왔을 때 다음에 놓일 수 있는 다른 아이스크림을 말한다.
- 2번째 줄부터 입력을 받고, 둘중 작은 값의 집합에서 큰 값의 아이스크림을 제거한다. (각각의 집합에는 더 큰 수밖에 없으므로)
- 딕셔너리 내 모든 집합을 순회하면서, 첫 번째 아이스크림(`i`)과 두 번째 아이스크림(`j`)이 정해졌을 때,  세 번째 올 수 있는 아이스크림의 개수를 구한다. 이는 `i`와 함께 먹을 수 있는 동시에 `j`와 함께 먹을 수도 있어야 하는 아이스크림의 개수와 같다. 즉 `checker[i]`와 `checker[j]`의 교집합 원소 개수를 구하면 된다. 경우의 수를 누적해서 더하고 출력한다.
> `시간복잡도`: O(n^(3/2))
- `simulate` 함수가 대부분의 일을 한다. 함수는 다음과 같이 동작한다.
- n 이하의 제곱수를 구해 리스트에 담아둔다. (`squares`)
- n이 `squares`의 원소인지 검사한다. 해당되면 1을 반환한다.
- 모든 제곱수를 한 번 빼 보고 다시 검사한다. (`n = 2 * sqrt(n/2)^2`일 때를 제외하면 같은 경우가 두 번씩 발생하므로, …
=> [튜브] 2021.08.05

changwoomon/README.md, changwoomon/brute_force/18511_큰수구성하기.py, changwoomon/brute_force/5568_카드놓기.py
- [5568_카드 놓기](https://www.acmicpc.net/problem/5568)
- [18511_큰 수 구성하기](https://www.acmicpc.net/problem/18511)
---
> `시간복잡도`: O(nPk)
- `itertools.permutations` 사용
- 카드 순열을 구한 후 set에 넣고 len 출력
> `시간복잡도`: O(kn log(kn)) 아마도,,,
집합 K의 원소 개수: k
N의 자릿수: n
- `itertools.product` 사용
- 만들 수 있는 수의 경우의 수를 구해 역으로 for 문을 돌며 N보다 작을 때 출력 후 break
---
=> [원딜] 2021.08.06

osmosm7/brute_force/17626_Foursquares.py, osmosm7/brute_force/18511_큰수구성하기.py, osmosm7/brute_force/2422_한윤정이이탈리아에가서아이스크림을사먹는데.py, osmosm7/brute_force/5568_카드놓기.py
- [큰수구성하기](https://www.acmicpc.net/problem/18511)
- [카드놓기](https://www.acmicpc.net/problem/5568)
---
> `시간복잡도`:  DFS라 잘.....
- DFS로 큰수부터 k자리수를 만들어보고 (''를 이용해 작은 수도 체크)
- 같거나 작아지는 순간 출력
> `시간복잡도`: O(n^k)
- 순열 > set로 중복 제거
=> [구너] 2021.08.06

opijae/brute_force/14501_퇴사.py, opijae/brute_force/16439_치킨치킨치킨.py, opijae/brute_force/16927_두스티커.py, opijae/brute_force/9073_동전게임.py
- [두스티커](https://www.acmicpc.net/problem/16927)
- [치킨치킨치킨](https://www.acmicpc.net/problem/16439)
---
> `시간복잡도`:  O(n^2)
- 두 장의 스티커를 골라 각각 h,w를 뒤집는 경우 마는 경우를 다 고려한다.
> `시간복잡도`:  combination(n)....이건 모르겠다
- 열 에서 3개 조합 만들고 각 조합 마다 돌면서 최대값을 찾는다.
---
=> [후미] 2021.08.10

opijae/brute_force/14501_퇴사.py, opijae/brute_force/9073_동전게임.py
- [동전게임](https://www.acmicpc.net/problem/9079)
- [퇴사](https://www.acmicpc.net/problem/14501)
---
> `시간복잡도`:  O(n) n = 반복 하는 횟수
- 열방향으로 3개, 행 방향 3개 대각선 2개 방향을 각각 쓰냐 안쓰냐의 경우로 나눠서 매 경우마다 돌린다.
> `시간복잡도`: O(n) 
- 그 전날까지의 최대값에 dp 형식으로 더한다,.
---
=> [후미] 2021.08.09

dkswndms4782/brute_force/16439_치킨치킨치킨.cpp, dkswndms4782/brute_force/16508_전공책.cpp, dkswndms4782/brute_force/16937_두스티커.cpp, dkswndms4782/brute_force/2615_오목.cpp
- [오목](https://www.acmicpc.net/problem/2615)
- [전공책](https://www.acmicpc.net/problem/16508)
---
> `시간복잡도`: O(N^3)...?(N : 바둑판크기)(모든 칸에 돌이 있는지 돌기 * 각 방향별로 dfs함수)
- 방향은 동, 동남, 남, 동서 4가지가 있다. 
- 왼쪽 위에서부터 돌들을 돌면서, 각 돌마다 방향별로 몇개의 돌이 나열되어 있는지 셈
- 이때 현재 돌이 가려는 방향 반대편으로 돌이 1개라도 놓여있으면, false로 함
- 돌이 5개 놓여있으면 이긴 돌 출력
> `시간복잡도`: O(N*N*W)(N:문자열의 개수, W:각 문자열의 최대 길이)
- map에 현재 구하고싶은 문자열의 각 char가 몇개 있는지 count
- 문자열을 1개고르는 방법, 2개 고르는 방법 ... N개 고르는 방법 나눈 후 순열을 이용해 사용할 문자 고름
- 선택된 문자열들 통틀어 각 char가 몇개 있는지 count
- 현재 구하고픈 문자열 각 char보다 선택된 문자열 각 char의 수들이 많거나 같을 경우 최솟값 갱신
---
=> [감자] 2021.08.11

opijae/brute_force/16508_전공책.py, opijae/brute_force/2615_오목.py
- [오목](https://www.acmicpc.net/problem/2615)
- [전공책](https://www.acmicpc.net/problem/16508)
---
> `시간복잡도`:  O(1)
- 한 점에서 8방향을 갈 수 있는데 여서 앞으로 볼 4방향을 정합니다.
- 오목 특성상 6목이 되면 안되기 때문에 앞으로 보는 4방향외 뒤로 4방향을 봐 같은 색이 있는지 확인한다.
> `시간복잡도`: O(n^3)
- nC1 ....nCn 까지 모든 조합을 만들어서 체크합니다
- 각 조합마다 target 문자열이 있는지 확인하자
---
=> [후미] 2021.08.11

dkswndms4782/brute_force/12919_A와B2.cpp, dkswndms4782/brute_force/14620_꽃길.cpp, dkswndms4782/brute_force/16508_전공책.cpp, dkswndms4782/brute_force/2615_오목.cpp
- [꽃길](https://www.acmicpc.net/problem/14620)
- [A와B 2](https://www.acmicpc.net/problem/12919)
---
> `시간복잡도`: O(N^6)....?.....
- 3개의 꽃이 동시에 놓일 수 있는 경우를 dfs로 찾음
- dfs로 찾을 때 마다 최솟값 갱신
> `시간복잡도`: O(T^(T-S))(reverse : O(T))....?....
- [여기](https://jaehoon0124welcome.tistory.com/44)를 참고하였습니다
- 완성된 단어에서 빼면서 처음 단어를 만들 수 있는지 확인
- A로 시작 -> A로 끝 : 맨 뒤 A빼기 가능
- A로 시작 -> B로 끝 : 어떤 연산도 불가능
- B로 시작 -> A로 끝 : 뒤집어서 B빼기 가능, 맨 뒤 A빼기 가능
- B로 시작 -> B로 끝 : 뒤집어서 B빼기 가능
=> [감자] 2021.08.12

opijae/brute_force/12919_A와B2.py, opijae/brute_force/14620_꽃길.py, opijae/brute_force/16508_전공책.py, opijae/brute_force/2615_오목.py
- [꽃길](https://www.acmicpc.net/problem/14620)
- [A와B2](https://www.acmicpc.net/problem/12919)
---
> `시간복잡도`: nC3 + n
- 1.1 ~ n-1.n-1 까지 좌표 조합을 모두 찾은다음
- 주어진 조건에 만족하면 min계산
> `시간복잡도`:  O(len(t) - len(s))
- [여기](https://jaehoon0124welcome.tistory.com/44) 참고 했습니다.
- s에서 붙이는 것이 아닌 t에서 빼는 식으로 진행 
- t의 맨아ㅠㅡ 맨뒤 글자를 보며 판단
---
=> [후미] 2021.08.12

opijae/brute_force/12919_A와B2.py, opijae/brute_force/14620_꽃길.py, opijae/brute_force/1548_부분삼각수열.py, opijae/brute_force/16508_전공책.py, opijae/brute_force/2615_오목.py, opijae/brute_force/2961_도영이가만든맛있는음식.py
- [부분삼각수열](https://www.acmicpc.net/problem/1548)
- [도영이가만든맛있는음식](https://www.acmicpc.net/problem/2961)
---
> `시간복잡도`: nlogn ,nC3
- 삼각수열이 될려면 3가지 수열을 만족해야되는데 이를 정열을 사용해 생각해보면
- x<y<z일때 x+y>z만 만족하면 삼각 수열이된다.
- 이를 이용해 인덱스 조합을 뽑고 조건에 만족하면 최대값을 갱신한다.
> `시간복잡도`: O(2**n * n)
- 모든 재료 조합을 고려해 풉니다.
---
=> [후미] 2021.08.13

opijae/brute_force/1025_제곱수.py, opijae/brute_force/15661_링크와스타트.py, opijae/brute_force/링크와스타트.py
- [링크와스타트](https://www.acmicpc.net/problem/15661)
- [제곱수](https://www.acmicpc.net/problem/1025)
---
> `시간복잡도`:  O(2^(n-1) * n^2)
- 비트마스킹으로 모든 조합을 구합니다.
- 조합을 다쓰는 것이 아닌 절반만 사용합니다( 1001 = 0110)
> `시간복잡도`: O(4n^3*m^3)
- [블로그](https://nerogarret.tistory.com/41) 참고했습니다.
- 모든 헹열을 돌면서 나올수 있는 행,열 등차들을 모두 구해 비교합니다.
---
=> [후미] 2021.08.16 

peacecheejecake/README.md, peacecheejecake/brute_force/12919_A와B2.py, peacecheejecake/brute_force/14500_테트로미노.py, peacecheejecake/brute_force/14620_꽃길.py, peacecheejecake/brute_force/15686_치킨배달.py
- [테트로미노](https://www.acmicpc.net/problem/14500)
- [치킨 배달](https://www.acmicpc.net/problem/15868)
---
> `시간복잡도`: O(NMT)..? (`T: 회전과 대칭을 고려한 테트로미노 수(=19)`)
- 가능한 모든 테트로미노에 대해, 네 점의 상대적인 위치를 정의한다. 이 때 (0, 0)이 되는 점은 가장 위 -> 가장 왼쪽 순으로 정한다. (정말로 노동력을 동원하는 방법밖에 없을까 해서 구글링 해보았더니, leve 3인 DFS로 해결한 풀이([설명](https://velog.io/@skyepodium/%EB%B0%B1%EC%A4%80-14500-%ED%85%8C%ED%8A%B8%EB%A1%9C%EB%AF%B8%EB%85%B8))가 일반적인 것 같다)
- 종이를 벗어나는지에 주의하며 모든 테트로미노를 검사하고, 최댓값을 갱신한다.
> `시간복잡도`: O(N^2 + C choose M)..? (`C: 치킨집 개수`) (combinations 시간복잡도가 명확하지 않네요..)
- 집과 치킨집 좌표를 각각의 리스트에 저장한다.
- combinations로 모든 치킨집 좌표 조합을 생성하며 최솟값을 찾는다.
---
=> [튜브] 2021.08.17

peacecheejecake/README.md, peacecheejecake/brute_force/12919_A와B2.py, peacecheejecake/brute_force/14500_테트로미노.py, peacecheejecake/brute_force/14620_꽃길.py, peacecheejecake/brute_force/15686_치킨배달.py, peacecheejecake/brute_force/21278_호석이두마리치킨.py, peacecheejecake/brute_force/21315_카드섞기.py
- [호석이 두 마리 치킨](https://www.acmicpc.net/problem/21278)
- [카드 섞기](https://www.acmicpc.net/problem/21315)
---
> `시간복잡도`: O((N choose 2) * (N + M)) = O(N^4) ..?
- 인접리스트에 도로 정보를 담는다.
- 모든 치킨집 조합에 대해 완전탐색한다. 두 치킨집에서 각각 출발하며, 하나의 조합마다 두 번의 bfs를 수행한다. 발견된 노드(건물)까지의 최솟값을 리스트에 갱신한다.
- 최솟값이 여러 개인 경우가 있으므로, `cands` 리스트에 모든 최솟값 조합을 담는다. 루프를 빠져나온 후 `cands`를 정렬해서 첫 번째 원소를 출력한다.
> `시간복잡도`: O((logN)^2)
- 한 번의 (2, K) 이후 원래 카드가 어디에 위치할지, 인덱스 지도를 만든다. K번째는 K-1번째보다 섞는 카드 수가 2^(K-1)개 만큼 더 있음을 이용한다.
- 이중 for 문으로 완전 탐색한다. 카드를 초기화 하고 인덱스 지도를 이용해 두 번 섞는다. 이 결과가 입력된 카드 순서와 같으면 결과를 출력하고 종료한다.
---
- 호식이 문제 시간복잡도 계산이 맞을까요?
---
=> [튜브] 2021.08.18

opijae/brute_force/14391_종이조각.py, opijae/brute_force/16637_괄호추가하기.py, opijae/brute_force/21278_호석이두마리치킨.py, opijae/brute_force/21315_카드섞기.py
- [괄호추가하기](https://www.acmicpc.net/problem/16637)
- [종이조각](https://www.acmicpc.net/problem/14391)
---
> `시간복잡도`: O(n^2)
- 오늘꺼 어렵네요 ㅠㅠ
- [참고](https://hjp845.tistory.com/159) 했습니다.
- 괄호를 칠 수 있는 경우를 모두 구한다,
- 괄호가 쳐지면 다음 괄호는 한칸 띄고 쳐야된다.
- 괄호가 쳐진 경우에 따라 stack을 사용해 계산을 하고
- 괄호 계산이 끝나면 나머지들을 계산합니다.
> `시간복잡도`: O(2^(n*m) *n *m)
- [참고](https://vixxcode.tistory.com/23) 했습니다.
- 모든 칸마다 가로로 더하는지 세로로 더하는 경우 두가지를 생각합니다.
=> [후미] 2021.08.19

dkswndms4782/brute_force/16637_괄호추가하기.cpp
- [괄호추가하기](https://www.acmicpc.net/problem/16637)
---
> `시간복잡도`: O((1<<N)*N)(N : 연산자의 개수)
- 각 연산자마다 씌울 수 있는 경우의 수는 비트마스크로 처리
- 두개의 연속된 연산자가 괄호가 씌워질경우 연산하지 않게 함
- a + b가 있으면 (a+b) + 0형태로 만들어줌. 이 형태가 괄호가 씌워진 형태와 같다고 할 수 있음
- a * b또한 (a*b) + 0으로 표현
- 위와같이 연산 후 앞에서부터 차례로 연산하면 현재 식의 값이 나온다. 후 갱신
=> [감자] 2021.08.19

opijae/simulation/16234_인구이동.py
- [인구이동](https://www.acmicpc.net/problem/16234)
---
> `시간복잡도`: O(n^2 * (V+E)) V: 정점, E: 간선 (BFS)
- 모든 나라에 대해 bfs를 돌려서 인구이동이 가능한지 확인합니다.
- 인구이동을 할때 마다 인구 값과 좌표들을 배열에 저장해 나중에 평균 냅니다.
---
- 간만에 알고리즘인데 맵네요..ㅠ
=> [후미] 2021.08.30

coodingpenguin/simulation/16234_인구이동.py, coodingpenguin/simulation/17144_미세먼지안녕.py
- [인구이동](https://www.acmicpc.net/problem/16234)
---
> `시간복잡도`: N에 대해 O(N^4)
- 모든 지점에 대해서 BFS를 수행합니다. 단, visited 2차원 배열을 두어 방문 여부를 체크하고 두 번 이상 방문하지 않도록 합니다.
- BFS를 하면 탐색한 모든 노드에 대해서 인구 이동을 합니다.
- 만약 한 번 이상으로 인구 이동을 했다면, `days`를 +1 해줍니다.
- 위를 계속 반복하다 한 번도 인구 이동을 하지 않았다면 탈출합니다.
---
> 두 번째 문제는 어려워 풀지 못했습니다... 1000원 자진반납합니다ㅠㅠ
=> [펭귄] 2021.08.30

sally/README.md, sally/simulation/16234_인구 이동.cpp, sally/simulation/17144_미세먼지 안녕!.cpp
- [16234_인구 이동](https://www.acmicpc.net/problem/16234)
- [17144_미세먼지 안녕!](https://www.acmicpc.net/problem/17144)
---
> `시간복잡도`: O(M * N^2)
> - M: 인구이동 발생횟수 (M < 2000, 인구 이동이 발생하는 일수가 2,000번 보다 작거나 같은 입력만 주어진다.)
- BFS를 통해 같은 그룹으로 묶일 대상을 선정하고 임시 배열에 변경된 인구수를 기록
- 인구수에 변화가 일어나지 않으면 반복문을 빠져나와서 결과를 출력
> `시간복잡도`: O(R*C*T)
- 미세먼지의 확산을 구현
- 공기청정기 작동을 구현
- T회 반복
---
=> [샐리] 2021.08.30

opijae/simulation/16236_아기상어.py, opijae/simulation/20056_마법사상어와파이어볼.py
- [아기상어](https://www.acmicpc.net/problem/16236)
---
> `시간복잡도`:  O(n*nlog(n)
- BFS로 지금 위치에서 가장 가까운 이동 지점을 찾았습니다.
- 아기상어 위치를 0으로 바꿔줘야 됩니다....ㅎ
=> [후미] 2021.09.01

opijae/simulation/16235_나무제테크.py, opijae/simulation/16235_나무제테크_시간초과.py, opijae/simulation/16236_아기상어.py, opijae/simulation/20056_마법사상어와파이어볼.py
- [나무제테크](https://www.acmicpc.net/problem/16235)
---
> `시간복잡도`: k * n^2 * TlogT (T는 나무의 개수)
- 각 칸마다 심어저 있는 나무 배열을 만들고 나이대로 오름 차순 합니다.
- 봄에 양분을 먹을 수 없다면 해당 인덱스 뒤에 있는 나무 모두 죽습니다.
=> [후미] 2021.09.02

opijae/simulation/16235_나무제테크.py, opijae/simulation/16235_나무제테크_시간초과.py, opijae/simulation/16236_아기상어.py, opijae/simulation/17140_이차원배열과연산.py, opijae/simulation/20056_마법사상어와파이어볼.py
- [이차원배열과연산](https://www.acmicpc.net/problem/17140)
---
> `시간복잡도`: ,상수니 O(1)..?
- 열 부분에 주의해서 구현하면 될듯 합니다.
- 구현에 시간이 좀 걸리네여..ㅎ
=> [후미] 2021.09.03

peacecheejecake/README.md, peacecheejecake/simulation/15685_드래곤커브.py, peacecheejecake/simulation/16236_아기상어.py
- [아기 상어](https://www.acmicpc.net/problem/16236)
- [드래곤 커브](https://www.acmicpc.net/problem/15685)
---
> `시간복잡도`: O(N^3)
- distances 리스트는 매 턴마다 각각의 칸까지 최소 거리를 나타낸다. 원소를 모두 무한대로 초기화한다.
- 규칙에 따라 bfs를 수행한다. 먹을 수 있는 물고기를 발견하면 집합에 추가한 후, 가장 위/왼쪽 물고기를 선택한다.
- 가장 바깥 루프는 최대 N-1번 돌 수 있다.
> `시간복잡도`: O(NG2^(G-1))
> G는 g의 최댓값
- update 함수로 각각의 커브가 포함하는 꼭짓점을 구하고, 이를 전체 꼭짓점 집합에 추가한다.
- 새로운 꼭짓점을 찾기 위해서, 마지막 점을 중심으로 한 모든 벡터(?)를 회전시킨 후 그 점을 추가하면 된다. (차례는 거꾸로)
- 꼭짓접 집합을 순회하며 오른쪽, 왼쪽, 대각선 아래 꼭짓점이 존재하는 경우를 센다.
=> [튜브] 2021.09.01

sally/leetcode/121_best-time-to-buy-and-sell-stock.cpp, sally/leetcode/1_two-sum.cpp, sally/leetcode/217_contains-duplicate.cpp, sally/leetcode/238_product-of-array-except-self.cpp
- [1. Two Sum](https://leetcode.com/problems/two-sum/)
- [121. Best Time to Buy and Sell Stock](https://leetcode.com/problems/best-time-to-buy-and-sell-stock/)
- [217. Contains Duplicate](https://leetcode.com/problems/contains-duplicate/)
- [238. Product of Array Except Self](https://leetcode.com/problems/product-of-array-except-self/)
---
- 모든 배열을 돌면서 시작 지점을 선택(i)
- i보다 큰 수를 돌면서 더할 수를 찾음(j)
- i번째 위치에 있는 값과 j번째 위치에 있는 값을 더하고, target과 같은지 확인
- target과 같으면 벡터에 담아서 리턴
- 1번과 동일하게 N^2 복잡도로 풀었다가 타임리밋 걸림
- O(N)으로 줄일 수 있음
- 배열을 탐색하며, 최소값을 계속 업데이트/유지
- 현재 값과 최소값을 비교하고, 현재값이 최소값보다 작으면 최소값을 업데이트
- 정렬하고 앞에서부터 i번과 (i+1)번을 비교
- 배열을 순차적으로 비교하다가 비교하는 두 값이 같은 때가 있다면 true return
- 모든 케이스를 통과하면 false return
- 배열의 i 위치에 존재한 값을 제외한 모든 값을 곱한 것을 리턴 배열의 i 번째에 담아서 반환
- O(N^2)로 만들면 안된다고 해서 좀 고민
- 배열을 좌측에서부터 돌면서 i …
=> [샐리] 2021.09.19

peacecheejecake/leetcode/121_Best_Time_To_Buy_And_Sell_Stock.py, peacecheejecake/leetcode/1_Two_Sum.py, peacecheejecake/leetcode/217_Contains_Duplicate.py, peacecheejecake/leetcode/238_Product_Of_Array_Except_Self.py
- [Two Sum](https://leetcode.com/problems/two-sum/)
- [Best Time to Buy and Sell Stock](https://leetcode.com/problems/best-time-to-buy-and-sell-stock/)
- [Contains Duplicate](https://leetcode.com/problems/contains-duplicate/)
- [Product of Array Except Self](https://leetcode.com/problems/product-of-array-except-self/)
---
- nums 리스트를 정렬하되, 원래 인덱스 정보를 함께 담아서 정렬한다.
- start=0, end=N-1으로 시작(N는 nums 길이)한다.
- 두 수의 합이 target보다 작으면 start <- start + 1, target보다 크면 end <- end - 1, target과 같으면 정렬하기 전 두 인덱스를 리턴한다.
- 각각의 시점에 샀을 때, 판매 가능한 최고점을 찾는다. 최고점에서 산 가격을 빼면 수익이 된다.
- max_profit을 0으로 초기화(수익이 나지 않으면 0이 답이므로)하고, 최고 수익을 찾는다.
- 한 번 등장한 수는 집합에 추가한다.
- 집합에 포함된 수가 등장하면 True를 리턴한다.
- for loop을 빠져나오면 False를 리턴한다.
- 특정 수의 앞에 있는 수를 모두 곱한 결과, 뒤에 있는 수를 모두 곱한 결과를 각각의 리스트에 담는다.
- 같은 위치에 있는 두 수의 곱을 원소로 한 리스트를 …
=> [튜브] 2021.09.19

sally/leetcode/1143_Longest Common Subsequence.cpp, sally/leetcode/338_Counting Bits.cpp
- [338. Counting Bits](https://leetcode.com/problems/counting-bits/)
- [1143. Longest Common Subsequence](https://leetcode.com/problems/longest-common-subsequence/)
---
- 0부터 N까지 모든 수에 대해 타겟 값이 1이 될 때까지 나눠보는 방식으로 풀이함
- 각 text의 맨 앞 줄을 ' ' 공백으로 패딩함(이차원배열의 각 행, 열의 첫 줄을 0으로 초기화하기 위함)
- 이차원 배열을 사용하여 규칙에 따라 메모하며 풀이함
- 만약 비교하고자 하는 위치의 값이 같으면, 좌측 상단의 기존 값에 +1을 한 것을 해당 자리에 저장
- 비교하고자 하는 위치의 값이 다르면, 좌측 혹은 상단의 값 중 큰 값을 가져와서 해당 자리에 저장
---
=> [샐리] 2021.09.26

opijae/leetcode/143_Reorder_List.py, opijae/leetcode/190_Reverse_Bits.py, opijae/leetcode/207_Course_Schedule.py, opijae/leetcode/242_Valid_Anagram.py, opijae/leetcode/435_Non-overlapping_Intervals.py, opijae/leetcode/79_Word_Search.py, opijae/leetcode/98_Validate_Binary_Search_Tree.py
- [Valid Anagram](https://leetcode.com/problems/valid-anagram/)
- [Non-overlapping Intervals](https://leetcode.com/problems/non-overlapping-intervals/)
- [Course Schedule](https://leetcode.com/problems/course-schedule/)
- [Word Break](https://leetcode.com/problems/word-break/)
---
- source 단어에 있는 알파벳 dict을 만들고 target단어에서 알파벳을 하나씩 빼면서 anagram이 가능한지 판단,
- 기간 문제는 시작하는 날 or 끝나는 날을 기준으로 정렬을 하는게 국룰인것 같습니다.
- 끝나는 날을 기준으로 정렬을 했으니 정렬된 intervals을 돌면서 끝나는 날짜를 update 합니다.
- for문을 돌면서 다음 interval 시작일이 현재 끝나는 시점 보다 이전이면 겹치는 거다.
- [참고](https://leetcode.com/problems/course-schedule/discuss/58750/Python-easy-to-understand-indegree-solution-with-comments.)
- 해당 과목을 수강하기 위한 들어야되는 선수 과목 set과 
- 과목 별 후 강의 list를 각각 만듭니다.
- 선수 과목 조건이 만족되는 강의들을 기준으로 후 강의 목록들을 하나씩 체크합니다.
- 체크된 과목 수와 전체 과목의 수가 같다면  true, 아니면 false …
=> [후미] 2021.10.17 

peacecheejecake/leetcode/139-Word-Break.py, peacecheejecake/leetcode/207-Course-Schedule.py, peacecheejecake/leetcode/242-Valid-Anagram.py, peacecheejecake/leetcode/435-Non-overlapping-Intervals.py
- [Valid Anagram](https://leetcode.com/problems/valid-anagram/)
- [Non-overlapping Intervals](https://leetcode.com/problems/non-overlapping-intervals/)
- [Course Schedule](https://leetcode.com/problems/course-schedule/)
- [Word Break](https://leetcode.com/problems/word-break/)
---
- `collections.Counter`로 문자별 등장 횟수를 세고, 이를 set으로 만들어 같은지 확인한다.
- `intervals`를 오름차순 정렬한다.
- `prev=intervals[0]`으로 초기화하고,`intervals`의 두 번째 원소부터 순회한다.
- 각 구간의 시작을 s, 끝을 e라고 하자.
- 새로운 s가 `prev`의 e보다 작으면 겹치는 경우이므로, 하나를 제거해야 한다. 이러한 경우를 센다.
- `prev`의 e가 작을수록 제거할 구간의 수가 작아질 것이므로, 새로운 e가 `prev`의 e보다 작으면 `prev`를 새로운 구간으로 교체한다.
- 사이클 판별은 [블로그](https://hongl.tistory.com/60?category=922907)를 참고했습니다.
- `prerequisites`을 인접 리스트로 만든다.
- dfs로 사이클 여부를 판별하되, 방문 여부를 -1(dfs 종료 전), 0(방문 안함), 1(dfs 종료)로 나누어 체크한다.
- 사이클이 발생하면 바로 …
=> [튜브] 2021.10.17.

sally/leetcode/weekly-contest-265/2057. Smallest Index With Equal Value.cpp, sally/leetcode/weekly-contest-265/2058. Find the Minimum and Maximum Number of Nodes Between Critical Points.cpp, sally/leetcode/weekly-contest-265/2059. Minimum Operations to Convert Number.cpp
// PR 양식 논의 후, 변경하도록 하겠습니다.
- [문제 1]()
- [문제 2]()
- [문제 3]()
- [문제 4]()
---
- 풀이과정
- 풀이과정
- 풀이과정
- 풀이과정
---
- 궁금한 점이 있을 경우 적어주시고 없을 경우 지워주세요.
---
=> [샐리] Weekly Contest 265

peacecheejecake/leetcode/139-Word-Break.py, peacecheejecake/leetcode/2057-smallest-index-with-equal-value.py, peacecheejecake/leetcode/2058-find-the-minimum-and-maximum-number-of-nodes-between-critical-points.py, peacecheejecake/leetcode/2059-minimum-operations-to-convert-number.py, peacecheejecake/leetcode/207-Course-Schedule.py, peacecheejecake/leetcode/242-Valid-Anagram.py, peacecheejecake/leetcode/435-Non-overlapping-Intervals.py
*** 양식 논의 후 변경!
- [Smallest Index With Equal Value](https://leetcode.com/contest/weekly-contest-265/problems/smallest-index-with-equal-value/)
- [Find the Minimum and Maximum Number of Nodes Between Critical Points](https://leetcode.com/contest/weekly-contest-265/problems/find-the-minimum-and-maximum-number-of-nodes-between-critical-points/)
- [Minimum Operations to Convert Number](https://leetcode.com/contest/weekly-contest-265/problems/minimum-operations-to-convert-number/)
- [(못품) Check if an Original String Exists Given Two Encoded Strings](https://leetcode.com/contest/weekly-contest-265/problems/check-if-an-original-string-exists-given-two-encoded-strings/)
---
- 문제 그대로 구현
- head의 next가 None일 때까지 순회
- critical point 조건에 부합할 경우, 인덱스를 리스트에 담는다. 동시에 minimum distance 갱신
- 위 리스트 길이가 2 …
=> [튜브] Weekly Contest 265

peacecheejecake/leetcode/139-Word-Break.py, peacecheejecake/leetcode/2057-smallest-index-with-equal-value.py, peacecheejecake/leetcode/2058-find-the-minimum-and-maximum-number-of-nodes-between-critical-points.py, peacecheejecake/leetcode/2059-minimum-operations-to-convert-number.py, peacecheejecake/leetcode/2062-count-vowel-substrings-of-a-string.py, peacecheejecake/leetcode/2063-vowels-of-all-substrings.py, peacecheejecake/leetcode/2064-minimized-maximum-of-products-distributed-to-any-store.py, peacecheejecake/leetcode/207-Course-Schedule.py, peacecheejecake/leetcode/242-Valid-Anagram.py, peacecheejecake/leetcode/435-Non-overlapping-Intervals.py
- [Count Vowel Substrings of a String](https://leetcode.com/problems/count-vowel-substrings-of-a-string/)
- [Vowels of All Substrings](https://leetcode.com/problems/vowels-of-all-substrings/)
- [Minimized Maximum of Products Distributed to Any Store](https://leetcode.com/problems/minimized-maximum-of-products-distributed-to-any-store/)
- [Maximum Path Quality of a Graph](https://leetcode.com/problems/maximum-path-quality-of-a-graph/)
---
- 자음 위치를 찾고, 자음 사이사이에 있는 모음 substring을 대상으로 검사한다.
- 검사할 때는 길이 5 이상의 substring을 완전탐색한다.
- 처음부터 완전탐색 하는 것보다 조금 빠르지만, 많이 차이나지 않는다. (그냥 완전탐색이 더 나은것 같기도 하다.)
- word에 포함된 문자 하나씩 검사해서, 모음일 경우 그 문자를 포함한 substring 개수를 더한다.
- substring들의 (시작 위치, 끝 위치) 쌍 개수로 경우의 수를 구할 수 있다.
- 어떤 모음 index가 i일 때, 시작 위치는 (i + 1)개, 끝 위치는 (word 길이 - i)개가 가능하다.
- 따라서 각 모음마다 (i + 1) * …
=> [튜브] Weekly Contest 266

sally/programmers/week1/2019-kakao-blind_오픈채팅방.py
- [오픈채팅방](https://programmers.co.kr/learn/courses/30/lessons/42888)
---
- 닉네임 정보를 딕셔너리에 저장한다. (아이디 생성, 변경 시)
- 행동 정보(Enter, Leave)와 유저아이디를 튜플로 묶어서 입력 순서대로 리스트에 저장한다. (Change 행동정보는 저장하지 않음)
- 저장된 행동정보는 Create인지 Leave인지에 따라 "님이 나갔습니다." 혹은 "님이 들어왔습니다."로 변경되고, 유저아이디를 키로 삼아 딕셔너리에서 닉네임을 가져와서 문장을 완성한다.(행동정보 순서대로 출력)
- 리스트의 아이디를 닉네임으로 바꾸고 행동에 따라 문장을 만든다.
---
- 문제가 어렵네요 ㅠㅠ 일단 벌금내고 조금 더 생각해본 후, 풀이 추가하도록 하겠습니다 ㅠㅠ
=> [샐리] 2021.11.27

coodingpenguin/programmers/level2/멀쩡한사각형.py, coodingpenguin/programmers/level2/문자열압축.py, coodingpenguin/programmers/level2/오픈채팅방.py
- [문자열 압축](https://programmers.co.kr/learn/courses/30/lessons/60057)
- [오픈채팅방](https://programmers.co.kr/learn/courses/30/lessons/42888)
- [멀쩡한 사각형](https://programmers.co.kr/learn/courses/30/lessons/62048)
---
- 예전에 이 문제를 풀었을 때는 엄청 복잡하게 생각했었는데, 풀고 나니까 엄청 간단했던 기억이 납니다.
- n개의 단위로 문자열을 나누다고 했는데, 이게 슬라이딩 윈도우같은 그런 느낌이 아니라 n개씩 딱 떨어지는 식으로 압축하는 겁니다.
- 압축 가능한 단위는 1 ~ len(s)//2이므로, 모든 단위를 돌면서 압축 시 길이를 구해주고 최솟값과 비교해 갱신해주면 됩니다.
- 총 두 단계를 거치면 됩니다.
-  record를 돌면서 uid-닉네임 매핑과 로그 저장
- 로그를 바탕으로 최종 메시지 구하기
- uid는 고유하기 때문에 uid를 키로 하고 record를 돌면서 닉네임이 바뀌면 값을 바꾸는 식으로 하면 중복 닉네임 처리도 가능합니다. 
- 전에 풀었던 문제인데, 확실히 다시 풀어도 이해가 확 되지는 않더라구요.
- 자세한 풀이는 전에 블로그에 써놨어써 블로그 링크 남겨둡니다.
- https://cooding-penguin.netlify.app/til/problem-solving/programmers/l2-normal-square.html
---
- 오랜만에 프로그래머스 문제를 푸니까 고향에 온 기분이 드네요. 리트코드 때는 안 …
=> [펭귄] 2021.11.27

peacecheejecake/programmers/42888_오픈채팅방.py, peacecheejecake/programmers/60057_문자열압축.py, peacecheejecake/programmers/62048_멀쩡한사각형.py
- [문자열 압축](https://programmers.co.kr/learn/courses/30/lessons/60057)
- [오픈채팅방](https://programmers.co.kr/learn/courses/30/lessons/42888)
- [멀쩡한 사각형](https://programmers.co.kr/learn/courses/30/lessons/62048)
---
- 자르는 단위 크기가 1~len(s)일 때를 검토해서 최솟값을 반환한다.
- 압축된 문자 길이 최솟값은 `s`의 길이로 초기화한다.
- 조각 크기만큼 건너뛰며 조각의 첫 인덱스를 얻는다. 이전 조각을 기록해서 이번 조각과 같으면 카운트만 +1, 다르면 문자열에 더해준다.
- 마지막 조각은 반영이 안 되므로 for loop 밖에서 한 번 더 더해준다.
- 닉네임 정보는 딕셔너리({아이디:닉네임})에 기록한다.
- 들어오거나 나갔을 때, (행동, 아이디) 쌍을 리스트에 저장한다.
- 리스트의 아이디를 닉네임으로 바꾸고 행동에 따라 문장을 만든다.
- 대각선이 지나는 사각형은 W+ H에 W, H의 최대공약수를 뺀 만큼 있다.
=> [튜브] 2021.11.27

coodingpenguin/programmers/level2/124나라의숫자.py, coodingpenguin/programmers/level2/기능개발.py, coodingpenguin/programmers/level2/더맵게.py
- [124 나라의 숫자](https://programmers.co.kr/learn/courses/30/lessons/12899)
- [기능개발](https://programmers.co.kr/learn/courses/30/lessons/42586)
- [더 맵게](https://programmers.co.kr/learn/courses/30/lessons/42626)
---
- 3진법을 구하는 문제인데, "012"가 아닌 "124"를 쓴다는 점이 차이가 있습니다.
- 주의할 점은 숫자는 0부터 시작하는데 여기서는 1부터 시작합니다. 그래서 몫과 나머지를 구할 때 -1을 해주어야 합니다.
- 문제 예시에 나온 1이 0, 2가 1, 3이 2가 됩니다.
- 작업 진도와 속도를 가지고 모든 기능의 개발까지 남은 날은 구합니다.
- 두 번째 기능부터 시작해 이전 기능 중 가장 많이 걸리는 날과 비교합니다.
- 만약 그 날보다 같거나 작다면, count를 +1해줍니다.
- 왜? 앞에 기능이 오래 걸리기 때문에 앞에 기능이 완료되면 뒤의 기능은 이미 완료되어있기 때문입니다.
-   그렇지 않다면, count를 deploy 리스트에 넣어주고 최대 남은 날을 갱신하고 count를 1로 초기화해줍니다.
- 최소힙을 사용하였고 힙의 크기가 1보다 클 때까지 다음을 반복해줍니다.
- 스코빌 지수가 가장 낮은 음식을 pop합니다.
- 만약 스코빌 지수가 K보다 크거나 같다면 요구사항과 동일하므로 break합니다.
- 아니라면, 두 번째로 낮은 음식을 pop하고 섞었을 때의 스코빌 지수를 구합니다.
- 이를 힙에 넣고 섞은 횟수 …
=> [펭귄] 2021.12.04

peacecheejecake/programmers/12899_124나라의숫자.py, peacecheejecake/programmers/42586_기능개발.py, peacecheejecake/programmers/42626_더맵게.py, peacecheejecake/programmers/42888_오픈채팅방.py, peacecheejecake/programmers/60057_문자열압축.py, peacecheejecake/programmers/62048_멀쩡한사각형.py
- [124 나라의 숫자](https://programmers.co.kr/learn/courses/30/lessons/12899)
- [기능개발](https://programmers.co.kr/learn/courses/30/lessons/42586)
- [더 맵게](https://programmers.co.kr/learn/courses/30/lessons/42626)
---
- 3의 거듭제곱을 빼 가면서 정답 자릿수를 구한다.
- 자릿수가 L이라면, n에서 1 ~ L - 1 자리 수 개수를 뺀다.
- 뺄셈의 결과로 얻은 수를 3진수 문자열로 변환한다. 자릿수가 모자란 경우도 있으므로 rjust 함수로 0을 더 붙여준다.
- 2 -> 4, 1 -> 2, 0 -> 1로 변환한다.
- 앞 작업과 같이 배포하거나 그 이후에 배포하는 경우만 있으므로, 주어진 두 배열 순서 그대로 검토한다.
- [배포일, 개수] 쌍을 schedule 리스트에 저장한다.
- 남은 작업을 speed로 나눈 값을 올림하여 작업 완료일을 구한다.
- 이전 schedule 날짜가 현재 작업 완료일 이전이라면, 이전 schedule과 같이 배포하면 된다. 이전 schedule의 개수에 +1 한다.
- 그렇지 않다면, 새로운 날짜에 배포해야 한다. [작업 완료일, 1]을 리스트에 추가한다.
- schedule 리스트에서 개수만 뽑아서 리턴한다.
- scoville 리스트를 힙으로 만든다. (heapq.heapify)
- 힙의 크기가 1이 될 때까지, 다음을 반복한다.
1. 힙의 첫 번째 최솟값을 pop
2. 최솟값이 K 이상이면 break, K …
=> [튜브] 2021.12.04

sally/programmers/week2/124 나라의 숫자.py, sally/programmers/week2/기능개발.cpp, sally/programmers/week2/더 맵게.cpp
- [124 나라의 숫자](https://programmers.co.kr/learn/courses/30/lessons/12899)
- [기능개발](https://programmers.co.kr/learn/courses/30/lessons/42586)
- [더 맵게](https://programmers.co.kr/learn/courses/30/lessons/42626)
---
- 반복적으로 3으로 나누며, 나머지를 인덱스로 삼아 문자열을 가져와 붙인다.
- 문자열은 [4, 1, 2]의 순서로 이루어져 있으므로, 나머지가 0이 되면 4를 가져오고, 나머지가 1이 되면 1을 가져오는 방식이다.
- 3으로 나눠진다면, n을 -1 시켜준다.
- 위의 방식을 반복하여 문자열을 완성한 후, 리턴한다.
- 1부터 n까지 돌면서 해당 인덱스에 위치하는 progress를 100이상으로 만들 때 까지 day를 올린다.
- day를 증가시키면서, 뒤의 progress들도 (각각의 speed와 day를 곱하여) 증가시킨다.
- 100 이상의 progress 값을 만나면, cnt를 높이고, 100 이하의 progress 값을 만나면 기존에 저장하던 cnt를 벡터에 append
- Priority Queue를 사용하여 가장 작은 값 두개를 뽑아서 새 스코빌 지수를 만들고 다시 push한다.
- 최소 값이 K 이하인데, PQ안의 모든 값이 소진되면 -1을 리턴한다.
---
=> [샐리] 2021.12.04 

sally/programmers/week3/짝지어 제거하기.cpp, sally/programmers/week3/타겟 넘버.cpp, sally/programmers/week3/행렬 테두리 회전하기.cpp
- [타겟 넘버](https://programmers.co.kr/learn/courses/30/lessons/43165)
- [짝지어 제거하기](https://programmers.co.kr/learn/courses/30/lessons/12973)
- [행렬 테두리 회전하기](https://programmers.co.kr/learn/courses/30/lessons/77485)
---
- 모든 경우의 수를 만들어서 계산
- 비트마스킹을 사용하여, 각 자리수가 1이면 +, 0이면 - 연산을 수행하고, 연산 결과가 타겟 넘버와 같으면, 카운트를 올려준다.
- (펭펭님의 도움을 받아 해결!)
- 문자열을 앞에서 부터 확인
- 스택이 비었다면, 문자를 push
- 스택이 비어있지 않다면, 맨 윗 문자와 현재 보고 있는 문자를 비교한다.
- 같으면 스택을 pop 하고, 다르면 스택에 문자열을 넣는다.
- 배열에서의 위치 정보를 pair로 묶어서 큐(1)에 넣고, 배열이 담는 값도 다른 큐(2)에 넣는다.
- 원형큐에서 한 칸 밀어내는 과정과 같이, 값을 담는 큐의 맨 앞 원소를 큐(2)에서 빼서, 큐(2)의 맨 뒤로 넣어준다.
- 큐 (1), (2)를 앞에서부터 확인하고, 배열의 위치 정보값과 배열이 담는 값을 매칭시켜가며, 2차원 배열의 값을 업데이트 한다.
- 위 과정을 거치며, 매 회전마다 최소값을 저장한다.
---
=> [샐리] 2021.12.11

peacecheejecake/programmers/12973_짝지어제거하기.py, peacecheejecake/programmers/43166_타겟넘버.py, peacecheejecake/programmers/77485_행렬테두리회전하기.py
- [타겟 넘버](https://programmers.co.kr/learn/courses/30/lessons/43165)
- [짝지어 제거하기](https://programmers.co.kr/learn/courses/30/lessons/12973)
- [행렬 테두리 회전하기](https://programmers.co.kr/learn/courses/30/lessons/77485)
---
- numbers 원소 개수 이하의 자릿수를 가지는 모든 이진수가 각 숫자의 부호를 나타내는 것으로 봅니다. 즉 i번째 자리가 0이라면 numbers[i]를 더하고 1이면 뺍니다.
- 계산 결과가 target과 같으면 1씩 더하면서, 최종 정답을 구합니다.
- [공식 문서](https://docs.python.org/ko/3/library/functions.html#bin)를 보고, 이진수에서 '0b'를 제외하는 법을 배웠습니다.  formatting할 때 임의의 변수(예: `f"i:0{l}b"`에서 `l`)를 쓸 수 있다는 것도 이번에 알았습니다.
- s의 문자를 순서대로 돌면서, stack의 top 원소가 이번 문자와 "같으면 pop, 아니면 push" 합니다.
- stack이 비었으면 0, 아니면 1을 리턴합니다.
- 인덱싱의 편의를 위해 쿼리의 네 좌표에 1씩 빼줍니다.
- 왼쪽 위부터 시계방향으로 모든 좌표와 원소를 기록합니다. 네 모서리의 좌표를 먼저 구하고, 이웃한 두 모서리 사이의 좌표를 담는 방법을 사용합니다. range의 step 파라미터를 이용해 진행 방향을 지정합니다.
- 기록한 좌표가 i번째라면, 행렬의 …
=> [튜브] 2021.12.11.

coodingpenguin/programmers/level2/짝지어제거하기.py, coodingpenguin/programmers/level2/타겟넘버.py, coodingpenguin/programmers/level2/행렬테두리회전하기.py
- [타겟 넘버](https://programmers.co.kr/learn/courses/30/lessons/43165)
- [짝지어 제거하기](https://programmers.co.kr/learn/courses/30/lessons/12973)
- [행렬 테두리 회전하기](https://programmers.co.kr/learn/courses/30/lessons/77485)
---
- 비트마스크를 써서 모든 조합을 계산하여 `target`과 일치하는지 검사했습니다.
- 이번 스터디 때 while문을 썼었는데 그럴 필요가 없었습니다..ㅋㅋㅋ
- 압축 후에 이게 빈 리스트인지만 검사해주면 됩니다!
- 미로 찾기처럼 구현했습니다! 모든 방향을 다 돌 때까지(`cd < 4`) 다음을 수행해줍니다.
- 최솟값을 갱신해줍니다. 
- 이동할 위치를 구해주고 범위에 벗어나면 방향을 바꿔줍니다.
- new_matrix에 새로운 값을 넣어주고 현재 위치를 움직인 위치로 변경해줍니다.
- matrix를  new_matrix로 바꿔주고 최솟값을 `result`에 넣어줍니다.
---
=> [펭귄] 2021.12.11

opijae/programmers/짝지어제거하기.py, opijae/programmers/타켓넘버.py, opijae/programmers/행렬테두리.py
- [타켓넘버](https://proghttps://github.com/boostcamp-ai-tech-4/coding-test-study/pull/398/commitsrammers.co.kr/learn/courses/30/lessons/43165)
- [짝지어 제거하기](https://programmers.co.kr/learn/courses/30/lessons/12973)
- [행렬 테두리 회전하기](https://programmers.co.kr/learn/courses/30/lessons/77485)
---
- 0 부터 시작해 numbers에 있는 값들을 재귀적으로 더하거나 뺍니다.
- numbers에 있는 모든 수를 사용해야되니 재귀 들어갈 때 마다 index++를 해주며 numbers 끝에 다 달았는지 확인합니다.
- index가 끝에 다 달았고 현재 누적합이 목표값이랑 같은지 확인합니다. 
- 스택을 사용해 다음값과 비교합니다.
- 스택의 처음 값(제일 나중에 들어온 값)이 다음 문자열이랑 같으면 pop 해줍니다.
- 설명을 너무 못했는데 애니팡 같은 게임을 생각 하면 쉬울 것 같습니다.
- 1 부터 i*j 까지의 행렬을 만들어 줍니다.
- 쿼리마다 돌면서 범위안에 있는 배열 테두리를 돌려 줍니다.
- 돌아야 하는 좌표의 순서는 다음과 같습니다.
0 1 2 3
9&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;4
8 7 6 5
- 코너마다 다음 봐야할 좌표 방향이 바뀌는 것을 이용했습니다.
---
---
=> [후미] 2021.12.11 

coodingpenguin/programmers/level2/괄호변환.py, coodingpenguin/programmers/level2/뉴스클러스터링.py, coodingpenguin/programmers/level2/메뉴리뉴얼.py
- [메뉴 리뉴얼](https://programmers.co.kr/learn/courses/30/lessons/72411)
- [괄호 변환](https://programmers.co.kr/learn/courses/30/lessons/60058)
- [뉴스 클러스터링](https://programmers.co.kr/learn/courses/30/lessons/17677)
---
- 만들 수 있는 코스 크기 리스트인 course를 돌면서 해당 코스 크기만큼의 만들 수 있는 모든 메뉴 구성을 구합니다.
- `Counter`를 사용하여 메뉴 구성의 카운트를 구하고 그 중 최대 카운트를 가진 메뉴를 추출하여 최종 메뉴 `menus`에 추가합니다.
- 반환하기 전에 알파벳 순으로 정렬해줍니다.
- 문제에 제시된 지시대로 구현했습니다.
- 다만 헷갈렸던 부분이 "u의 첫 번째와 마지막 문자를 제거하고, 나머지 문자열의 괄호 방향을 뒤집어서 뒤에 붙입니다."이었습니다.
- 단순히 문자열을 거꾸로 하는 것인 줄 알았는데 그게 아니라 반전시키는 거여서 디버깅 하는데 조금 시간을 썼습니다.
- 한 번 풀어본 문제라서 그런지 금방 풀었습니다.
- `Counter`를 사용하면 간단히 구할 수 있습니다.
- Counter에는 단순히 카운트를 세주는 것 뿐만 아니라 두 Counter에 대해 합집합, 교집합 기능도 제공합니다.
-  [여기](https://docs.python.org/ko/3/library/collections.html#:~:text=Counter%20%EA%B0%9D%EC%B2%B4%EB%A5%BC%20%EA%B2%B0 …
=> [펭귄] 2021.12.18

opijae/programmers/괄호변환.py, opijae/programmers/뉴스클러스터링.py, opijae/programmers/메뉴리뉴얼.py
- [메뉴 리뉴얼](https://programmers.co.kr/learn/courses/30/lessons/72411)
- [괄호 변환](https://programmers.co.kr/learn/courses/30/lessons/60058)
- [뉴스클러스터링](https://programmers.co.kr/learn/courses/30/lessons/17677)
---
- 나중에 오름차순으로 return해야되니 메뉴를 오름차순으로 정렬
- 코스 요리 수 많큼 조합짜서 많이 2개이상 나온 코스 만들기
- 문제 이해가 어려웠네요..
- 이해가 안가서  [질문](https://programmers.co.kr/questions/21146) 확인
- 기본적으로 문제 설명대로 구현
- 대소문자 구분없이 하기 위해 대문자로 변경
- 숫자나 특수 기호 제거
- 가공된 두 문자열을 비교하며 점수 구함
---
=> [후미] 2022.01.09

sally/programmers/week5/거리두기 확인하기.cpp, sally/programmers/week5/수식 최대화.cpp, sally/programmers/week5/튜플.py
- [거리두기 확인하기](https://programmers.co.kr/learn/courses/30/lessons/81302)
- [수식 최대화](https://programmers.co.kr/learn/courses/30/lessons/67257?language=cpp)
- [튜플](https://programmers.co.kr/learn/courses/30/lessons/64065?language=python3)
---
- depth=2인 BFS 활용
- 각 응시자의 위치에서 깊이가 2인 너비우선탐색을 수행한다.
- 너비우선탐색에서 다른 응시자가 발견되면 0, 모든 응시자의 위치 검사를 수행했을 때 다른 응시자가 발견되지 않았다면 1을 answer에 추가
- algorithm 헤더에 next_permutation 사용(모든 경우의 수에 대해 확인)
- 두가지 종류의 스택을 각각 두개씩 사용했다.
- 종류
- 종류1: 숫자(long long) 담는다.
- 종류2: 연산자(char) 담는다.
- 숫자의 수보다 연산자의 수가 더 많으므로, 편리한 계산을 위해, 숫자 하나를 먼저 스택에 넣어둔다.
- 만약 현재 타깃이 되는(수행하고자 하는) 연산자가 발견되면, 기존 숫자를 담는 스택의 top을 가져와서, 해당 연산을 수행하고, 그 결과를 다시 push 한다.
- 이렇게 세 연산자에 대해 반복 수행하면, 결국 배열에는 하나의 원소가 남는다. 이를 answer와 비교하여 더 큰 값을 담아둔다
- 문자열을 정제하여, 숫자 리스트를 담는 리스트로 만들어둔다.
- 원소를 적게 담고 있는 순서대로 정렬한다.
- 하나의 …
=> [샐리] 2022.01.15

peacecheejecake/programmers/64065_튜플.py, peacecheejecake/programmers/67257_수식최대화.py, peacecheejecake/programmers/81302_거리두기확인하기.py
- [거리두기 확인하기](https://programmers.co.kr/learn/courses/30/lessons/81302)
- [수식 최대화](https://programmers.co.kr/learn/courses/30/lessons/67257)
- [튜플](https://programmers.co.kr/learn/courses/30/lessons/64065)
---
- 응시자가 있는 칸이라면, 바로 옆칸을 검사합니다.
- 옆칸에 사람이 없다면, 한 칸 더 가서 검사합니다.
- 문제 조건을 만족하지 않는 경우가 발견되면 0을 바로 리턴합니다.
- `[숫자, 연산자, 숫자, 연산자, ...]` 순서로 담은 배열과 `연산자 집합`을 만듭니다.
- `연산자 집합`을 순회하면서 모든 경우를 검토합니다.
- step 함수는 주어진 식에서 타겟 연산자를 앞에서부터 계산합니다. 문자열로 만들고 eval 함수를 활용합니다.
- 마지막에 연산자가 하나 남았다면 절댓값을 취해 상금을 구합니다.
- 입력 문자열에 담긴 정보를 {원소 개수: 원소를 담은 집합} 딕셔너리로 만듭니다. `{`를 만나면 새 집합을 만들고, `,`나 `}`를 만나면 이어붙이던 숫자를 집합에 추가합니다.
- 튜플 길이가 1이라면, 그 값을 배열에 담아 반환합니다. 길이가 2 이상이라면, 집합 원소 개수가 하나 늘어났을 때 새로 포함된 원소를 순서대로 배열에 담습니다. (집합의 차집함 연산을 했고, 집합은 인덱싱이 불가해서 pop()을 해줬습니다.)
---
=> [튜브] 2022.01.15

sally/programmers/week6/빛의 경로 사이클.cpp, sally/programmers/week6/전화번호 목록.cpp, sally/programmers/week6/프린터.cpp
- [빛의 경로 사이클](https://programmers.co.kr/learn/courses/30/lessons/86052?language=cpp)
- [전화번호 목록](https://programmers.co.kr/learn/courses/30/lessons/42577)
- [프린터](https://programmers.co.kr/learn/courses/30/lessons/42587)
---
- visit 배열을 하나의 노드에 대해 만드는 것이 아니라, 노드의 위치 + 빛의 방향에 대해 만들어야한다.(3차원)
- 방문하지 않은 위치와 방향에 대해 시작점으로 삼는다.
- L을 가지는 노드는 -1을 의미하고, R을 가지는 노드는 +1, S를 가지는 노드는 0을 의미한다.
- 방향의 변환을 담당하는 dir 배열은 순서대로 위, 오른쪽, 아래, 왼쪽을 가리킨다.
- ex. 현재 방향에 -1(L)을 적용하면, dir 배열 기준으로 본인의 방향의 왼쪽을 가리키게 된다.
- 시작점에 도달하면, 한 턴을 종료하고, cnt를 저장한다.
- 저장한 cnt 값들을 정렬하여 return 한다.
- 문자열 벡터를 정렬하면, 사전 순으로 정렬된다.
- 가장 비슷한 문자열끼리 인접한 위치에 존재하게 된다.
- 따라서, i번째 문자열이 i+1번째 문자열의 접두어가 되는지 확인하면 된다.
- 타겟이 되는 문서를 나타내기 위해, 단순히 우선순위로 하나의 노드를 구분하는 것이 아닌, pair로 구분한다.
- 하나의 노드는 pair{우선순위, 타겟여부}로 이루어진다.(타겟노드 하나만 '타겟여부=true')
- 처리되지 않은 노드들의 …
=> [샐리] 2022.01.22

opijae/programmers/전화번호목록.py, opijae/programmers/프린터.py
- [빛의경로](https://programmers.co.kr/learn/courses/30/lessons/86052)
- [전화번호목록](https://programmers.co.kr/learn/courses/30/lessons/42577)
- [프린터](https://programmers.co.kr/learn/courses/30/lessons/42587)
---
- 이번주안에 풀고 commit하겠습니다
- 배열을 정렬하고 현재 index가 다음 index의 접두사인지 판단한다.
- 기존 배열을 우선순위와 함께 인덱스를 넣습니다.
- 큐의 첫번쨰 값이 초고 우선순위인지 판단하고 아니면 큐에 다시 넣습니다.
---
=> [후미] 2022.01.22 

coodingpenguin/programmers/level2/전화번호목록.py, coodingpenguin/programmers/level2/프린터.py
- [빛의 경로 사이클](https://programmers.co.kr/learn/courses/30/lessons/86052)
- [전화번호 목록](https://programmers.co.kr/learn/courses/30/lessons/42577)
- [프린터](https://programmers.co.kr/learn/courses/30/lessons/42587)
---
- 다 풀지 못해서 이번 주 내로 풀고 제출하겠습니다.
- 배열을 정렬한 후 전체 배열을 순회합니다.
- 순회하면서 현재 바로 다음 전화번호의 접두어가 현재 전화번호인지 확인합니다.
- 이게 가능한 이유는 정렬을 했기 때문입니다.
- 정렬 시 (문자, 길이) 기준으로 정렬을 하기 떄문에 서로 인접한 전화번호만 비교하면 됩니다. 
- 문제에 있는 그대로 구현을 해주었습니다.
- `deque`를 사용하여 큐를 구현해주었습니다.
---
=> [펭귄] 2022.01.22

peacecheejecake/programmers/.idea/.gitignore, peacecheejecake/programmers/.idea/inspectionProfiles/profiles_settings.xml, peacecheejecake/programmers/.idea/misc.xml, peacecheejecake/programmers/.idea/modules.xml, peacecheejecake/programmers/.idea/programmers.iml, peacecheejecake/programmers/.idea/vcs.xml, peacecheejecake/programmers/42577_전화번호목록.py, peacecheejecake/programmers/42598_프린트.py, peacecheejecake/programmers/64065_튜플.py, peacecheejecake/programmers/67257_수식최대화.py, peacecheejecake/programmers/81302_거리두기확인하기.py, peacecheejecake/programmers/86052_빛의경로사이클.py
- [빛의 경로 사이클](https://programmers.co.kr/learn/courses/30/lessons/86052)
- [전화번호 목록](https://programmers.co.kr/learn/courses/30/lessons/42577)
- [프린트](https://programmers.co.kr/learn/courses/30/lessons/42598)
---
- 빠른 시일 내로 풀어서 제출하겠습니다.
- 통과하지 못한 케이스가 있어서 해결한 후에 제출하겠습니다.
- deque에 (우선순위, 타겟 여부) 튜플을 담습니다.
- 문제 지시사항을 수행합니다.
---
=> [튜브] 2022.01.22

peacecheejecake/programmers/.idea/.gitignore, peacecheejecake/programmers/.idea/inspectionProfiles/profiles_settings.xml, peacecheejecake/programmers/.idea/misc.xml, peacecheejecake/programmers/.idea/modules.xml, peacecheejecake/programmers/.idea/programmers.iml, peacecheejecake/programmers/.idea/vcs.xml, peacecheejecake/programmers/42577_전화번호목록.py, peacecheejecake/programmers/42598_프린트.py, peacecheejecake/programmers/42746_가장큰수.py, peacecheejecake/programmers/42839_소수찾기.py, peacecheejecake/programmers/42860_조이스틱.py, peacecheejecake/programmers/81302_거리두기확인하기.py, peacecheejecake/programmers/86052_빛의경로사이클.py
- [가장 큰 수](https://programmers.co.kr/learn/courses/30/lessons/42746)
- [소수 찾기](https://programmers.co.kr/learn/courses/30/lessons/42839)
- [조이스틱](https://programmers.co.kr/learn/courses/30/lessons/42680)
---
- 앞 자리에 가능한 큰 수가 오게 하면 됩니다. 따라서 주어진 수를 문자열로 바꿔서 내림차순 정렬합니다.
- 다만, 자릿수가 다른 경우는 다음과 같은 규칙으로 우선순위를 정해 처리합니다.
- 짧은 수는 나머지 자리를 첫 번째 자릿수로 채웁니다. (예: `81` -> `8188`) 이 방법으로 긴 수의 남는 자리가 첫 번째 자릿수보다 클 경우에는 앞에, 작은 경우에는 뒤에 오게 할 수 있습니다. (예: `8, 89` -> `89, 8(8)`, `8, 87` -> `8(8), 87`) 
- 두 자리 수와 세 자리 수를 비교할 때, 세 자릿수의 마지막 자릿수가 첫 자리와 같을 때, 예외가 발생합니다. (예: `89, 898`) 이런 경우에는 공통된 부분의 두 번째 수가 첫 번째 수보다 작으면 긴 수가 앞에 오고, 그렇지 않으면 짧은 수가 앞에 오게 합니다. (예: `87, 878` -> `878 87 > 87 878`, `89, 898` -> `89 898 > 898 89`)
- 0이 여러개 있을 때는 "000" 처럼 되므로, 예외 처리를 해서 "0"이 되게 합니다.
- `permutations`로 모든 경우를 생성합니다.
- 주어진 수에 같은 …
=> [튜브] 2022.01.29

coodingpenguin/programmers/level2/가장큰수.py, coodingpenguin/programmers/level2/소수찾기.py
- [가장 큰 수](https://programmers.co.kr/learn/courses/30/lessons/42746)
- [소수 찾기](https://programmers.co.kr/learn/courses/30/lessons/42839)
- [조이스틱](https://programmers.co.kr/learn/courses/30/lessons/42860)
---
- 못 풀어서 [여기](https://jokerldg.github.io/algorithm/2021/05/06/most-big-number.html)를 참고하여 풀었습니다.
- 가장 어려웠던 부분은 두 번째 테스트 케이스였습니다. 30보다 3이 우선되어야 하는데 이걸 어떤 것을 기준으로 해야할지 어려웠던 것 같습니다.
- 그렇게 하고 나서 11번 케이스에서 계속 에러가 났는데, '0000'일 경우 '0'으로 출력해야 한다는 걸 확인했습니다.
- `numbers`를 역정렬해서 큰 수를 만들고 2 ~ 그 수 범위의 소수를 모두 구합니다.
- `permutations`를 사용해서 모든 숫자 조합을 구합니다. (r은 숫자의 길이까지 순회합니다.)
- 해당 숫자 조합이 소수인지 판단하고 소수이면 `result`에 추가합니다. (`result`는 집합입니다.)
- `result`의 개수를 반환합니다.
- 해당 문제는 풀지 못해서 이번 주내로 풀고 추가로 PR 올리겠습니다😥
---
=> [펭귄] 2022.01.29

opijae/programmers/가장큰수.py, opijae/programmers/소수찾기.py, opijae/programmers/전화번호목록.py, opijae/programmers/조이스틱.py, opijae/programmers/프린터.py
- [가장큰수](https://programmers.co.kr/learn/courses/30/lessons/42746)
- [소수찾기](https://programmers.co.kr/learn/courses/30/lessons/42839)
- [조이스틱](https://programmers.co.kr/learn/courses/30/lessons/42860?language=python3)
---
- 가장 큰수를 만들어야되기 때문에 각 숫자의 앞이 큰대로 정렬을 해야된다. 
- ex) 20 ,30 -> 30, 20
- 첫번째 수가 같다면 다음 수를 비교해야된다. 만약 다음 수가 없다면 이전 수로 패딩한다.
- ex) 9, 91은 앞의 수가 9로 같다.
- 9랑 91로 만들 수 있는 수의 앞자리는 9로 고정된다.
- 따라서 자리수가 부족한 경우 처음 수로 패딩을 한다.
- 99, 91을 정렬한다.
- 두 번째 수가 같을 경우 위의 방식대로 쭉 비교한다.
- 만들 수 있는 모든 조합을 만든다.
- 중복제거
- 각 수가 소수인지 판단
- 잘모르겠어서 해설 봤습니다.
- A애서 원하는 문자열은 위로갈지 아래로 갈지 정하기
- 현재 위치에서 앞으로 갈지 뒤로 갈지 정하기
- 매 위치 마다 세 단계를 거친다.
1. 지금까지 온거리랑 앞으로 가야할 거리 비교(앞을 갈지 뒤로 갈지 정하기)
2. 갈 방향을 정한후 이동거리 구하기
3. 거리를 구한 것이 최소값인지 판단
---
=> [후미] 2022.01.29 
