sally/README.md, sally/graph_traversal/1260_DFS와 BFS(메모리과다).cpp, sally/graph_traversal/1260_DFS와 BFS.cpp, sally/graph_traversal/2606_바이러스.cpp
- [바이러스](https://www.acmicpc.net/problem/2606)
- [DFS와 BFS](https://www.acmicpc.net/problem/1260)
---
- 주요변수
- `bool coms[101][101]` : 노드간 연결 상태를 나타내는 이차원 배열, 대각선은 visited 배열로 사용
- 풀이
- 1번 노드를 시작노드로 하여 BFS
- 연결되어있는지, 방문 안했었는지 확인하고 방문
- 방문 후에는 coms 이차원 배열의 대각 라인에 표시(방문했다고 표시)
- 방문할 노드를 발견할때마다 result 변수를 +1
- 주요변수
- `bool con[1001][1001]` : 연결을 나타내는 bool 이차원 배열
- `bool visited[1001]` : 방문했는지를 표시하는 bool 일차원 배열
- `queue<int> q` : BFS에 사용되는 큐
- DFS
- 인자로 들어오는 노드 번호를 출력
- 1~N까지 반복문을 돌면서 현재 노드와 연결된 노드가 있는지, 그 노드를 방문하였는지 확인
- (시작노드를 포함한) 방문했던 노드들은 visited true로 초기화했기 때문에 따로 처리하지 않아도 됨(확인하려는 노드가 본인인지)
- 연결이 되어있고, 노드를 방문하지 않았으면, 방문했다고 표시하고, 재귀를 통해서 다음 노드를 탐색
- 메모리 면에서 비효율적이지만, 작은 노드 순으로 순회해야한다는 조건 때문에 이차원 배열로 구현
- BFS
- BFS 시작 전, visited 배열을 초기화
- 큐가 비어있지 않으면 계속 반복
- 1~N까지 반복문을 돌면서 현재 노드와 연결된 노드가 …
=> [샐리] 2021.05.10

changwoomon/tree/11725_트리의부모찾기.py, changwoomon/tree/9934_완전이진트리.py
- [완전 이진 트리](https://www.acmicpc.net/problem/9934)
- [트리의 부모 찾기](https://www.acmicpc.net/problem/11725)
---
- `node`에 방문한 순서대로 노드를 넣어준다.
- 완전 이진 트리
- 2^{K-1}: 루트 노드
- 2^{K-2}의 배수들: 2층 노드들 + 루트 노드
- 2^{K-3}의 배수들: 3층 노드들 + 2층 노드들 + 루트 노드
→ 규칙을 토대로 노드들을 트리에 넣어주며 트리를 만들어준다. (이미 트리에 들어간 노드는 0으로 만들어줘 다시 넣어주는 일을 방지)
- 만든 트리를 출력한다.
- 전에 이 문제를 풀었을 때는 DFS를 사용했어서 이번에는 BFS를 사용해봤다.
- 트리의 노드들을 BFS로 돌며 해당 노드에서 갈 수 있는 다른 노드의 parent가 0일 때 현재 노드를 부모로 넣어준다.
---
=> [원딜] 2021.06.11

sally/README.md, sally/tree/11725_트리의 부모 찾기.cpp, sally/tree/9934_완전 이진 트리.cpp
- [9934_완전 이진 트리](https://www.acmicpc.net/problem/9934)
- [11725_트리의 부모 찾기](https://www.acmicpc.net/problem/11725)
---
- 조건을 찾음
- queue를 반복하는데, depth를 기준으로 `\n`를 출력하도록 함
- 큐 사이즈 만큼 돌고나면 줄바꿈 출력
- 현재 위치와 남은 길이를 pair 형으로 queue에 담음
- 현재 위치에서 남은 길이를 1/2 하여 뺀 것을 큐에 먼저 담고, 더한것을 다음에 담음(visit 하지 않았다면)
- 큐에 담을때, 해당 위치에 있는 문자를 출력하고, 그 자리를 0으로 만들어, 방문했다는 것을 표시
- 노드 수 보다 간선 수가 현저히 작으므로, 간선을 인접리스트로 표현
- 루트(1)을 시작으로, 연결된 노트를 visit 표시하고, queue에 넣음
- queue를 뽑아서 위의 과정을 반복(연결된 노트를 visit 표시하고, queue에 넣음)
---
=> [샐리] 2021.06.11

coodingpenguin/README.md, coodingpenguin/tree/11725_트리의부모찾기.py, coodingpenguin/tree/9934_완전이진트리.py
- [완전 이진 트리](https://www.acmicpc.net/problem/9934)
- [트리의 부모 찾기](https://www.acmicpc.net/problem/11725)
---
- 방문 순서별 트리 레벨을 계산하는 리스트 `level`을 생성한다. 예를 들면, 트리의 최대 깊이는 2이고 방문 순서가 [2, 1, 3]이라면, 각 위치에 해당하는 노드의 트리 레벨은 [2, 1, 2]이다.
- `level`을 순회하면서 defaultdict를 사용하여 레벨 별 노드 리스트를 생성하여 저장한다.
- `tree`를 레벨을 기준으로 정렬하고 출력한다.
> 그래프 탐색 유형에 동일한 문제가 있었네요. 근데 거의 똑같이 풀고 visited 처리하는 부분만 달랐습니다.
- 간선 정보를 입력 받아 연결리스트 형태로 `graph`에 저장한다.
- 노드 수+1만큼의 부모 테이블 `parent`를 생성하고 자기 자신으로 초기화시킨다.
- 시작 노드를 1로 하여 너비우선탐색을 진행한다.
- 이 때, 방문 여부를 체크하는 것을 만들지 않고 자신의 부모가 자신인 경우 갱신하지 않은 것 즉, 방문을 하지 않은 것이므로 이를 이용하여 방문 여부를 체크한다.
- 2번 노드부터 자신의 부모를 출력한다. 
---
=> [펭귄] 2021.06.11

dkswndms4782/dynamic_programming_1/17626_FourSquares.cpp, dkswndms4782/dynamic_programming_1/9655_돌게임.cpp
- [돌게임](https://www.acmicpc.net/problem/9655)
- [FourSquares](https://www.acmicpc.net/problem/17626)
---
- 블로그를 참고하였습니다🥺
- 수가 홀수일때는 상근이가, 짝수일때는 창영이가 이기는 구조입니다.
- 홀수면 SK출력, 짝수면 CY출력
- arr[50001] =  {0,}; 선언 후 idx는 3이하는 idx만큼의 값 할당. 
- 나머지는 5로 초기화
- dp로 현재 값보다 작은 제곱수와 현재 idx-제곱수의 합 중 가장 작은 값 arr에 할당. 
---
=> [감자] 2021.06.23

peacecheejecake/README.md, peacecheejecake/dynamic_programming_1/11726_2xn타일링.py, peacecheejecake/dynamic_programming_1/2579_계단오르기.py
- [11726_2xn 타일링](https://www.acmicpc.net/problem/11726)
- [2579_계단 오르기](https://www.acmicpc.net/problem/2579)
---
- n이 1, 2일 때의 경우의 수는 각각 1, 2이다.
- i번째 경우의 수는 i - 1번째 및 i - 2번째 경우의 수 합이다.
- `(a + b) % c == (a % c + b % c) % c`라는 점을 이용해 `table`에는 10007로 나눈 나머지를 담는다.
- `table`의 마지막(n번째) 원소를 출력한다.
- 전체 계단 수가 3보다 작으면, 모든 점수를 더해서 출력한다.
- 그렇지 않은 경우, 다음과 같이 구한다.
- 1~3층에서 얻을 수 있는 최대 점수를 `best_scores`에 담는다.
- 4층부터는 다음의 두 경우 중 최댓값을 이전 계단까지의 최대 점수로 한다.
1. 직전 계단을 밟은 경우 : 세 번째 전 계단까지의 최대 점수에 직전 계단의 점수
2. 직전 계단을 밟지 않은 경우 : 두 번째 전 계단까지의 최대 점수
- `이전 계단까지의 최대 점수 + 현재 층의 점수`를 `best_scores`에 담는다.
- `best_scores`의 마지막 원소를 출력한다.
=> [튜브] 2021.06.25

dkswndms4782/dynamic_programming_1/11726_2xn타일링.cpp, dkswndms4782/dynamic_programming_1/2579_계단오르기.cpp
- [2xn 타일링](https://www.acmicpc.net/problem/11726)
- [계단오르기](https://www.acmicpc.net/problem/2579)
---
- 점화식
- (idx = 1,2) -> arr[idx] = idx
- (idx > 2) -> arr[n] = arr[n-1] + arr[n-2]
- arr[n-1]은 arr[n]번째에서 맨 뒤에 1x2블록을 붙이는 경우의 수
- arr[n-2]는  arr[n]번째에서 맨 뒤에 2x1블록을 두개 가로로 붙이는 경우의 수
- 점화식
- (i = 1, 2) -> score[1][1] =score[1][0], score[2][1] =  score[2][0], score[2][2] = score[1][1] + score[2][0]
- (i > 2) -> score[i][2] = score[i - 1][1] + score[i][0];
score[i][1] = max(score[i - 2][1], score[i - 2][2]) + score[i][0];
- 첫번째 idx는 계단의 순서, 두번째 idx는 연속으로 오른 계단의 수
- score[i][0]은 현재 계단의 점수
- 현재 idx가 i라고 할때, score[i][2]는 바로 직전 계단에서 올라오는 경우의 수밖에 없음. 
- 현재 idx가 i라고 할때, score[i][1]은 두칸 밑 계단에서 올라오는 경우의 수인데, 두칸 밑 계단에서 연속으로 1칸, 2칸 오른것은 상관없기때문에 더 큰값에 score[i][0]을 더함
---
=> [감자] 2021.06.25

opijae/dynamic_programming_1/11726_2xn타일링.py, opijae/dynamic_programming_1/2579_계단오르기.py
- [2xn타일링](https://www.acmicpc.net/problem/11726)
- [계단오르기](https://www.acmicpc.net/problem/2579)
---
- 현재 타일은 이전 타일(세로로 했을때) + 전전 타일(가로로 했을때)의 값을 더해준다.
- 어려웠다,.....
- 계단의 값을 저장하는 `stairs` , 계단의 최대 값을 저장하는 `dp` 배열을 만든다.
- 3개연속으로 밟으면 안되니 현재 밟으려는 칸을 기준으로 전 3칸을 봐 현재 칸까지 올수 있는 경우의 수를 구한다,
---
=> [후미] 2021.06.25

peacecheejecake/README.md, peacecheejecake/dynamic_programming_1/11053_가장긴증가하는부분수열.py, peacecheejecake/dynamic_programming_1/11727_2xn타일링2.py
- [11727_2xn 타일링 2](https://www.acmicpc.net/problem/11727)
- [11053_가장 긴 증가하는 부분 수열](https://www.acmicpc.net/problem/11053)
---
- 가장 끝에 가로 길이가 2인 타일이 들어올 때, 경우의 수가 2가 된다는 점이 `11726_2xn 타일링`과 다르다.
- 따라서, 점화식을 `table[i] = table[i - 1] + 2 * table[i - 2]`와 같이 세울 수 있다.
- `table`의 모든 원소를 1로 초기화한다.
- `j < i`이고 `arr[j] < arr[i]`)를 만족하는 j에 대해서, `table[j]` 값의 최댓값을 구하고, 여기에 1을 더하여 `table[i]`를 갱신한다.
- `table`의 최댓값이 `가장 긴 증가하는 부분 수열`의 길이가 된다.
=> [튜브] 2021.06.28

dkswndms4782/dynamic_programming_1/11053_가장긴증가하는부분수열.cpp, dkswndms4782/dynamic_programming_1/11727_2xn타일링2.cpp
- [2xn 타일링2](https://www.acmicpc.net/problem/11727)
- [가장 긴 증가하는 부분 수열](https://www.acmicpc.net/problem/11053)
---
- 점화식
- (idx = 1) -> arr[1] = 1
- (idx = 2) -> arr[2] = 3
- (idx > 2) -> arr[n] = arr[n-1] + arr[n-2] * 2
- 마지막 두칸이 가로2칸 쌓은 것, 2x2 한칸이 되는 경우 2경우가 있어서 *2를 해주었다. 
- 현재 숫자와 이전 숫자들을 비교한 후, 이전 숫자보다 현재 숫자가 크다면, 길이 비교
- 길이 비교를 했을 때 현재 길이보다 이전 숫자의 길이가 크거나 같으면, 현재 길이는 이전숫자 + 1이 된다. 
---
=> [감자] 2021.06.28

peacecheejecake/.gitignore, peacecheejecake/README.md, peacecheejecake/dynamic_programming_1/1912_연속합.py, peacecheejecake/dynamic_programming_1/9465_스티커.py
- [1912_연속합](https://www.acmicpc.net/problem/1912)
- [9465_스티커](https://www.acmicpc.net/problem/9465)
---
- 주어진 수열을 `numbers`에 담는다.
- 수열이 i번째 원소까지만 있다고 생각할 때 최대 연속합을 구한다.
- 직전 최대 연속합이 음수이면 연속합을 이어가고, 아니면 연속합을 새로 시작한다.
- 어느 경우든 `numbers[i]`가 포함되므로, `numbers`를 앞에서부터 갱신하면 된다.
- 각각의 점수를 2xn 리스트 `stickers`에 담는다.
- `max_table[i]`은 i번째 열까지의 최댓값이다. 마지막 스티커 위치가 다음 열 계산에 영향을 주므로, (`윗쪽 스티커를 선택했을 때 최댓값`, `아랫쪽 스티커를 선택했을 때의 최댓값`)을 담은 tuple로 저장한다.
- `max_table[0]`은 `stickers[0]`과 같다.
- `max_table[1]`은 `stickers[1]`과 `stickers[0]`의 원소를 교차로 더한 것과 같다.
- i이 2 이상일 때, `max_table[i]`은 다음과 같은 규칙으로 구한다.
- i번째 행에서 위쪽 스티커를 고른다면(`upper`), 두 가지 경우의 수가 가능하다.
1. i-1열의 아래쪽 스티커를 선택하기
2. i-2열의 위쪽 스티커를 선택하기 위해 i-1열에서는 아무것도 선택하지 않기
- 둘 중 최댓값이 `max_table[i]`의 위쪽 원소가 된다.
- 같은 방법으로 `max_table[i]`의 아래쪽 원소를 구한다.
- 어떤 경우에도 마지막 …
=> [튜브] 2021.06.29

dkswndms4782/dynamic_programming_1/11055_가장큰증가부분수열.cpp, dkswndms4782/dynamic_programming_1/1890_점프.cpp
- [가장 큰 증가 부분 수열](https://www.acmicpc.net/problem/11055)
- [점프](https://www.acmicpc.net/problem/1890)
---
- 현재 숫자가 이전 숫자보다 크고 현재 합이 이전 합과 현재 값의 합보다 작은 경우 현재 합에 이전 합 + 현재 값을 할당
- 현재 합이 0일경우 현재 값 할당
- 이중포문사용
- dp[0][0] = 1
- dp[i][j]가 0일경우와 마지막 도착지의 경우 continue
- i + 현재값 혹은 j + 현재값이 N보다 작을 경우, 이동해준 좌표에 dp[i][j]더해주기
- 2^63-1만큼의 개수가 나올 수 있었으므로 int형에 담아줄 수 없음. long long int로 배열 자료형 지정
---
=> [감자] 2021.06.30

opijae/dynamic_programming_1/1106_호텔.py, opijae/dynamic_programming_1/15486_퇴사2.py, opijae/dynamic_programming_1/2156_포도주시식.py
- [퇴사2](https://www.acmicpc.net/problem/15486)
- [포도주시식](https://www.acmicpc.net/problem/2156)
---
- 입력이 `시간, 급여` 로 주어지니 `arr[i+t]=max(arr[i+t],_max+p)` 식으로 오늘 상담을 했다면 끝나는 날 기준 최대 금액을 구하는 식으로 한다.
- `_max`는 상담을 꼭 매일 받아야 최대값이 나온다는 보장이 없으니 현재 날짜 기준 최대 금액을 가지고 있다 다음 상담 날짜를 잡을 때 더해줘야된다.
- 앞서 풀었던 [계단오르기](https://github.com/boostcamp-ai-tech-4/coding-test-study/pull/131) 랑 비슷한 문제인다.
- 다른점은 계단오르기는 `꼭 끝점을 밟아야되는데` 이건 아니다.
- 이 문제에서는 OOX 처럼 마지막껄 안마셔도 된다는 뜻이다.
---
- 다른 분 풀이를 보면서 얻은  `퇴사2` 700ms 줄인 꿀팁????
1. max vs if
`max` 를 안쓰고 손수 `if`문 쓰니 300ms가 주는 것을 확인 할 수 있다.
```python
arr[i+t]=max(arr[i+t],_max+p)  # 2556 ms
```
```python
if arr[i+t]<p+_max:
arr[i+t]=p+_max # 2292 ms
```
2. 함수 사용
```python  
n= int(input())  # 2292ms
arr=[0]*(n+1)
_max=0
......
중략
......
````
```python
def solve():  # 1868ms
n= …
```
=> [후미] 2021.07.02

dkswndms4782/dynamic_programming_1/10844_쉬운계단수.cpp, dkswndms4782/dynamic_programming_1/2293_동전1.cpp
- [쉬운계단수](https://www.acmicpc.net/problem/10844)
- [동전1](https://www.acmicpc.net/problem/2293)
---
- 한자리수는 1~9
- 두번째부터는 0 사용 가능
- n번째 자릿수가 0이면 1가지 경우의 수(1인경우)이므로 dp[i-1][1]
- n번째 자릿수가 9이면 1가지 경우의 수(8인경우)이므로 dp[i-1][8]
- n번째 자릿수가 나머지 숫자면 dp[i-1][j-1] + dp[i-1][j+1]
- 동전의 가치와 같은 값은 1가지 경우의 수가 무조건 추가
- 이때 dp[j] = dp[j] + dp[j - coin[i]]가 되어야함
- 각 coin의 값부터 K값까지 dp의 경우의 수 더해줌
---
=> [감자] 2021.07.05

peacecheejecake/README.md, peacecheejecake/dynamic_programming_1/21317_징검다리건너기.py
- [징검다리 건너기](https://www.acmicpc.net/problem/21317)
---
- n이 1이면 0을 출력하고 종료한다.
- `stones`에 1부터 N-1까지 에너지 정보를 튜플로 저장한다.
- 먼저 작은 점프와 큰 점프만 가능한 경우를 계산해서 `table`에 계산한다.
- 3부터 N까지 돌까지 마지막이 매우 큰 점프일 경우가 기존 `table`의 값보다 작을 경우, 그 이후의 최소 에너지를 계산해서 `sup_cands`에 넣는다.
- `sup_cands`가 빈 리스트인 경우(갱신하지 않는 것이 최선인 경우), `table[-1]`을 출력한다.
- 그렇지 않으면, `sup_cands`의 원소 중 최솟값을 출력한다.
=> [튜브] 2021.07.07

sally/README.md, sally/shortest_path/13549_숨바꼭질 3(1).cpp, sally/shortest_path/1753_최단경로.cpp
- [1753_최단경로](https://www.acmicpc.net/problem/1753)
- [13549_숨바꼭질 3](https://www.acmicpc.net/problem/13549)
---
> `시간복잡도`: O((V+E)logV)
> - V는 정점의 개수
> - E는 한 정점의 주변 노드
- 다익스트라 알고리즘 사용하여 풀었음
- 시간, 공간복잡도 생각 안하고 풀었다가.. 시간 허비했다...
- 일단 인접행렬쓰면 메모리 초과가 나고, priority_queue 안쓰고 모든 간선을 한번씩만 탐색하는 방법은 시간초과가 난다.
> `시간복잡도`: O(VlogV) 
> - V는 두 사람 사이의 거리
> - 우선순위 큐에 넣고 빼는 과정 1회 당 logV (상수배 생략)
> - 앞서 우선순위 큐에 넣고 빼는 과정을 최악의 경우, V만큼 수행
- 이전이랑 똑같이 풀이했는데, 자꾸 틀렸대서 확인해봤더니
- `*2` → `+1` → `-1` 순서대로 큐에 넣어줘야했음 → [이유 참고](https://www.acmicpc.net/board/view/54741)
---
=> [샐리] 2021.07.13

dkswndms4782/two_pointer/1806_부분합.cpp, dkswndms4782/two_pointer/3151_합이0.cpp
- [부분합](https://www.acmicpc.net/problem/1806)
- [합이0](https://www.acmicpc.net/problem/3151)
---
- 합이 S보다 큰 경우 start좌표를 +1 -> 최소 길이 구함
- 합이 S보다 작은 경우 end좌표를 +1
> `시간복잡도`: O(n^2 log n) (이분탐색을 시행했기때문)
- [여기](https://t-anb.tistory.com/26)를 참고했습니다.
- 각 값을 더한 값의 부호 반대값을 tmp변수에 할당
- lower bound함수는 tmp값보다 큰 값중 가장 작은 값(tmp포함)의 index return(1)
- upper bound함수는 tmp값을 초과하는 값 중 가장 작은 값의 index return(2)
- (2)에서 (1)빼주면 조합의 개수 나옴
- count에 더해준 후 cout
=> [감자] 2021.08.02

sally/README.md, sally/two_pointer/20366_같이 눈사람 만들래.cpp, sally/two_pointer/20442_ㅋㅋ루ㅋㅋ.cpp
- [20442_ㅋㅋ루ㅋㅋ](https://www.acmicpc.net/problem/20442)
- [20366_같이 눈사람 만들래?](https://www.acmicpc.net/problem/20366)
---
- 문제 해석과 예외처리에 시간을 많이 들였다.
- K의 수와 R의 수를 누적해서 저장해둔다.
- a 포인터는 앞에서부터, b 포인터는 뒤에서부터 탐색을 시작
- 각각 앞에서부터, 뒤에서부터 카운트한 K의 수를 사용한다. (각각을 A, B라고 해보자)
- 앞에서부터 K의 수를 카운트한 값: K[a] → **A**
- 뒤에서부터 K의 수를 카운트한 값: K[`문자열길이 - 1`] - K[b] → **B**
- A가 더 큰 경우에는 B가 한칸 앞으로 와야한다.
- B가 더 큰 경우에는 A가 한칸 뒤로 가야한다.
- 해당 부분 → `if(K[a] < l) a++; else b--;`
- 예외처리 힘들었던 부분: 
- `int l = K[s_len - 1] - K[b];`
- `if (str[b] == 'K') l++; // 예외처리 중요 // KKKR`
- 왜 계속 틀렸냐면...
- RKRR의 경우에는, K[] = 0,1,1,1 (마지막에 R이 오는 경우)
- RKKK의 경우에는, K[] = 0,1,2,3 (마지막에 K가 오는 경우)
- 뒤에서부터 수를 셀 때, `int l = K[s_len - 1] - K[b] + 1;` 이렇게 두고 풀었을 때, "RKRR"의 경우에 문제가 생겼음
- → K가 없는데 1개로 카운트하는 오류
- 그래서 기본적으로 `int l = …
=> [샐리] 2021.08.03

dkswndms4782/brute_force/14501_퇴사.cpp, dkswndms4782/brute_force/9079_동전게임.cpp
- [동전게임](https://www.acmicpc.net/problem/9079)
- [퇴사](https://www.acmicpc.net/problem/14501)
---
> `시간복잡도`: O(T * 2^N) (N : 판의 크기)
- 각 뒤집을 수 있는 행(가로,세로,대각선)을 배열에 8x3x2의 형태로 저장
- 비트마스크를 이용하여 8개의 비트를 나타내고, 각 자리가 1인지 0인지에 따라 그 자리에 해당하는 행을 뒤집을지 말지 결정
- 총 2*8의 동전을 뒤집는 경우의 수가 나오고, 뒤집었을 때 판이 다 똑같은 면일 경우 result갱신
- 출력
> `시간복잡도`: O(N)..?...
- 재귀를 사용하여 풂
- 현재 상담 날짜가 N과 같으면 result갱신, return
- 현재 상담 날짜가 N보다 크면 return
- 현재 상담 날짜가 N보다 작으면 {1)현재 상담 X, 다음 날짜로 재귀 2)현재 상담 O, 다음 가능 날짜로 재귀} 이렇게 재귀
=> [감자] 2021.08.09

peacecheejecake/README.md, peacecheejecake/brute_force/16439_치킨치킨치킨.py, peacecheejecake/brute_force/16937_두스티커.py
- [두 스티커](https://www.acmicpc.net/problem/16937)
- [치킨치킨치킨](https://www.acmicpc.net/problem/16439)
---
> `시간복잡도`: O(N^2) 
- 순열을 이용해 스티커를 두 개씩 뽑는다.
- 두 스티커의 넓이 합이 모눈종이 넓이보다 큰지 검사한다.
- 스티커를 90도씩 돌릴 수 있으므로, 각각의 쌍마다 네 가지 경우를 검사한다. 이 때 한 쪽 방향은 더하고, 한 쪽 방향은 둘 중 최댓값을 택해서 모눈종이 한 변 길이와 비교한다.
- 네 가지 경우 중 조건을 만족하는 경우가 발견되면, 최댓값을 갱신하고 다음 두 스티커를 찾는다.
> `시간복잡도`: O(NM^3)
- 순열을 이용해 세 가지 치킨을 고르고, 모든 경우를 완전탐색한다.
=> [튜브] 2021.08.10

dkswndms4782/brute_force/16439_치킨치킨치킨.cpp, dkswndms4782/brute_force/16937_두스티커.cpp
- [두 스티커](https://www.acmicpc.net/problem/16937)
- [치킨치킨치킨](https://www.acmicpc.net/problem/16439)
---
> `시간복잡도`: O(N*2)(permutation * N번 돌면서 -1값 찾기)
- 순열을 이용해 2개의 스티커 뽑음
- 스티커 두개의 세로를 더한 길이가 H보다 작거나 같고, 가로의 값중 큰 값이 W보다 작거나 같으면 현재 스티커 2개 사용가능(가로, 세로 반대도 마찬가지) 
- 스티커를 돌리는 경우의 수는 (돌리는 것:1, 원래 : 0){(0,0), (1,0), (0,1), (1,1)}이 있음
- 8개의 경우에서 하나라도 참이 되면 두 스티커의 넓이를 더해 최댓값 갱신
> `시간복잡도`: O(N(N+M))(permution*(M만큼 돌며 -1값인지 확인 + 회원 전체 확인))
- 순열로 3개의 치킨 브랜드를 뽑음
- 각 회원별로 3개의 치킨 브랜드 중 가장 큰 값을 가지고 있는것을 sum에 더해줌
- result와 sum값을 비교해 최댓값 갱신 
---
=> [감자] 2021.08.10

sally/leetcode/139_Word Break.cpp, sally/leetcode/207_Course Schedule.cpp, sally/leetcode/242_Valid Anagram.cpp, sally/leetcode/435_Non-overlapping Intervals.cpp
- [242. Valid Anagram](https://leetcode.com/problems/valid-anagram/)
- [435. Non-overlapping Intervals](https://leetcode.com/problems/non-overlapping-intervals/)
- [207. Course Schedule](https://leetcode.com/problems/course-schedule/)
- [139. Word Break](https://leetcode.com/problems/word-break/)
---
- 알파벳 소문자 길이의 int 배열(alpha)을 생성
- string s는 각 자리의 문자에 해당하는 배열의 값을 1씩 더해주고, 반대로 string t는 각 자리의 문자에 해당하는 배열의 값을 1씩 빼준다.
- alpha 배열의 모든 값이 0인지 확인한다.
- [참고](https://leetcode.com/problems/non-overlapping-intervals/discuss/1520653/C%2B%2B-Sorting)
- 우선, 인풋으로 들어오는 벡터를 정렬한다.
- 각 interval 벡터가 오버랩이 되는 경우와 오버랩이 되지 않는 경우로 나누어서 생각한다.
- 오버랩이 안되는 경우는 interval[i-1][1] <= interval[i][0]인 경우이다.
- 오버랩이 되는 경우, 지워야하는 interval의 수를 하나 증가시키고, 끝부분이 더 앞에 있는 interval을 선택하여 남겨둔다. (다음 interval과 비교하기 위해)
- …
=> [샐리] 2021.10.17

peacecheejecake/programmers/12973_짝지어제거하기.py, peacecheejecake/programmers/17677_뉴스클러스터링.py, peacecheejecake/programmers/43166_타겟넘버.py, peacecheejecake/programmers/60058_괄호변환.py, peacecheejecake/programmers/72411_메뉴리뉴얼.py, peacecheejecake/programmers/77485_행렬테두리회전하기.py
- [메뉴 리뉴얼](https://programmers.co.kr/learn/courses/30/lessons/72411)
- [괄호 변환](https://programmers.co.kr/learn/courses/30/lessons/60058)
- [뉴스 클러스터링](https://programmers.co.kr/learn/courses/30/lessons/17677)
---
- `{단품 메뉴 수: {메뉴 조합: count}}` 형식으로 각각의 조합이 주문된 횟수를 셉니다.
- 각각의 주문 길이 이하만큼, combinations로 모든 조합을 만들어 counter에 반영합니다.
- counter에서 메뉴 수마다 최댓값을 가진 조합을 리스트에 담는다. 단, 최댓값이 1 이하이면 제외합니다.
- '('을 1, ')'을 0으로 보고, 이진수로 변환해서 풀었습니다. 둘로 나누거나 뒤집는 연산을 쉽게 하기 위해 그랬는데, 풀고 나니 효율적인지는 모르겠습니다.
- 주어진 p를 이진수로 변환하고, `convert` 함수가 올바른 괄호로 고칩니다.
- `is_right` 함수는 stack을 이용해서 `올바른 괄호 문자열`인지 검사합니다. 빈 stack에 0이 들어오거나 마지막에 stack이 비어있지 않다면 False입니다.
- `find_u` 함수로 p에서 u를 찾습니다. 구한 u의 길이를 이용해 나머지 v를 구합니다.
- `reverse` 함수는 XOR 연산을 통해 이진수를 뒤집습니다.
- 문제의 지시를 따라 `convert`를 재귀적으로 호출합니다.
- `re.findall`으로 모든 알파벳 pair를 찾습니다. …
=> [튜브] 2021.12.18.
